
/*
 * ***************************************************************************
 * *  File: common.c                                         Part of Duris *
 * *  Usage: almost all of the tables and wordlists.
 * * *  Copyright  1990, 1991 - see 'license.doc' for complete information.
 *  * *  Copyright  1994, 1995 - Duris Systems Ltd.
 * *
 * ***************************************************************************
 */

#include "defines.h"
#include "objmisc.h"
#include "skillrec.h"
#include "spells.h"
#include "flagdef.h"



const char *specdata[][MAX_SPEC] = {
  {"", "", "", ""},         //None
  {"&+BSwordsman", "&+yGuardian", "&+CSw&+cas&+Lhbuc&+ckl&+Cer&n", ""},      //Warrior
  {"&+cBlademaster", "&+gHuntsman", "&+gMa&+yrsha&+gll&n", ""},    //Ranger
  {"&+rPyr&+Rokine&+rtic", "&+MEn&+mslav&+Mer", "&+bPsyche&+Lporter", ""},         //Psionicist
  {"&+wCrusa&+Wder", "&+WCavalier", "", ""},    //Paladin
  {"&+LDark Knight", "&+LDem&+ronic Ri&+Lder", "", ""},  //Anti-Paladin
  {"&+YZealot&n", "&+WHealer&n", "&+cHoly&+Wman&n", ""},      //Cleric
  {"&+rRe&+Rd Dra&+rgon", "&+gElap&+Ghi&+gdist", "", ""},   //Monk
  {"&+gFo&+Gre&+gst Druid", "&+cStorm &+CDruid", "", ""},       //Druid
  {"&+rEl&+Rem&+Lenta&+Rli&n&+rst", "&+WSpir&+Citua&+Wlist", "&+yAni&+Ymal&n&+yist", ""},       //Shaman
  {"&+MWild&+mmage", "&+LWizard", "&+LShadow&+wmage", ""},      //Sorcerer
  {"&+mDia&+rbolis", "&+mNe&+Lcro&+mlyte", "&+LReap&+wer", ""}, //Necromancer
  {"&+CAir Magus", "&+BWater Magus", "&+rFire Magus", "&+yEarth Magus"},        //Conjurer
  {"&+rAssassin&n", "&+LThief&n","Not Used" , "&+LSh&+wa&+Ldow &+BArc&+bher&n"},         //Rogue
  {"", "", "", ""}, //Assassin
  {"&+yBr&+Lig&+yand", "&+yBounty &+LHunter", "", ""},  //Mercenary
  {"&+rD&+mis&+gha&+crm&+yon&+bist", "&+RScoundrel", "&+YMin&n&+ystr&+Yel", ""},        //Bard
  {"", "", "", ""},         //Thief
  {"", "", "", ""},         //Warlock
  {"", "", "", ""},         //MindFlayer
  {"&+CBat&n&+ctle-For&+Cger&n", "&+LBla&+ccksm&+Lith&n", "", ""},   //Alchemist
  {"&+rMa&+RUle&+rR", "&+RRa&+rGe&+Rlo&+rRd", "", ""},  //Berserker
  {"&+CI&+Wc&+Ce &+LR&+Le&+wa&+wv&+Le&+Lr", "&+rF&+Rl&+Ya&+Rm&+re &+LR&+Le&+wa&+wv&+Le&+Lr", "&+bSh&+Bo&+Wck &+LR&+Le&+wa&+wv&+Le&+Lr", "&+LEa&+yrt&+Lh R&+yea&+Lve&+yr"},      //Reaver
  {"&+BM&+Yag&+Bic&+Yia&+Bn&n", "&+LDark &+mDreamer&n", "", ""},         // Illusionist
  {"", "", "", ""},  // Unused
  {"&+LDeath&+rlord", "&+LShadow&+rlord", "", ""},      // Dreadlord
  {"&+cWindtalker", "&+WFro&+cst &+CMagus", "&+WCo&+Ysm&+Wom&+Yanc&+Wer", ""},     // Ethermancer
  {"&+YLight&+Wbringer", "&+WInq&+wuisi&+Wtor", "", ""},       //Avenger
  {"&+wMedium&n", "&+YT&+Re&+rmpl&+Ra&+Yr&n", "&+C&+WT&+ch&+Ca&+Wu&+Cm&+ca&+Ct&+Wu&+Cr&+cg&+Ce&n", ""}, // Theurgist
  {"", "", "", ""}
};

/*
 * mob race lookup table, used to assign a race to a mob when reading them
 * from the .mob file.  Need to update this table when adding new races.
 *
 * A note on the codes:  when I set them up, I tried to follow a pattern of
 * general/specific, like all 'player' races are "Px", all elementals are
 * "Ex", undead "Ux", humanoid "Hx", animals "Ax", etc.  Current this is not
 * used for anything specific, but it looked like a good idea, so try to
 * follow it if you add more races.  JAB
 */
extern const struct race_names race_names_table[LAST_RACE + 2];
const struct race_names race_names_table[LAST_RACE + 2] = {
  {"None", "None", "Unknown Race", "NO"},
  {"Human", "Human", "&+CHuman&n", "PH"},
  {"Barbarian", "Barbarian", "&+BBarbarian&n", "PB"},
  {"Drow Elf", "DrowElf", "&+mDrow Elf&n", "PL"},
  {"Grey Elf", "GreyElf", "&+cGrey Elf&n", "PE"},
  {"Mountain Dwarf", "MountainDwarf", "&+YDwarf&n", "PM"},
  {"Duergar Dwarf", "DuergarDwarf", "&+rDuergar&n", "PD"},
  {"Halfling", "Halfling", "&+yHalfling&n", "PF"},
  {"Gnome", "Gnome", "&+RGnome&n", "PG"},
  {"Ogre", "Ogre", "&+bOgre&n", "PO"},
  {"Troll", "Troll", "&+gTroll&n", "PT"},
  {"Half-Elf", "Half-Elf", "&+CHalf&+c-Elf&n", "P2"},
  {"Illithid", "Illithid", "&+MIllithid&n", "MF"},
  {"Orc", "Orc", "&+LOrc&n", "HO"},
  {"Thri-Kreen", "Thri-Kreen", "&+GThri-&+YKreen&n", "TK"},
  {"Centaur", "Centaur", "&+gCen&+Ltaur&n", "CT"},
  {"Githyanki", "Githyanki", "&+GGith&+Wyanki&n", "GI"},
  {"Minotaur", "Minotaur", "&+LMino&+rtaur&n", "MT"},
  {"Shade", "Shade", "&+LShade&n", "SH"},
  {"Revenant", "Revenant", "&+cRevenant&n", "RE"},
  {"Goblin", "Goblin", "&+GGoblin&n", "HG"},
  {"Lich", "Lich", "&+LL&+mic&+Lh&n", "UL"},
  {"Vampire", "Vampire", "&+RVam&+rpi&+Rre&n", "UM"},
  {"Death Knight", "DeathKnight", "&+LDeath &+bKnight&n", "UK"},
  {"Shadow Beast", "ShadowBeast", "&+LShadow &+rBeast&n", "US"},
  {"Storm Giant", "StormGiant", "&+WS&+wt&+Wo&+wr&+Wm &+wG&+Wi&+wa&+Wn&+Wt&n", "SG"},
  {"Wight", "Wight", "&+RW&+ri&+Rg&+rh&+Rt&n", "UW"},
  {"Phantom", "Phantom", "&+WPha&+Lntom&n", "UP"},
  {"Harpy", "Harpy", "&+yHarpy&n", "MH"},
  {"Orog", "Orog", "&+LOr&+yo&+Lg&n", "OR"},
  {"Githzerai", "Githzerai", "&+WGith&+Gzerai&n", "GZ"},
  {"Drider", "Drider", "&+mDri&+Lder&n",                              "DR"},
  {"Kobold", "Kobold", "&+LKobold&n",                                 "KB"},
  {"Planetbound Illithid", "Pillithid", "&+MIllithid&n",              "PI"},
  {"Kuo Toa", "KuoToa", "&+GKu&+Lo T&+Goa&n", "KT"},
  {"Wood Elf", "WoodElf", "&+gW&+Goo&+gd E&+Glf&n", "WE"},
  {"Firbolg", "Firbolg", "&+yFir&+cbolg&n", "FB"},
  {"Agathinon", "Agathinon", "&+WAga&+Yt&+Whin&+Yo&+Wn&n",            "AG"},
  {"Eladrin", "Eladrin", "&+cE&+Cl&+Wadr&+Ci&+cn&n",                  "EL"},
  {"Gargoyle", "Gargoyle", "&+LGar&+wgo&+Lyle&n", "MG"},
  {"Fire Elemental", "FireElemental", "&+rFire Elemental&n", "EF"},
  {"Air Elemental", "AirElemental", "&+CAir Elemental&n", "EA"},
  {"Water Elemental", "WaterElemental", "&+BWater Elemental&n", "EW"},
  {"Earth Elemental", "EarthElemental", "&+yEarth Elemental&n", "EE"},
  {"Demon", "Demon", "&+LD&+we&+Lm&+wo&+Ln&n", "X"},
  {"Devil", "Devil", "&+RD&+re&+Rv&+ri&+Rl&n", "Y"},
  {"Undead ", "Undead", "&+LUn&+wdead&n", "U"},
  {"Vampire", "Vampire", "&+rV&+Ra&+rm&+Rp&+ri&+Rr&+re&n", "UV"},
  {"Ghost", "Ghost", "&+WG&+wh&+Wo&+ws&+Wt&n", "UG"},
  {"Lycanthrope", "Lycanthrope", "&+LL&+yy&+Lc&+ya&+Ln&+yt&+Lh&+yr&+Lo&+yp&+Le&n", "L"},
  {"Giant", "Giant", "&+yGiant&n", "G"},
  {"Half Orc", "HalfOrc", "&+wHalf &+LOrc&n", "H2"},
  {"Golem", "Golem", "&+yGolem&n", "OG"},
  {"Faerie", "Faerie", "&+MFa&+mer&+Mie&n", "HF"},
  {"Dragon", "Dragon", "&+LDragon&n", "D"},
  {"Dragonkin", "Dragonkin", "&+LDra&+wgon&+Lkin&n", "DK"},
  {"Reptile", "Reptile", "&+GR&+ge&+Gp&+gt&+Gi&+gl&+Ge&n", "R"},
  {"Snake", "Snake", "&+gS&+Gn&+ga&+Gk&+ge&n", "RS"},
  {"Insect", "Insect", "&+wI&+Ln&+ws&+Le&+wc&+Lt&n", "I"},
  {"Arachnid", "Arachnid", "&+wA&+Lr&+wa&+Lc&+wh&+Ln&+wi&+Ld&n", "AS"},
  {"Aquatic Animal", "Aquatic Animal", "&+bAquatic Animal&n", "F"},
  {"Winged Animal", "Winged Animal", "&+WWinged Animal&n", "B"},
  {"Quadruped", "Quadruped", "&+yQuadruped&n", "AE"},
  {"Primate", "Primate", "&+yP&+Lr&+yi&+Lm&+ya&+Lt&+ye&n", "AA"},
  {"Humanoid", "Humanoid", "&+LH&+yu&+Lm&+ya&+Ln&+yo&+Li&+yd&n", "H"},
  {"Animal", "Animal", "&+yAnimal&n", "A"},
  {"Plant", "Plant", "&+gPlant&n", "VT"},
  {"Herbivore", "Herbivore", "&+GH&+ge&+Gr&+gb&+Gi&+gv&+Go&+gr&+Ge&n", "AH"},
  {"Carnivore", "Carnivore", "&+rC&+Ra&+rr&+Rn&+ri&+Rv&+ro&+Rr&+re&n", "AC"},
  {"Parasite", "Parasite", "&+LP&+wa&+Lr&+wa&+Ls&+wi&+Lt&+we&n", "AP"},
  {"Beholder", "Beholder", "&+mBe&+Lho&+mld&+Ler&n", "BH"},
  {"Dracolich", "Dracolich", "&+LDr&+wa&+Lc&+wo&+Ll&+wi&+Lch&n", "UD"},
  {"Slime", "Slime", "&+GSlime&n", "SL"},
  {"Angel", "Angel", "&+WA&+Cng&+Wel&n", "AN"},
  {"Rakshasa", "Rakshasa", "&+rRaks&+Yhasa&n", "RA"},
  {"Construct", "Construct", "&+LC&+won&+Lstr&+wuc&+Lt&n", "CN"},
  {"Efreet", "Efreet", "&+rEf&+Rre&n&+ret&n", "E"},
  {"Snow Ogre", "Snow Ogre", "&+WSnow &n&+bOgre&n", "SO"},
  {"Beholderkin", "Beholderkin", "&+mBeholderkin&n", "BK"},
  {"Zombie", "Zombie", "&+GZo&+gmbie&n", "ZO"},
  {"Spectre", "Spectre", "&+wSpe&+Wctre&n", "SP"},
  {"Skeleton", "Skeleton", "&+wSkeleton&n",                           "SK"},
  {"Wraith", "Wraith", "&+LWr&+wai&+Lth&n",                           "WR"},
  {"Shadow", "Shadow", "&+LShadow&n",                                 "SW"},
  {"Purple Worm", "PurpleWorm", "&+mPurple &+LWorm&n",                "PW"},
  {"Void Elemental", "VoidElemental", "&+LVoi&+wd Elemen&+Ltal&n",    "VE"},
  {"Ice Elemental", "IceElemental", "&+CIc&+We Ele&+Cme&+Wnt&+Cal&n", "IE"},
  {"Phoenix", "Phoenix", "&+rP&+Rh&+Yo&+We&+Yn&+Ri&+rx&n", "PX"},
  {"Archon", "Archon", "&+RArch&+Wo&+Rn&n", "AR"},
  {"Asura", "Asura", "&+RAsu&+Yr&+Ra&n", "AU"},
  {"Titan", "Titan", "&+CT&+Wi&+Ct&+Wa&+Cn&n", "TT"},
  {"Avatar", "Avatar", "&+cAv&+Ca&+Wt&+Ca&+cr&n", "AV"},
  {"Bralani", "Bralani", "&+cB&+Cr&+Wala&+Cn&+ci&n", "BR"},
  {"Ghaele", "Ghaele", "&+cG&+Ch&+Wae&+Cl&+ce&n", "GH"},
  {"Whiner", "Whiner", "&+MW&+Wh&+Min&+We&+Mr&n", "WH"},
  {"Incubus", "Incubus", "&+BIn&+bcub&+Bus&n",    "IN"},
  {"Succubus", "Succubus", "&+LS&+ru&+Rccub&+ru&+Ls&n", "SU"},
  {"Fire Giant", "FireGiant", "&+rFi&+Rre Gia&+rnt&n", "FG"},
  {"Frost Giant", "FrostGiant", "&+cFr&+Cos&+Wt G&+Cia&+cnt&n", "IG"},
  {"Deva", "Deva", "&+wD&+Wev&+wa&n", "DV"},
{0}
};

flagDef  wear_bits[] = {
  {"TAKE", "Takeable", 1, 0},
  {"WEAR_FINGER", "Worn on finger", 1, 0},
  {"WEAR_NECK", "Worn on neck", 1, 0},
  {"WEAR_BODY", "Worn on body", 1, 0},
  {"WEAR_HEAD", "Worn on head", 1, 0},
  {"WEAR_LEGS", "Worn on legs", 1, 0},
  {"WEAR_FEET", "Worn on feet", 1, 0},
  {"WEAR_HANDS", "Worn on hands", 1, 0},
  {"WEAR_ARMS", "Worn on arms", 1, 0},
  {"WEAR_SHIELD", "Worn as shield", 1, 0},
  {"WEAR_ABOUT", "Worn about body", 1, 0},
  {"WEAR_WAIST", "Worn about waist", 1, 0},
  {"WEAR_WRIST", "Worn on wrist", 1, 0},
  {"WIELD", "Wieldable (weapon)", 1, 0},
  {"HOLD", "Held", 1, 0},
  {"THROW", "Thrown (not used)", 0, 0},
  {"LIGHT_SOURCE", "Light (obsolete)", 0, 0},
  {"WEAR_EYES", "Worn on eyes", 1, 0},
  {"WEAR_FACE", "Worn on face", 1, 0},
  {"WEAR_EARRING", "Worn as earring", 1, 0},
  {"WEAR_QUIVER", "Worn as quiver", 1, 0},
  {"WEAR_INSIGNIA", "Worn as badge", 1, 0},
  {"WEAR_BACK", "Worn on back", 1, 0},
  {"ATTACH_BELT", "Attachable to belt", 1, 0},
  {"HORSE_BODY", "Worn on horse's body", 1, 0},
  {"WEAR_TAIL", "Worn on tail", 1, 0},
  {"WEAR_NOSE", "Worn in nose", 1, 0},
  {"WEAR_HORN", "Worn on horns", 1, 0},
  {"WEAR_IOUN", "Worn as ioun stone", 1, 0},
  {"SPIDER_BODY", "Worn on spider body", 1, 0},
  {0}
};

flagDef  extra_bits[] = {
  {"GLOW", "Glow", 1, 0},
  {"NOSHOW", "No show", 1, 0},
  {"BURIED", "Buried", 0, 0},
  {"NOSELL", "No sell", 1, 0},
  {"THROW2", "Thrown ranged", 1, 0},
  {"INVISIBLE", "Invisible", 1, 0},
  {"NOREPAIR", "Non repairable", 1, 0},
  {"NODROP", "No drop (cursed)", 1, 0},
  {"RETURNING", "Auto-returning", 1, 0},
  {"ALLOWED_RACES", "Listed races CAN use", 1, 0},
  {"ALLOWED_CLASSES", "Listed classes CAN use", 1, 0},
  {"PROCLIB", "Generic Special Proc", 0, 0},
  {"SECRET", "Secret", 1, 0},
  {"FLOAT", "Floats", 1, 0},
  {"NORESET", "Doesn't repop", 1, 0},
  {"NOLOCATE", "No locate", 1, 0},
  {"NOIDENTIFY", "No identify", 1, 0},
  {"NOSUMMON", "No summon", 1, 0},
  {"LIT", "Lit", 1, 0},
  {"TRANSIENT", "Transient", 1, 0},
  {"NOSLEEP", "No sleep", 1, 0},
  {"NOCHARM", "No charm", 1, 0},
  {"TWOHANDS", "Two-handed", 1, 0},
  {"NORENT", "No rent", 1, 0},
  {"THROW1", "Thrown close", 1, 0},
  {"HUM", "Hum", 1, 0},
  {"LEVITATES", "Levitates", 1, 0},
  {"IGNORE_ITEM", "Ignore item", 1, 0},
  {"ARTIFACT", "Artifact", 1, 0},
  {"WHOLEBODY", "Whole body", 1, 0},
  {"WHOLEHEAD", "Whole head", 1, 0},
  {"ENCRUSTED", "Was encrusted", 0, 0},
  {0}
};

flagDef  extra2_bits[] = {
  {"SILVER", "Made of silver", 1, 0},
  {"BLESS", "Blessed", 1, 0},
  {"SLAY_GOOD", "Slaying good", 1, 0},
  {"SLAY_EVIL", "Slaying evil", 1, 0},
  {"SLAY_UNDEAD", "Slaying undead", 1, 0},
  {"SLAY_LIVING", "Slaying living", 1, 0},
  {"MAGIC", "Magic", 1, 0},
  {"LINKABLE", "Linkable Object", 1, 0},
  {"NOPROC", "Ignore proc", 0, 0},
  {"NOTIMER", "Ignore timer proc", 0, 0},
  {"NOLOOT", "Not lootable", 1, 0},
  {"CRUMBLELOOT", "Crumble when looted", 1, 0},
  {0}
};

flagDef  room_bits[] = {
  {"DARK", "Dark", 1, 0},
  {"LOCKER", "Locker", 0, 0},
  {"NO_MOB", "No mob", 1, 0},
  {"INDOORS", "Indoors", 1, 0},
  {"SILENT", "Silent", 1, 0},
  {"UNDERWATER", "Underwater", 1, 0},
  {"NO_RECALL", "No recall", 1, 0},
  {"NO_MAGIC", "No magic", 1, 0},
  {"TUNNEL", "Tunnel", 1, 0},
  {"PRIVATE", "Private", 0, 0},
  {"ARENA", "Arena", 1, 0},
  {"SAFE", "Safe", 0, 0},
  {"NO_PRECIP", "No precipitation", 1, 0},
  {"SINGLE_FILE", "Single file", 1, 0},
  {"JAIL", "Jail", 1, 0},
  {"NO_TELEPORT", "No teleport", 1, 0},
  {"PRIV_ZONE", "Private zone", 0, 0},
  {"HEAL", "Heal", 1, 0},
  {"NO_HEAL", "No heal", 1, 0},
  {"RENTABLE", "Rentable", 1, 0},
  {"DOCKABLE", "Dockable", 1, 0},
  {"MAGIC_DARK", "Magic darkness", 1, 0},
  {"MAGIC_LIGHT", "Magic light", 1, 0},
  {"NO_SUMMON", "No summon", 1, 0},
  {"GUILD_ROOM", "Guild room", 1, 0},
  {"TWILIGHT", "Twilight", 1, 0},
  {"NO_PSI", "No psionics", 1, 0},
  {"NO_GATE", "No gate/planeshift", 1, 0},
  {"HOUSE", "House", 0, 0},
  {"ATRIUM", "Atrium", 0, 0},
  {"BLOCKS_SIGHT", "Blocks farsee/scan", 1, 0},
  {"BFS_MARK", "BFS mark", 0, 0},
  {0}
};

flagDef  affected1_bits[] = {
  {"BLIND", "Blind", 0, 0},
  {"INVIS", "Invisible", 1, 0},
  {"FARSEE", "Farsee", 1, 0},
  {"DET_INV", "Detect invis", 1, 0},
  {"HASTE", "Haste", 1, 0},
  {"SENSE_LIFE", "Sense life", 1, 0},
  {"MINOR_GLOBE", "Minor globe", 1, 0},
  {"STONE_SKIN", "Stoneskin", 1, 0},
  {"UD_VISION", "Underdark vis", 1, 0},
  {"SHADOW", "Shadow", 0, 0},
  {"WRAITHFORM", "Wraithform", 0, 0},
  {"WATERBREATH", "Waterbreathing", 1, 0},
  {"KNOCKED_OUT", "Knocked out", 0, 0},
  {"PROT_EVIL", "Prot evil", 1, 0},
  {"BOUND", "Bound", 1, 0},
  {"SLOW_POISON", "Slow poison", 1, 0},
  {"PROT_GOOD", "Prot good", 1, 0},
  {"SLEEP", "Slept", 0, 0},
  {"SKILL_AWARE", "Skill aware", 0, 0},
  {"SNEAK", "Sneak", 1, 0},
  {"HIDE", "Hide", 1, 0},
  {"FEAR", "Fear", 0, 0},
  {"CHARM", "Charmed", 0, 0},
  {"MEDITATE", "Meditate", 0, 0},
  {"BARKSKIN", "Barkskin", 1, 0},
  {"INFRAVISION", "Infravision", 1, 0},
  {"LEVITATE", "Levitate", 1, 0},
  {"FLY", "Fly", 1, 0},
  {"AWARE", "Aware", 1, 0},
  {"PROT_FIRE", "Prot fire", 1, 0},
  {"CAMPING", "Camping", 0, 0},
  {"BIOFEEDBACK", "Biofeedback", 1, 0},
  {0}
};

flagDef  affected2_bits[] = {
  {"FIRESHIELD", "Fireshield", 1, 0},
  {"ULTRA", "Ultravision", 1, 0},
  {"DET_EVIL", "Detect evil", 1, 0},
  {"DET_GOOD", "Detect good", 1, 0},
  {"DET_MAGIC", "Detect magic", 1, 0},
  {"MAJOR_PHYS", "Major physical", 0, 0},
  {"PROT_COLD", "Prot cold", 1, 0},
  {"PROT_LIGHT", "Prot lightning", 1, 0},
  {"MINOR_PARA", "Minor paralyze", 0, 0},
  {"MAJOR_PARA", "Major paralyze", 0, 0},
  {"SLOWNESS", "Slowness", 1, 0},
  {"MAJOR_GLOBE", "Major globe", 1, 0},
  {"PROT_GAS", "Prot gas", 1, 0},
  {"PROT_ACID", "Prot acid", 1, 0},
  {"POISONED", "Poisoned", 0, 0},
  {"SOULSHIELD", "Soulshield", 1, 0},
  {"DUERGAR_HIDE", "Duergar hide", 0, 0},
  {"MINOR_INVIS", "Minor invis", 1, 0},
  {"VAMP_TOUCH", "Vampiric touch", 1, 0},
  {"STUNNED", "Stunned", 0, 0},
  {"EARTH_AURA", "Earth aura", 1, 0},
  {"WATER_AURA", "Water aura", 1, 0},
  {"FIRE_AURA", "Fire aura", 1, 0},
  {"AIR_AURA", "Air aura", 1, 0},
  {"HOLDING_BREATH", "Holding breath", 0, 0},
  {"MEMORIZING", "Memorizing", 0, 0},
  {"DROWNING", "Drowning", 0, 0},
  {"PASSDOOR", "Passdoor", 0, 0},
  {"FLURRY", "Flurry", 1, 0},
  {"CASTING", "Casting", 0, 0},
  {"SCRIBING", "Scribing", 0, 0},
  {"HUNTING", "Hunting", 0, 0},
  {0}
};

flagDef  affected3_bits[] = {
  {"TENSORS_DISC", "Tensor's disc", 1, 0},
  {"TRACKING", "Tracking", 0, 0},
  {"SINGING", "Singing", 0, 0},
  {"ECTO_FORM", "Ectoplasmic form", 1, 0},
  {"ABSORBING", "Absorbing", 0, 0},
  {"PROT_ANIMAL", "Protection from animals", 1, 0},
  {"SPIRIT_WARD", "Spirit ward", 1, 0},
  {"GR_SPIRIT_WARD", "Gr. spirit ward", 1, 0},
  {"NON_DETECTION", "Non-detectable", 1, 0},
  {"SILVER", "Made of silver", 0, 0},
  {"PLUSONE", "Plus one", 0, 0},
  {"PLUSTWO", "Plus two", 0, 0},
  {"PLUSTHREE", "Plus three", 0, 0},
  {"PLUSFOUR", "Plus four", 0, 0},
  {"PLUSFIVE", "Plus five", 0, 0},
  {"ENLARGED", "Enlarged", 1, 0},
  {"REDUCED", "Reduced", 1, 0},
  {"COVER", "Has cover", 1, 0},
  {"FOUR_ARMS", "Has four arms", 1, 0},
  {"INERT_BARRIER", "Inertial barrier", 1, 0},
  {"INTEL_FORT", "Intellect fortress", 1, 0},
  {"COLDSHIELD", "Coldshield", 1, 0},
  {"CANNIBALIZE", "Cannibalize", 1, 0},
  {"SWIMMING", "Swimming", 0, 0},
  {"TOWER_IRON_WILL", "Tower of iron will", 1, 0},
  {"UNDERWATER", "Underwater", 0, 0},
  {"BLUR", "Blur", 1, 0},
  {"NECKBITING", "Neckbiting", 0, 0},
  {"ELEM_FORM", "Elemental form", 0, 0},
  {"PASS_WO_TRACE", "Pass w/o trace", 1, 0},
  {"PAL_AURA", "Paladin aura", 1, 0},
  {"FAMINE", "Famine", 0, 0},
  {0}
};

flagDef  affected4_bits[] = {
  {"LOOTER", "Looter", 0, 0},
  {"CARRY_DISEASE", "Carries disease", 1, 0},
  {"SACKING", "Sacking", 0, 0},
  {"SENSE_FOLLOWER", "Sense followers", 1, 0},
  {"STOR_SPHERES", "Stornog's spheres", 1, 0},
  {"STOR_GR_SPHERES", "Stornog's gr. sph", 1, 0},
  {"VAMP_FORM", "Vampiric form", 0, 0},
  {"NO_UNMORPH", "Can't unmorph", 1, 0},
  {"HOLY_SACR", "Holy sacrifice", 1, 0},
  {"BATTLE_ECS", "Battle ecstasy", 1, 0},
  {"DAZZLER", "Dazzler", 1, 0},
  {"PHANTASMAL_FORM", "Phantasmal form", 1, 0},
  {"NOFEAR", "Immune to fear", 1, 0},
  {"REGENERATION", "Regenerates in combat", 1, 0},
  {"AFF4UNUSED15", "Unused", 0, 0},
  {"AFF4UNUSED16", "Unused", 0, 0},
  {"AFF4UNUSED17", "Unused", 0, 0},
  {"MAGE_FLAME", "Mage flame", 1, 0},
  {"GLOBE_DARK", "Globe of darkness", 1, 0},
  {"DEFLECT", "Deflection", 1, 0},
  {"HAWKVISION", "Hawkvision", 1, 0},
  {"MULTICLASS", "Multiclassed NPC", 0, 0},
  {"SANCTUARY", "Sanctuary", 1, 0},
  {"HELLFIRE", "Hellfire", 1, 0},
  {"SENSE_HOLINESS", "Sense holiness", 1, 0},
  {"PROT_LIVING", "Prot living", 1, 0},
  {"DETECT_ILLUSION", "Detect illusion", 1, 0},
  {"AFF4UNUSED28", "Unused", 0, 0},
  {"REV_POLARITY", "Reverse polarity", 1, 0},
  {"NEG_SHIELD", "Negative shield", 1, 0},
  {"TUPOR", "Tupor", 0, 0},
  {"AFF4UNUSED32", "Unused", 0, 0},
  {0}
};

flagDef  affected5_bits[] = {
  {"DAZZLEE", "Dazzled", 0, 0},
  {"MENTAL_ANGUISH", "Mental anguish", 0, 0},
  {"MEMORY_BLOCK", "Memory block", 0, 0},
  {"VINES", "Vines", 0, 0},
  {"AFF5UNUSED5", "Unused", 0, 0},
  {"AFF5UNUSED6", "Unused", 0, 0},
  {"AFF5UNUSED7", "Unused", 0, 0},
  {"WET", "Wet", 0, 0},
  {"AFF5UNUSED9", "Unused", 0, 0},
  {"ENH_HIDE", "Enhanced hide", 1, 0},
  {"LISTEN", "Listen", 0, 0},
  {"DAKTAS_FURY", "Daktas furry", 1, 0},
  {"SHADOW_SHIELD", "Shadow shield", 1, 0},
  {"IMPRISON", "Imprisoned", 1, 0},
  {"TITAN FORM", "Titan form", 1, 0},
  {"DELIRIUM", "Delirium", 1, 0},
  {"SHADE_MOVEMENT", "Shade movement", 1, 0},
  {"NO BLIND", "No blind", 0, 0},
  {"MAGICAL GLOW", "Magical glow", 0, 0},
  {"REFRESHING GLOW", "Refreshing glow", 0, 0},
  {"MINE", "Mine", 1, 0},
  {"STANCE OFFENSIVE", "Stance offensive", 0, 0},
  {"STANCE DEFENSIVE", "Stance defensive", 0, 0},
  {"OBSCURING MIST", "Obscuring mist", 1, 0},
  {"NOT OFFENSIVE", "Non-offensive", 0, 0},
  {0}
};

const char *apply_types[] = {
  "NONE",                       /* * 0 */
  "STR",
  "DEX",
  "INT",
  "WIS",
  "CON",                        /* * 5 */
  "SEX",
  "CLASS",
  "LEVEL",
  "AGE",
  "WEIGHT",                     /* * 10 */
  "HEIGHT",
  "MANA",
  "HITPOINTS",
  "MOVE",
  "GOLD",                       /* * 15 */
  "EXP",
  "AC",
  "HITROLL",
  "DAMROLL",
  "SV_PARA",                    /* * 20 */
  "SV_ROD",
  "SV_FEAR",
  "SV_BREATH",
  "SV_SPELL",
  "FIRE_PROT",                  /* * 25 */
  "AGI",
  "POW",
  "CHA",
  "KARMA",
  "LUCK",                       /* * 30 */
  "STR_MAX",
  "DEX_MAX",
  "INT_MAX",
  "WIS_MAX",
  "CON_MAX",                    /* * 35 */
  "AGI_MAX",
  "POW_MAX",
  "CHA_MAX",
  "KARMA_MAX",
  "LUCK_MAX",                   /* * 40 */
  "STR_RACE",
  "DEX_RACE",
  "INT_RACE",
  "WIS_RACE",
  "CON_RACE",                   /* * 45 */
  "AGI_RACE",
  "POW_RACE",
  "CHA_RACE",
  "KARMA_RACE",
  "LUCK_RACE",                  /* * 50 */
  "CURSE",
  "SKILL_GRANT",
  "SKILL_ADD",
  "HIT_REG",
  "MOVE_REG",
  "MANA_REG",
  "SPELL_PULSE",
  "COMBAT_PULSE",
  "\n"
};

const struct class_names class_names_table[] = {
  {"None", "Unknown Class", "---", '-'},
  {"Warrior", "&+BWarrior&n", "War", 'w'},
  {"Ranger", "&+GRanger&n", "Ran", 'r'},
  {"Psionicist", "&+bPsionicist&n", "Psi", 'p'},
  {"Paladin", "&+WPaladin&n", "Pal", 'l'},
  {"Anti-Paladin", "&+LAnti-Paladin&n", "A-P", 'i'},
  {"Cleric", "&+cCleric&n", "Cle", 'c'},
  {"Monk", "&+LM&Non&+Lk&n", "Mon", 'k'},
  {"Druid", "&+gDruid&n", "Dru", 'd'},
  {"Shaman", "&+CShaman&n", "Sha", 'h'},
  {"Sorcerer", "&+MSorcerer&n", "Sor", 's'},
  {"Necromancer", "&+mNecromancer&n", "Nec", 'n'},
  {"Conjurer", "&+YConjurer&n", "Con", 'j'},
  {"Rogue", "&+rRogue&n", "Rog", 't'},
  {"Assassin", "&+rAssassin&n", "Ass", 'a'},
  {"Mercenary", "&+yMercenary&n", "Mer", 'm'},
  {"Bard", "&+LB&N&+bar&N&+Ld&n", "Bar", 'b'},
  {"Thief", "&+LThief&n", "Thf", 't'},
  {"Warlock", "&+BWar&+Llock&n", "Wlk", 'o'},
  {"MindFlayer", "&+MMindFlayer&n", "Mfl", 'f'},
  {"Alchemist", "&+CAlc&+chem&+Cist&n", "Alc", 'q'},
  {"Berserker", "&+rBeR&+RSeR&n&+rKeR&n", "Ber", 'u'},
  {"Reaver", "&+LRe&+Wav&+Ler&n", "Rev", 'v'},
  {"Illusionist", "&+WIl&+Clu&+csi&+Con&+Wist&n", "Ilu", 'y'},
  {"Unholy Piper", "&+GUnholy Piper&n", "Pip", 'y'},
  {"Dreadlord", "&+LDread&+rlord&n", "Dre", 'e'},
  {"Ethermancer", "&+wEthermancer&n", "Eth", 'g'},
  {"Avenger", "&+WAvenger&n", "Ave", '2'},
  {"Theurgist", "&+cTh&+Ceur&+Wgist&n", "The", '1'},
  {0}
};

flagDef  action_bits[] = {
  {"SPEC", "Special proc", 1, 0},
  {"SENTINEL", "Sentinel", 1, 0},
  {"SCAVENGER", "Scavenger", 1, 0},
  {"ISNPC", "Is NPC", 0, 1},
  {"NICE_THIEF", "Nice thief", 1, 0},
  {"BREATHES_FIRE", "Breathes fire", 1, 0},
  {"STAY_ZONE", "Stays in zone", 1, 0},
  {"WIMPY", "Wimpy", 1, 0},
  {"BREATHES_LIGHTNING", "Breathes lightning", 1, 0},
  {"BREATHES_FROST", "Breathes frost", 1, 0},
  {"BREATHES_ACID", "Breathes acid", 1, 0},
  {"MEMORY", "Memory", 1, 0},
  {"NO_PARALYZE", "Can't be paralyzed", 1, 0},
  {"NO_SUMMON", "Can't be summoned", 1, 0},
  {"NO_BASH", "Can't be bashed", 1, 0},
  {"TEACHER", "Teacher", 1, 0},
  {"IGNORE_MOB", "Ignore mob", 1, 0},
  {"CANFLY", "Can fly", 1, 0},
  {"CANSWIM", "Can swim", 1, 0},
  {"BREATHES_GAS", "Breathes gas", 1, 0},
  {"BREATHES_SHADOW", "Breathes shadows", 1, 0},
  {"BREATHES_BLIND", "Breathes blinding gas", 1, 0},
  {"GUILD_GOLEM", "Guild golem", 1, 0},
  {"SPEC_DIE", "Special death proc", 1, 0},
  {"ELITE", "Elite type mob", 1, 0},
  {"BREAK_CHARM", "Breaks charm", 1, 0},
  {"PROTECTOR", "Protector", 1, 0},
  {"MOUNT", "Mount", 1, 0},
  {"WILDMAGE", "Wildmagic", 1, 0},
  {"PATROL", "Map Patrol", 1, 0},
  {"HUNTER", "Hunter", 1, 0},
  {"SPEC_TEACHER", "Specialization teacher", 1, 0},
  {0}
};

flagDef  aggro_bits[] = {
  {"AGGR_ALL", "Aggr to all", 1, 0},
  {"AGGR_DAY_ONLY", ".. by day only", 1, 0},
  {"AGGR_NIGHT_ONLY", ".. by night only", 1, 0},
  {"AGGR_GOOD_ALIGN", ".. to good align", 1, 0},
  {"AGGR_NEUTRAL_ALIGN", ".. to neut align", 1, 0},
  {"AGGR_EVIL_ALIGN", ".. to evil align", 1, 0},
  {"AGGR_GOOD_RACE", ".. to good races", 1, 0},
  {"AGGR_EVIL_RACE", ".. to evil races", 1, 0},
  {"AGGR_UNDEAD_RACE", ".. to undead races", 1, 0},
  {"AGGR_OUTCASTS", ".. to outcasts", 1, 0},
  {"AGGR_FOLLOWERS", ".. to all followers", 1, 0},
  {"AGGR_UNDEAD", ".. to undead fol", 1, 0},
  {"AGGR_ELEMENTALS", ".. to elemental fol", 1, 0},
  {"AGGR_DRACOLICH", ".. to dracolich fol", 1, 0},
  {"AGGR_HUMAN", ".. to humans", 1, 0},
  {"AGGR_BARBARIAN", ".. to barbarians", 1, 0},
  {"AGGR_DROW_ELF", ".. to drow elves", 1, 0},
  {"AGGR_GREY_ELF", ".. to grey elves", 1, 0},
  {"AGGR_MOUNT_DWARF", ".. to mount dwarves", 1, 0},
  {"AGGR_DEURGAR", ".. to duergar", 1, 0},
  {"AGGR_HALFLING", ".. to halflings", 1, 0},
  {"AGGR_GNOME", ".. to gnomes", 1, 0},
  {"AGGR_OGRE", ".. to ogres", 1, 0},
  {"AGGR_TROLL", ".. to trolls", 1, 0},
  {"AGGR_HALF_ELF", ".. to half-elves", 1, 0},
  {"AGGR_ILLITHID", ".. to illithids", 1, 0},
  {"AGGR_ORC", ".. to orcs", 1, 0},
  {"AGGR_THRIKREEN", ".. to thrikreen", 1, 0},
  {"AGGR_CENTAUR", ".. to centaurs", 1, 0},
  {"AGGR_GITHYANKI", ".. to githyanki", 1, 0},
  {"AGGR_MINOTAUR", ".. to minotaurs", 1, 0},
  {"AGGR_GOBLIN", ".. to goblins", 1, 0},
  {0}
};

flagDef  aggro2_bits[] = {
  {"AGGR2_PLICH", "Aggr to liches", 1, 0},
  {"AGGR2_PVAMPIRE", ".. to vampires", 1, 0},
  {"AGGR2_PDKNIGHT", ".. to death knights", 1, 0},
  {"AGGR2_PSBEAST", ".. to shadow beasts", 1, 0},
  {"AGGR2_WARRIOR", ".. to warriors", 1, 0},
  {"AGGR2_RANGER", ".. to rangers", 1, 0},
  {"AGGR2_PSIONICIST", ".. to psionicists", 1, 0},
  {"AGGR2_PALADIN", ".. to paladins", 1, 0},
  {"AGGR2_ANTIPALADIN", ".. to anti-paladins", 1, 0},
  {"AGGR2_CLERIC", ".. to clerics", 1, 0},
  {"AGGR2_MONK", ".. to monks", 1, 0},
  {"AGGR2_DRUID", ".. to druids", 1, 0},
  {"AGGR2_SHAMAN", ".. to shamans", 1, 0},
  {"AGGR2_SORCERER", ".. to sorcerers", 1, 0},
  {"AGGR2_NECROMANCER", ".. to necromancers", 1, 0},
  {"AGGR2_CONJURER", ".. to conjurers", 1, 0},
  {"AGGR2_ROGUE", ".. to rogues", 1, 0},
  {"AGGR2_ASSASSIN", ".. to assassins", 1, 0},
  {"AGGR2_MERCENARY", ".. to mercenaries", 1, 0},
  {"AGGR2_BARD", ".. to bards", 1, 0},
  {"AGGR2_THIEF", ".. to thieves", 1, 0},
  {"AGGR2_WARLOCK", ".. to warlocks", 1, 0},
  {"AGGR2_MINDFLAYER", ".. to mindflayers", 1, 0},
  {"AGGR2_MALES", ".. to males", 1, 0},
  {"AGGR2_FEMALES", ".. to females", 1, 0},
  {"AGGR2_SGIANT", ".. to storm giants", 1, 0},
  {"AGGR2_WIGHT", ".. to wights", 1, 0},
  {"AGGR2_PHANTOM", ".. to phantoms", 1, 0},
  {"AGGR2_SHADE", ".. to shades", 1, 0},
  {"AGGR2_REVENANT", ".. to revenants", 1, 0},
  {"AGGR2_GITHZERAI", ".. to githzerais", 1, 0},
  {"AGGR2_THEURGIST", ".. to theurgists", 1, 0},
  {0}
};

flagDef aggro3_bits[] = {
  {"AGGR3_OROG", ".. to orogs", 1, 0},
  {"AGGR3_DRIDER", ".. to driders", 1, 0},
  {"AGGR3_KOBOLD", ".. to kobolds", 1, 0},
  {"AGGR3_KUOTOA", ".. to kuo toas", 1, 0},
  {"AGGR3_WOODELF", ".. to wood elves", 1, 0},
  {"AGGR3_FIRBOLG", ".. to firbolgs", 1, 0},
  {"AGGR3_AGATHINON", ".. to agathinons", 1, 0},
  {"AGGR3_ELADRIN", ".. to eladrins", 1, 0},
  {"AGGR3_PILLITHID", ".. to planetbound illithids", 1, 0},
  {"AGGR3_ALCHEMIST", ".. to alchemists", 1, 0},
  {"AGGR3_BERSeRKER", ".. to berserkers", 1, 0},
  {"AGGR3_REAVER", ".. to reavers", 1, 0},
  {"AGGR3_ILLUSIONIST", ".. to illusionists", 1, 0},
  {"AGGR3_ETHERMANCER", ".. to ethermancers", 1, 0},
  {"AGGR3_DREADLORD", ".. to dreadlords", 1, 0},
  {"AGGR3_AVENGER", ".. to avengers", 1, 0},
  {0}
};

struct material_data materials[NUMB_MATERIALS] = {
  // phys , fire , cold , light, gas  , acid , neg  , holy ,  psi , spirit
  {"&=RLundefined&n"},
  {"&+La non-substantial material&n"},
  {"&+rflesh&n"},
  {"cloth"},
  {"&+ybark&n"},
  {"&+ysoft wood&n"},
  {"&+yhard wood&n"},
  {"&+Wglass&n"},
  {"&+gcrystal&n"},
  {"&+yclay&n"},
  {"&+Wbone&n"},
  {"&+Lstone&n"},
  {"&+yhide&n"},
  {"&+yleather&n"},
  {"&+ycured leather&n"},
  {"&+ciron&n"},
  {"&+Csteel&n"},
  {"&+ybrass&n"},
  {"&+mmithril&n"},
  {"&+Madamantium&n"},
  {"&+ybronze&n"},
  {"&+ycopper&n"},
  {"&+csilver&n"},
  {"&+Celectrum&n"},
  {"&+Ygold&n"},
  {"&+Wplatinum&n"},
  {"&+ggem&n"},
  {"&+Wdiamond&n"},
  {"&+Wpaper&n"},
  {"&+yparchment&n"},
  {"&+gleaves&n"},
  {"&+rruby&n"},
  {"&+gemerald&n"},
  {"&+bsapphire&n"},
  {"&+Wivory&n"},
  {"&+gdragonscale&n"},
  {"&+Lobsidian&n"},
  {"&+Lgranite&n"},
  {"&+Wmarble&n"},
  {"&+glimestone&n"},
  {"&+cliquid&n"},
  {"&+ybamboo&n"},
  {"&+greeds&n"},
  {"&+ghemp&n"},
  {"&+cglassteel&n"},
  {"&+Weggshell&n"},
  {"&+ychitin&n"},
  {"&+greptile scale&n"},
  {"&+Ygeneric food&n"},
  {"&+Lrubber&n"},
  {"&+Wfeather&n"},
  {"&+Wwax&n"},
  {"&+Wpearl&n"}
};
