/**************************************************************************
 *  file: spells.h , Implementation of magic spells.                       *
 *  Usage : Spells                                                         *
 ************************************************************************* */

#ifndef _SOJ_SPELLS_H_
#define _SOJ_SPELLS_H_

#define GET_SPELLTYPE(spell_id) (skills[(spell_id)].type)

#define SPELLTYPE_FIRE                1
#define SPELLTYPE_COLD                2
#define SPELLTYPE_ELECTRIC            3
#define SPELLTYPE_ACID                4
#define SPELLTYPE_BLOW                5
#define SPELLTYPE_GENERIC             6         /* Defined for use in        */
#define SPELLTYPE_HEALING             7         /* classifying spell types.  */
#define SPELLTYPE_PROTECTION          8         /* SKB - 3 Mar 1995          */
#define SPELLTYPE_ENCHANTMENT         9
#define SPELLTYPE_DIVINATION         10
#define SPELLTYPE_TELEPORTATION      11
#define SPELLTYPE_SUMMONING          12
#define SPELLTYPE_ANIMAL             13
#define SPELLTYPE_ELEMENTAL          14
#define SPELLTYPE_SPIRIT             15
#define SPELLTYPE_PSIONIC            16
#define NUMB_SPELLTYPES		     16

#define TYPE_UNDEFINED               -1
#define SPELL_RESERVED_DBC            0 /* SKILL NUMBER ZERO */
#define SPELL_ARMOR                   1
#define SPELL_TELEPORT                2
#define SPELL_BLESS                   3
#define SPELL_BLINDNESS               4
#define SPELL_BURNING_HANDS           5
#define SPELL_CALL_LIGHTNING          6
#define SPELL_CHARM_PERSON            7
#define SPELL_CHILL_TOUCH             8
#define SPELL_FULL_HEAL               9
#define SPELL_CONE_OF_COLD           10
#define SPELL_CONTROL_WEATHER        11
#define SPELL_CREATE_FOOD            12
#define SPELL_CREATE_WATER           13
#define SPELL_CURE_BLIND             14
#define SPELL_CURE_CRITIC            15
#define SPELL_CURE_LIGHT             16
#define SPELL_CURSE                  17
#define SPELL_CONTINUAL_LIGHT        18
#define SPELL_DETECT_INVISIBLE       19
#define SPELL_MINOR_CREATION         20
#define SPELL_FLAMESTRIKE            21
#define SPELL_DISPEL_EVIL            22
#define SPELL_EARTHQUAKE             23
#define SPELL_ENCHANT_WEAPON         24
#define SPELL_ENERGY_DRAIN           25
#define SPELL_FIREBALL               26
#define SPELL_HARM                   27
#define SPELL_HEAL                   28
#define SPELL_INVISIBLE              29
#define SPELL_LIGHTNING_BOLT         30
#define SPELL_LOCATE_OBJECT          31
#define SPELL_MAGIC_MISSILE          32
#define SPELL_POISON                 33
#define SPELL_PROTECT_FROM_EVIL      34
#define SPELL_REMOVE_CURSE           35
#define SPELL_STONE_SKIN             36
#define SPELL_SHOCKING_GRASP         37
#define SPELL_SLEEP                  38
#define SPELL_STRENGTH               39
#define SPELL_SUMMON                 40
#define SPELL_HASTE                  41
#define SPELL_WORD_OF_RECALL         42
#define SPELL_REMOVE_POISON          43
#define SPELL_SENSE_LIFE             44
#define SPELL_IDENTIFY               45
#define SPELL_VENTRILOQUATE          46
#define SPELL_FIRESTORM              47
#define SPELL_FIRE_BREATH            48
#define SPELL_GAS_BREATH             49
#define SPELL_FROST_BREATH           50
#define SPELL_ACID_BREATH            51
#define SPELL_LIGHTNING_BREATH       52
#define SPELL_FARSEE                 53
#define SPELL_FEAR                   54
#define SPELL_RECHARGER              55
#define SPELL_VITALITY               56
#define SPELL_CURE_SERIOUS           57
#define SPELL_DESTROY_UNDEAD         58
#define SPELL_METEOR_SWARM           59
#define SPELL_CREEPING               60
#define SPELL_MINOR_GLOBE            61
#define SPELL_CHAIN_LIGHTNING        62
#define SPELL_DIMENSION_DOOR         63
#define SPELL_VIGORIZE_LIGHT         64
#define SPELL_VIGORIZE_SERIOUS       65
#define SPELL_VIGORIZE_CRITIC        66
#define SPELL_DISPEL_INVISIBLE       67
#define SPELL_WIZARD_EYE             68
#define SPELL_CLAIRVOYANCE           69
#define SPELL_REJUVENATE_MAJOR       70
#define SPELL_RAY_OF_ENFEEBLEMENT    71
#define SPELL_DISPEL_GOOD            72
#define SPELL_DEXTERITY              73
#define SPELL_REJUVENATE_MINOR       74
#define SPELL_AGE                    75
#define SPELL_CYCLONE                76
#define SPELL_BIGBYS_CLENCHED_FIST   77
#define SPELL_CONJURE_ELEMENTAL      78
#define SPELL_VITALIZE_MANA          79
#define SPELL_RELOCATE               80
#define SPELL_PROTECT_FROM_GOOD      81
#define SPELL_ANIMATE_DEAD           82
#define SPELL_LEVITATE               83
#define SPELL_FLY                    84
#define SPELL_WATERBREATH            85
#define SPELL_PLANE_SHIFT            86
#define SPELL_GATE                   87
#define SPELL_RESURRECT              88
#define SPELL_MASS_CHARM             89
#define SPELL_DETECT_EVIL            90
#define SPELL_DETECT_GOOD            91
#define SPELL_DETECT_MAGIC           92
#define SPELL_DISPEL_MAGIC           93
#define SPELL_PRESERVE               94
#define SPELL_MASS_INVIS             95
#define SPELL_PROTECT_FROM_FIRE      96
#define SPELL_PROTECT_FROM_COLD      97
#define SPELL_PROTECT_FROM_LIGHTNING 98
#define SPELL_DARKNESS               99
#define SPELL_MINOR_PARALYSIS        100
#define SPELL_MAJOR_PARALYSIS        101
#define SPELL_SLOW                   102
#define SPELL_WITHER                 103
#define SPELL_PROTECT_FROM_GAS       104
#define SPELL_PROTECT_FROM_ACID      105
#define SPELL_INFRAVISION            106
#define SPELL_PRISMATIC_SPRAY        107
#define SPELL_FIRESHIELD             108
#define SPELL_COLOR_SPRAY            109
#define SPELL_INCENDIARY_CLOUD       110
#define SPELL_ICE_STORM              111
#define SPELL_DISINTEGRATE           112
#define SPELL_CAUSE_LIGHT            113
#define SPELL_CAUSE_SERIOUS          114
#define SPELL_CAUSE_CRITICAL         115
#define SPELL_ACID_BLAST             116
#define SPELL_FAERIE_FIRE            117
#define SPELL_FAERIE_FOG             118
#define SPELL_PWORD_KILL             119
#define SPELL_PWORD_BLIND            120
#define SPELL_PWORD_STUN             121
#define SPELL_UNHOLY_WORD            122
#define SPELL_HOLY_WORD              123
#define SPELL_SUNRAY                 124
#define SPELL_FEEBLEMIND             126
#define SPELL_SILENCE                127
#define SPELL_TURN_UNDEAD            128
#define SPELL_COMMAND_UNDEAD         129
#define SPELL_SLOW_POISON            130
#define SPELL_COLDSHIELD             131
#define SPELL_COMPREHEND_LANGUAGES   132
#define SPELL_WRAITHFORM             133
#define SPELL_VAMPIRIC_TOUCH         134
#define SPELL_PROT_UNDEAD            135
#define SPELL_PROT_FROM_UNDEAD       136
#define SPELL_COMMAND_HORDE          137
#define SPELL_HEAL_UNDEAD            138
#define SPELL_ENTANGLE               139
#define SPELL_CREATE_SPRING          140
#define SPELL_BARKSKIN               141
#define SPELL_MOONWELL               142
#define SPELL_CREATE_DRACOLICH       143
#define SPELL_GLOBE                  144
#define SPELL_EMBALM                 145
#define SPELL_SHADOW_BREATH_1        146
#define SPELL_SHADOW_BREATH_2        147
#define SPELL_WALL_OF_FLAMES         148
#define SPELL_WALL_OF_ICE            149
#define SPELL_WALL_OF_STONE          150
#define SPELL_WALL_OF_IRON           151
#define SPELL_WALL_OF_FORCE          152
#define SPELL_WALL_OF_BONES          153
#define SPELL_LIGHTNING_CURTAIN      154
#define SPELL_MOLECULAR_CONTROL      155
#define SPELL_MOLECULAR_AGITATION    156
#define SPELL_ADRENALINE_CONTROL     157
#define SPELL_AURA_SIGHT             158
#define SPELL_AWE                    159
#define SPELL_BALLISTIC_ATTACK       160
#define SPELL_BIOFEEDBACK            161
#define SPELL_CELL_ADJUSTMENT        162
#define SPELL_COMBAT_MIND            163
//#define SPELL_CONTROL_FLAMES         164
#define SPELL_EGO_BLAST              164
#define SPELL_CREATE_SOUND           165
#define SPELL_DEATH_FIELD            166
#define SPELL_DETONATE               167
#define SPELL_DISINTEGRATE2          168
#define SPELL_DISPLACEMENT           169
#define SPELL_DOMINATION             170
#define SPELL_ECTOPLASMIC_FORM       171
#define SPELL_EGO_WHIP               172
#define SPELL_ENERGY_CONTAINMENT     173
#define SPELL_ENHANCE_ARMOR          174
#define SPELL_ENHANCED_STR           175
#define SPELL_ENHANCED_DEX           176
#define SPELL_ENHANCED_AGI           177
#define SPELL_ENHANCED_CON           178
#define SPELL_FLESH_ARMOR            179
#define SPELL_INERTIAL_BARRIER       180
#define SPELL_INFLICT_PAIN           181
#define SPELL_INTELLECT_FORTRESS     182
#define SPELL_LEND_HEALTH            183
#define SPELL_POWERCAST_FLY          184
#define SPELL_CONFUSE                185
#define SPELL_DISEASE                186
#define SPELL_CHARM_ANIMAL           187
#define SPELL_SOULSHIELD             188
#define SPELL_INVIS_MAJOR            189
#define SPELL_MASS_HEAL              190

/* shaman spells */

#define SPELL_ICE_MISSILE            191
#define SPELL_SPIRIT_ARMOR           192
#define SPELL_WOLFSPEED              193
#define SPELL_TRANSFER_WELLNESS      194
#define SPELL_FLAMEBURST             195
#define SPELL_SCALDING_BLAST         196
#define SPELL_PYTHONSTING            197
#define SPELL_SNAILSPEED             198
#define SPELL_MOLEVISION             199
#define SPELL_PURIFY_SPIRIT          200
#define SPELL_PANTHERSPEED           201
#define SPELL_MOUSESTRENGTH          202
#define SPELL_SUMMON_BEAST           203
#define SPELL_HAWKVISION             204
#define SPELL_SCORCHING_TOUCH        205
#define SPELL_MENDING                206
#define SPELL_SOUL_DISTURBANCE       207
#define SPELL_SPIRIT_SIGHT           208
#define SPELL_BEARSTRENGTH           209
#define SPELL_SHREWTAMENESS          210
#define SPELL_SENSE_SPIRIT           211
#define SPELL_MALISON                212
#define SPELL_WELLNESS               213
#define SPELL_GREATER_MENDING        214
#define SPELL_LIONRAGE               215
#define SPELL_SPIRIT_ANGUISH         216
#define SPELL_EARTHEN_GRASP          217
#define SPELL_SUMMON_SPIRIT          218
#define SPELL_GREATER_SOUL_DISTURB   219
#define SPELL_SPIRIT_WARD            220
#define SPELL_ELEPHANTSTRENGTH       221
#define SPELL_GREATER_PYTHONSTING    222
#define SPELL_SCATHING_WIND          223
#define SPELL_REVEAL_TRUE_FORM       224
#define SPELL_GREATER_SPIRIT_SIGHT   225
#define SPELL_EARTHEN_RAIN           226
#define SPELL_GREATER_SPIRIT_WARD    227
#define SPELL_SUSTENANCE             228
#define SPELL_CREATE_EARTHEN_PROJ    229
#define SPELL_ANIMATE_EARTHEN_PROJ   230
#define SPELL_GREATER_SUST           231
#define SPELL_COLD_WARD              232
#define SPELL_FIRE_WARD              233
#define SPELL_LESSER_MENDING         234
#define SPELL_MOLTEN_SPRAY           235
#define SPELL_TRUE_SEEING            236
#define SPELL_BOGUS_TEST             237
#define SPELL_RAVENFLIGHT            238
#define SPELL_GREATER_RAVENFLIGHT    239
#define SPELL_LORE                   240
#define SPELL_WORMHOLE               241
#define SPELL_ETHERPORTAL            242
#define SPELL_FULL_HARM              243
#define SPELL_CONJURE_GREATER_ELEMENTAL 244
#define SPELL_GROUP_RECALL           245
#define SPELL_GREATER_EARTHEN_GRASP  246
#define SPELL_GROUP_STONE_SKIN       247
#define SPELL_ENLARGE                248
#define SPELL_REDUCE                 249
#define SPELL_REVEAL_SPIRIT_ESSENCE  250
#define SPELL_SPIRIT_JUMP            251
#define SPELL_BEHOLDER_DISIN         252
#define SPELL_BEHOLDER_DAMAGE        253
#define SPELL_ARIEKS_SHATTERING_ICEBALL 254
#define SPELL_ENRAGE                 255
#define SPELL_BLINDING_BREATH        256
#define SPELL_MIND_BLANK             257
#define SPELL_SIGHT_LINK             258
#define SPELL_CANIBALIZE             259
#define SPELL_TOWER_IRON_WILL        260
#define SPELL_MIRROR_IMAGE           261
#define SPELL_REVEAL_TRUE_NAME       262
#define SPELL_BLUR                   263
#define SPELL_PRISMATIC_CUBE         264
#define SPELL_JUDGEMENT              265
#define SPELL_GREATER_WRAITHFORM     266
#define SPELL_ELEMENTAL_FORM         267
#define SPELL_RAISE_SPECTRE          268
#define SPELL_RAISE_WRAITH           269
#define SPELL_RAISE_VAMPIRE          270
#define SPELL_RAISE_LICH             271
#define SPELL_PALADIN_AURA           272
#define SPELL_MINDSHIELD	     273
#define SPELL_AIRY_WATER	     274
#define SPELL_CURE_DISEASE           275
#define SPELL_POLYMORPH_OBJECT       276
#define SPELL_IMMOLATE               277
#define SPELL_APOCALYPSE	     278
#define SPELL_SENSE_FOLLOWER	     279
#define SPELL_PASS_WITHOUT_TRACE     280
#define SPELL_ETHER_WARP	     281
#define SPELL_STARSHELL              282
#define SPELL_CLOAK_OF_FEAR          283
#define SPELL_VAMPIRE                284
#define SPELL_BIGBYS_CRUSHING_HAND   285
#define SPELL_STORNOGS_SPHERES	     286
#define SPELL_STORNOGS_GREATER_SPHERES  287
#define SPELL_GROUP_GLOBE            288
#define SPELL_ETHER_SENSE            289
#define SPELL_CALL_OF_THE_WILD       290
#define SPELL_HOLY_SACRIFICE	     291
#define SPELL_BATTLE_ECSTASY	     292
#define SPELL_DAZZLE		     293
#define SPELL_REGENERATION	     294
#define SPELL_WEB		     295
#define SPELL_PLEASANTRY	     296
#define SPELL_MAGE_FLAME             297
#define SPELL_SELF_COMPREHENSION     298
#define SPELL_ENLARGE_ITEM           299
#define SPELL_REDUCE_ITEM            300
#define SPELL_DEFLECT		     301
#define SPELL_GLOBE_OF_DARKNESS      302
#define SPELL_RADIAL_NAV	     303
#define SPELL_MIRACLE                304
#define SPELL_MOONSTONE		     305
#define SPELL_COMMAND                306
#define SPELL_MASS_BARKSKIN          307
#define SPELL_PSYCHIC_CRUSH          308
#define SPELL_STORNOGS_LOWERED_RES   309
#define SPELL_DIVINE_FURY            310
#define SPELL_BARB_BREATH	     311
#define SPELL_BIGBYS_GRASPING_FIST   312
#define SPELL_CHANNEL		     313
#define SPELL_SANCTUARY		     314
#define SPELL_HELLFIRE	             315
#define SPELL_SENSE_HOLINESS         316
#define SPELL_UNHOLY_WIND            317
#define SPELL_PROTECT_FROM_LIVING    318
#define SPELL_UNMAKING               319
#define SPELL_INVOKE_NEG_ENERGY      320
#define SPELL_LIFELUST               321
#define SPELL_SOUL_LINK              322
#define SPELL_PURGE                  323
#define SPELL_DEVITALIZE             324
#define SPELL_FROSTBITE              325
#define SPELL_NETHER_TOUCH           326
#define SPELL_CHANNEL_NEG_ENERGY     327
#define SPELL_SHADOW_AURA            328
#define SPELL_NEG_ENERGY_VORTEX      329
#define SPELL_DISPEL_LIFEFORCE       330
#define SPELL_ALTER_ENERGY_POLARITY  331
#define SPELL_NETHER_GATE            332
#define SPELL_NEG_ENERGY_BARRIER     333
#define SPELL_SHADOW_GATE            334
#define SPELL_LIFE_WARD              335
#define SPELL_SHADOW_VISION          336
#define SPELL_ENTROPY_STORM          337
#define SPELL_MASS_EMBALM	     338
#define SPELL_MASS_PRESERVE	     339
#define SPELL_DARK_COMPACT	     340
#define SPELL_HANDOFDEATH	     341
#define SPELL_MENTAL_ANGUISH	     342
#define SPELL_SPINAL_CORRUPTION	     343
#define SPELL_MEMORY_BLOCK	     344
#define SPELL_PSIONIC_CLOUD	     345
#define SPELL_ETHEREAL_RIFT	     346
#define SPELL_PULCHRITUDE            347
#define SPELL_FORTITUDE	             348
#define SPELL_WANDERING_WOODS	     349
#define SPELL_FLAME_BLADE	     350
#define SPELL_SHIELD		     351
#define SPELL_SERENDIPITY	     352
#define SPELL_TRANQUILITY	     353
#define SPELL_AID		     354
#define SPELL_ENDURANCE		     355
#define SPELL_ACCEL_HEALING	     356
#define SPELL_UNHOLY_STRENGTH        357
#define SPELL_CONSECRATE_LAND	     358
#define SPELL_NOVA		     359
#define SPELL_SIREN_SONG	     360
#define SPELL_HARMONIC_RESONANCE     361
#define SPELL_ELEMENTAL_AURA         362
#define SPELL_ANTI_MAGIC_RAY	     363
#define SPELL_PRISMATIC_RAY	     364
#define SPELL_ACID_STREAM            365
#define SPELL_GASEOUS_CLOUD          366
#define SPELL_EARTHEN_MAUL           367
#define SPELL_RESTORE_ITEM           368
#define SPELL_NATURES_TOUCH          369
#define SPELL_STICKS_TO_SNAKES       370

/* SPEC SPELLS - KVARK */
#define SPELL_GROUP_HEAL             371
#define SPELL_LESSER_SANCTUARY       372
#define SPELL_AREA_RESURRECT         373
#define SPELL_RING_LIGHTNING         374
#define SPELL_NAPALM                 375
#define SPELL_STRONG_ACID            376
#define SPELL_CORPSEFORM             377
#define SPELL_NEGATIVE_CONCUSSION_BLAST 378
#define SPELL_MIND_TRAVEL            379
#define SPELL_CREATE_GREATER_DRACOLICH 380
#define SPELL_GREATER_SPIRIT_ANGUISH 381
#define SPELL_ROPE_TRICK	     382
#define SPELL_PROTECT_FROM_ANIMAL    383
#define SPELL_ANIMAL_FRIENDSHIP      384
#define SPELL_ANIMAL_VISION          385
#define SPELL_CDOOM	 	     386

/* REAVER SPELLS - Ilienze */
#define SPELL_THARKUNS_PROTECTION    387
#define SPELL_JERAS_GAZE	     388
#define SPELL_KELEMONS_PRECISION     389
#define SPELL_ILIENZES_FLAME_SWORD   390
#define SPELL_KVARKS_VITALITY	     391
#define SPELL_DAKTAS_FURY            392           
#define SPELL_FOOS_SNEAKY_WAYS	     393
/* END REAVER SPELLS  */

#define SPELL_MAGMA_BURST	     394
#define SPELL_HEALING_BLADE	     395
#define SPELL_AIR_FORM			 396
#define SPELL_WATER_TO_LIFE		 397
#define SPELL_LIVING_STONE		398
#define SPELL_EARTHEN_TOMB		399

/* ILLUSIONIST SPELLS */

#define SPELL_PHANTOM_ARMOR		400
#define SPELL_SHADOW_MONSTER		401
#define SPELL_INSECTS			402
#define SPELL_ILLUSIONARY_WALL		403
#define SPELL_BOULDER			404
#define SPELL_SHADOW_TRAVEL		405
#define SPELL_STUNNING_VISIONS		406
#define SPELL_REFLECTION		407
#define SPELL_MASK			408
#define SPELL_WATCHING_WALL		409
#define SPELL_NIGHTMARE			410
#define SPELL_SHADOW_SHIELD		411
#define SPELL_VANISH			412
#define SPELL_HAMMER			413
#define SPELL_DETECT_ILLUSION		414
#define SPELL_SHADOW_RIFT		415
#define SPELL_MAGIC_BARRIER		416
#define SPELL_CLONE_FORM		417
#define SPELL_DELIRIUM			418
#define SPELL_IMPRISON			419
#define SPELL_NONEXISTENCE	  	420
#define SPELL_TITAN			421
#define SPELL_DRAGON			422

#define SPELL_CONJURE_WATER		423
#define SPELL_DREAD_WAVE		424
#define SPELL_GREATER_LIVING_STONE		425

#define SPELL_ETHEREAL_GROUNDS		426
#define SPELL_SPAWN	427

// For Shabo Proc
#define SPELL_ACIDIMMOLATE              428
#define SPELL_FLICKER			429
#define SPELL_GREATER_FLICKER		430

#define SPELL_SOLAR_FLARE	431
#define SPELL_CHAOTIC_RIPPLE 432
#define SPELL_BLINK 433
#define SPELL_UNUSED434 434
#define SPELL_RACE_CHANGE 435
#define SPELL_BEASTFORM 436

#define SPELL_GREATER_HEAL_UNDEAD 437
#define SPELL_HEALING_SALVE  438
#define SPELL_PLAGUE  439
#define SPELL_FLARE   440
#define SPELL_PEACE   441
#define SPELL_WINDSTROM_BLESSING  442
#define SPELL_DEATH_BLESSING 443

// Druid Specs
#define SPELL_GROW  444
#define SPELL_VINES 445
#define SPELL_AWAKEN_FOREST 446
#define SPELL_REFRESHING_FOUNTAIN 	     447
#define SPELL_MAGICAL_FOUNTAIN 	     448
#define SPELL_HURRICANE 	     449
#define SPELL_STORMSHIELD      450
#define SPELL_BLOODSTONE       451

// Ethermancer Spells
#define SPELL_VAPOR_ARMOR      452
#define SPELL_WINDWALK         453
#define SPELL_WIND_BLADE       454
#define SPELL_FROST_BOLT       455
#define SPELL_GUST             456
#define SPELL_ETHEREAL_FORM      457
#define SPELL_ETHEREAL_RECHARGE 458
#define SPELL_ARCANE_WHIRLWIND 459
#define SPELL_FORKED_LIGHTNING 460
#define SPELL_PURGE_LIVING     461
#define SPELL_WAY_OF_THE_WIND  462
#define SPELL_INDUCE_TUPOR     463
#define SPELL_GUARDIAN_SPIRIT  464
#define SPELL_STORM_EMPATHY    466
#define SPELL_VAPOR_STRIKE     467
#define SPELL_FROST_BEACON     468
#define SPELL_CONJURE_AIR      469
#define SPELL_MASS_FLY         470
#define SPELL_PATH_OF_FROST    471
#define SPELL_COLD_SNAP        472
#define SPELL_FAERIE_SIGHT     473
#define SPELL_INDOMITABILITY   474
#define SPELL_TEMPEST_TERRAIN  475

// Frost Magus Ethermancer Spec
#define SPELL_TEMPEST           465
#define SPELL_WIND_RAGE         476
#define SPELL_ETHEREAL_ALLIANCE 477
#define SPELL_GREATER_ETHEREAL  478
#define SPELL_ARMAGEDDON        479

#define SPELL_ELEM_FURY            480
#define SPELL_ELEM_AFFINITY        481
#define SPELL_SPIRIT_WALK          482
#define SPELL_ESSENCE_OF_WOLF      483
#define SPELL_GREATER_SUMMON_BEAST 484

#define SPELL_CREATE_GOLEM      485
#define SPELL_RAISE_SHADOW      486

#define SPELL_SHATTER		487
#define SPELL_GROUP_TELEPORT    488
#define SPELL_CONTROL_FLAMES    489
#define SPELL_LESSER_RESURRECT  490
#define SPELL_GLASS_BOMB        491
#define SPELL_FIRE_AURA         492
#define SPELL_GREASE            493
#define SPELL_NITROGEN          494
#define SPELL_BANISH            495
#define SPELL_BLOOD_ALLIANCE    496

#define SPELL_CALL_WOODLAND     497
#define SPELL_BINDING_WIND      498
#define SPELL_WIND_TUNNEL       499
#define SPELL_NATURES_BLESSING  500
#define SPELL_SUMMON_INSECTS    501
#define SPELL_ANIMAL_GROWTH     502
#define SPELL_SEVER_LINK        503
#define SPELL_SPORE_CLOUD       504
#define SPELL_SPORE_BURST       505
#define SPELL_GROW_SPIKES       506
#define SPELL_SPIKE_GROWTH      507
#define SPELL_TREE              508
#define SPELL_TRANS_MUD_ROCK    509
#define SPELL_TRANS_ROCK_MUD    510
#define SPELL_TRANS_MUD_WATER   511
#define SPELL_TRANS_WATER_MUD   512
#define SPELL_TRANS_WATER_AIR   513
#define SPELL_TRANS_AIR_WATER   514
#define SPELL_VIRTUE            515
#define SPELL_TRANS_ROCK_LAVA   516
#define SPELL_BLOODHOUND        517
#define SPELL_DEPRESSED_EARTH   518
#define SPELL_TRANS_LAVA_ROCK   519
#define SPELL_COMET             520

#define SPELL_USEME1            521
#define SPELL_USEME2            522
#define SPELL_USEME3            523
#define SPELL_USEME4            524
#define SPELL_USEME5            525

#define SPELL_TIME_STOP         526
#define SPELL_DOOM_BLADE        527

#define SPELL_COSMIC_VACUUM		  528
#define SPELL_SUPERNOVA			    529
#define SPELL_PLANETARY_ALIGNMENT	530
#define SPELL_ETHEREAL_DISCHARGE	531

// SPEC Spells Illusionist - Deceiver
#define SPELL_OBSCURING_MIST    532
#define SPELL_SUPPRESS_SOUND    533
// SPEC Spells Illusionist - Dark Dreamer
#define SPELL_SHADOW_MERGEING   534
#define SPELL_SHADOW_SPAWN      535
#define SPELL_SHDW_GATE_ARDGRAL 536
#define SPELL_THOUGHT_BEACON    537
#define SPELL_DIVINE_BLESSING   538

#define LAST_SPELL              540 /* last number +2 */


#define FIRST_SKILL                  550  /* should be a decent split point */

#define SKILL_SNEAK                  551
#define SKILL_HIDE                   552
#define SKILL_STEAL                  553
#define SKILL_BACKSTAB               554
#define SKILL_PICK_LOCK              555
#define SKILL_KICK                   556
#define SKILL_BASH                   557
#define SKILL_RESCUE                 558
#define SKILL_DOUBLE_ATTACK          559
#define SKILL_DUAL_WIELD             560
#define SKILL_DODGE                  561
#define SKILL_HITALL                 562
#define SKILL_TRAP                   563
#define SKILL_BERSERK                564
#define SKILL_APPLY_POISON           565
#define SKILL_TRACK                  566
#define SKILL_LISTEN                 567
#define SKILL_DISARM                 568
#define SKILL_PARRY                  569
#define SKILL_SHADOW                 570
#define SKILL_INSTANT_KILL           571
#define SKILL_HEADBUTT               572
#define SKILL_MEDITATE               573
#define SKILL_SURPRISE               574
#define SKILL_AWARENESS              575
#define SKILL_MOUNT                  576
#define SKILL_FEIGN_DEATH            577
#define SKILL_QUIVERING_PALM         578
#define SKILL_FIRST_AID              579
#define SKILL_SAFE_FALL              580
#define SKILL_SWITCH_OPPONENTS       581
#define SKILL_SPRINGLEAP             582
#define SKILL_MARTIAL_ARTS           583
#define SKILL_UNARMED_DAMAGE         584
#define SKILL_BUDDHA_PALM            585
#define SKILL_HEROISM                586
#define SKILL_CHANT                  587
#define SKILL_DRAGON_PUNCH           588
#define SKILL_THROAT_CRUSH	     589
#define SKILL_CALM                   590
#define SKILL_RANGE_SPECIALIST       591
#define SKILL_ARCHERY                592
#define SKILL_RANGE_WEAPONS          593
#define SKILL_CIRCLE                 594
#define SKILL_RIPOSTE                596
#define SKILL_SUMMON_MOUNT           597
#define SKILL_BANDAGE                598
#define SKILL_SCRIBE                 599
#define SKILL_QUICK_CHANT            600
#define SKILL_SPELL_KNOWLEDGE_CLERICAL 601
#define SKILL_SPELL_KNOWLEDGE_MAGICAL  602

#define SKILL_1H_BLUDGEON            603
#define SKILL_1H_SLASHING            604
#define SKILL_1H_PIERCING            605
#define SKILL_1H_FLAYING             606
#define SKILL_2H_BLUDGEON            607
#define SKILL_2H_SLASHING            608
#define SKILL_2H_FLAYING             609

#define SKILL_BLINDFIGHTING          610
/* following are cast related skills, and really should be removed */
#define SKILL_CAST_GENERIC           611
#define SKILL_FIRST_CAST             612
#define SKILL_CAST_FIRE              SKILL_FIRST_CAST
#define SKILL_CAST_COLD              (SKILL_FIRST_CAST+1)
#define SKILL_CAST_HEALING           (SKILL_FIRST_CAST+2)
#define SKILL_CAST_TELEPORTATION     (SKILL_FIRST_CAST+3)
#define SKILL_CAST_SUMMONING         (SKILL_FIRST_CAST+4)
#define SKILL_CAST_PROTECTION        (SKILL_FIRST_CAST+5)
#define SKILL_CAST_DIVINATION        (SKILL_FIRST_CAST+6)
#define SKILL_CAST_ELECTRIC          (SKILL_FIRST_CAST+7)
#define SKILL_CAST_ACID              (SKILL_FIRST_CAST+8)
#define SKILL_CAST_ENCHANT           (SKILL_FIRST_CAST+7)
#define SKILL_LAST_CAST              SKILL_CAST_ENCHANT
#define SKILL_FIRST_SPEC             622
#define SKILL_SPEC_FIRE              SKILL_FIRST_SPEC
#define SKILL_SPEC_COLD              (SKILL_FIRST_SPEC+1)
#define SKILL_SPEC_HEALING           (SKILL_FIRST_SPEC+2)
#define SKILL_SPEC_TELEPORTATION     (SKILL_FIRST_SPEC+3)
#define SKILL_SPEC_SUMMONING         (SKILL_FIRST_SPEC+4)
#define SKILL_SPEC_PROTECTION        (SKILL_FIRST_SPEC+5)
#define SKILL_SPEC_DIVINATION        (SKILL_FIRST_SPEC+6)
#define SKILL_SPEC_ENCHANT           (SKILL_FIRST_SPEC+7)
#define SKILL_LAST_SPEC              SKILL_SPEC_ENCHANT
/* Bard related. Diff names, but still skills */
#define SONG_FIRST                   629
#define SONG_MINDSHIELD		     SONG_FIRST
#define SONG_CHARMING                (SONG_FIRST+1)
#define SONG_SLEEP                   (SONG_FIRST+2)
#define SONG_CALMING                 (SONG_FIRST+3)
#define SONG_HEALING                 (SONG_FIRST+4)
#define SONG_REVELATION              (SONG_FIRST+5)
#define SONG_HARMING                 (SONG_FIRST+6)
#define SONG_FLIGHT                  (SONG_FIRST+7)
#define SONG_PROTECTION              (SONG_FIRST+8)
#define SONG_HEROISM                 (SONG_FIRST+9)
#define SONG_COWARDICE               (SONG_FIRST+10)
#define SONG_FORGETFULNESS           (SONG_FIRST+11)
#define SONG_PEACE                   (SONG_FIRST+12)
#define SONG_CHAOS		     (SONG_FIRST+13)
#define SONG_DRAGONS		     (SONG_FIRST+14)
#define SONG_STORMS		     (SONG_FIRST+15)
#define SONG_DISCORD		     (SONG_FIRST+16)
#define SONG_HARMONY		     (SONG_FIRST+17)
#define SONG_LAST                    SONG_HARMONY
/*feel free to rename and use these undefs*/
/*they were put in to fix the*/
#define SKILL_DEFEND                 647 /*fubared bard stuff */
#define SKILL_BEARHUG                648
#define SKILL_OGRE_ROAR              649
#define SKILL_CARVE                  650
#define SKILL_SUBTERFUGE             651
#define SKILL_TRIP                   652
#define SKILL_DIRTTOSS               653
#define SKILL_DISGUISE               654
#define SKILL_SPELL_KNOWLEDGE_SHAMAN 655
#define SKILL_CAST_SH_ANIMAL         656
#define SKILL_CAST_SH_ELEMENT        657
#define SKILL_CAST_SH_SPIRIT         658
#define SKILL_CAPTURE                659
#define SKILL_TRIPLE_ATTACK          660
#define SKILL_APPRAISE               661
#define SKILL_LORE                   662
#define SKILL_SWIM                   663
#define SKILL_AXE                    664
#define SKILL_DAGGER                 665
#define SKILL_FLAIL                  666
#define SKILL_HAMMER                 667
#define SKILL_LONGSWORD              668
#define SKILL_MACE                   669
#define SKILL_POLEARM                670
#define SKILL_SHORTSWORD             671
#define SKILL_CLUB                   672
#define SKILL_2HANDSWORD             673
#define SKILL_WHIP                   674
#define SKILL_PARRY_AXE              675
#define SKILL_PARRY_DAGGER           676
#define SKILL_PARRY_FLAIL            677
#define SKILL_PARRY_HAMMER           678
#define SKILL_PARRY_LONGSWORD        679
#define SKILL_PARRY_MACE             680
#define SKILL_PARRY_POLEARM          681
#define SKILL_PARRY_SHORTSWORD       682
#define SKILL_PARRY_CLUB             683
#define SKILL_PARRY_2HANDSWORD       684
#define SKILL_PARRY_WHIP             685
#define SKILL_SHIELD                 686
#define SKILL_TWOHANDED_SWORD        687
#define SKILL_STAFF                  688
#define SKILL_PICK                   689
#define SKILL_LANCE		     690
#define SKILL_SICKLE		     691
#define SKILL_FORK		     692
#define SKILL_HORN		     693
#define SKILL_NUMCHUCKS		     694
#define SKILL_BAREHANDED_FIGHTING    695
#define SKILL_GRAPPLE		     696
#define SKILL_MOUNTED_COMBAT	     697
#define SKILL_CLIMB		     698
#define SKILL_ROUNDKICK 	     699
#define SKILL_REGENERATE 	     700
#define SKILL_AERIAL_COMBAT          701
#define SKILL_AERIAL_CASTING         702
#define SKILL_TOUCH_DEATH            703
#define SKILL_HAMSTRING              704
#define SKILL_BODYSLAM               705
#define SKILL_SHIELD_BLOCK	     706
#define SKILL_COMBINATION	     707
#define SKILL_GUARD	             708
#define SKILL_SHIELDLESS_BASH	     709
#define FIRST_INSTRUMENT             710
#define INSTRUMENT_FLUTE             710
#define INSTRUMENT_LYRE              711
#define INSTRUMENT_MANDOLIN          712
#define INSTRUMENT_HARP              713
#define INSTRUMENT_DRUMS             714
#define INSTRUMENT_HORN              715
#define LAST_INSTRUMENT              715
#define SKILL_AGE_CORPSE             716
#define SKILL_QUADRUPLE_ATTACK	     717
#define SKILL_CRITICAL_ATTACK	     718
#define SKILL_EVADE                  719
#define SKILL_VICIOUS_ATTACK         720
#define SKILL_SPINAL_TAP	     721
#define SKILL_WAR_CRY    	     722
#define SKILL_TACKLE		     723
#define SKILL_CONTROL_FLEE           724
#define SKILL_CRITICAL_STAB	     725
#define SKILL_CRAFT                  726
#define SKILL_MIX	             727
#define SKILL_FORGE	             728
#define SKILL_THROW_POTIONS          729
#define SKILL_RAGE		     730
#define SKILL_MAUL		     731
#define SKILL_RAMPAGE                732
#define SKILL_LOTUS                  733
#define SKILL_CHI                    734
#define SKILL_TRUE_STRIKE            735
#define SKILL_RECONSTRUCTION         736
#define SKILL_DISPLACEMENT           737
#define SKILL_SIGHT                  738
#define SKILL_SHIELDPUNCH	     739
#define SKILL_SWEEPING_THRUST	     740
#define SKILL_ENRAGE		     741
#define SKILL_ENCRUST		     742
#define SKILL_FOLLOWUP_RIPOSTE	     743
#define SKILL_FIX		     744
#define SKILL_SKEWER		745
#define SKILL_LANCE_CHARGE  746
#define SKILL_SIDESTEP		747
/* Spectral Piper */
#define PIPER_FIRST                  748
#define PIPER_MINDSHIELD  	      PIPER_FIRST
#define PIPER_SUBVERSION             (PIPER_FIRST+1)
#define PIPER_ELEGY_NIGHTMARES       (PIPER_FIRST+2)
#define PIPER_FUNEREAL               (PIPER_FIRST+3)
#define PIPER_UNHOLY                 (PIPER_FIRST+4)
#define PIPER_MORBID_VISIONS         (PIPER_FIRST+5)
#define PIPER_DECAY                  (PIPER_FIRST+6)
#define PIPER_GHOSTS                 (PIPER_FIRST+7)
#define PIPER_DIRGE_BONES            (PIPER_FIRST+8)
#define PIPER_STANZA_FURY            (PIPER_FIRST+9)
#define PIPER_TERROR_RHYTHMS         (PIPER_FIRST+10)
#define PIPER_HYMN_ZOMBIE            (PIPER_FIRST+11)
#define PIPER_REQUIEM_CRYP           (PIPER_FIRST+12)
#define PIPER_NIGHT		     (PIPER_FIRST+13)
#define PIPER_DRACONIC_CRESCENDO     (PIPER_FIRST+14)
#define PIPER_CHIME_VAMPIRE          (PIPER_FIRST+15)
#define PIPER_REBUKE		     (PIPER_FIRST+16)
#define PIPER_DREAD		     (PIPER_FIRST+17)
#define PIPER_LAST                    PIPER_DREAD

#define SKILL_ARCANE_RIPOSTE		766
#define SKILL_ARCANE_BLOCK		767
#define SKILL_DOUBLE_STRIKE		768
#define SKILL_WHIRLWIND		 	769
#define SKILL_CHARGE      	     770
#define SKILL_DARTS			771
#define SKILL_REMIX   		     772
#define SKILL_ENCHANT  		     773
#define SKILL_VICIOUS_STRIKE         774
#define SKILL_RUSH                   775
#define SKILL_FLANK                  776
#define SKILL_GAZE                   777
#define SKILL_TAINTED_BLADE          778
#define SKILL_BATTLE_SENSES          779
#define SKILL_BLOOD_SCENT            780
#define SKILL_BATTLE_ORDERS	         782
#define SKILL_CALL_GRAVE             783
#define SKILL_DISRUPTIVE_BLOW	     784
#define SKILL_CRIPPLING_STRIKE	     785
#define SKILL_REACH_WEAPONS          786
#define SKILL_AMBUSH	             787
#define SKILL_QUICK_STEP             788
#define SKILL_SNEAKY_STRIKE          789
#define SKILL_MANGLE                 790
#define SKILL_BOILING_BLOOD          791
#define SKILL_EXHUME                 793
#define SKILL_HOLY_BLADE             794
#define SKILL_MUG                    796
#define SKILL_FADE                   797
#define SKILL_SHADOW_MOVEMENT        798
#define SKILL_SHRIEK		         799
#define SKILL_LEGEND_LORE            800
#define SONG_DRIFTING                801
#define SKILL_DISPERSE_FLAMES        802
#define SKILL_FLAME_MASTERY          803
#define SKILL_SOUL_TRAP              804
#define SKILL_MINE                   805
#define SKILL_FLURRY_OF_BLOWS	     806
#define SKILL_FIST_OF_DRAGON	     807
#define SKILL_FISHING                808
#define SKILL_HEALING_MASTERY        809
#define SKILL_DOUBLE_HEADBUTT        810
#define SKILL_SPELLBIND              811
#define SKILL_RETREAT				 812
#define SKILL_EXPEDITED_RETREAT		 813
#define SKILL_CHANT_MASTERY          814
#define SKILL_SPELL_MASTERY          815
#define SKILL_ANATOMY                816
#define SKILL_SUMMON_BLIZZARD        817
#define SKILL_SUMMON_FAMILIAR        818
#define SKILL_ADVANCED_MEDITATION    819
#define SKILL_SMELT	                 820

#define LAST_SKILL                   822   // skills + 1



#define TOTAL_SKILLS                 ((LAST_SKILL - FIRST_SKILL) + 1)
/* Not skills, don't bother listing them. Its simply easiest to handle these
   via the skill system. Also, lets number them a jump away */
#define SKILL_CAMP                    901
#define SKILL_PERMINVIS               902

/* everything below does now make part of players skill data */

#define TAG_OBJ_DECAY                1001
#define TAG_ALTERED_EXTRA2           1002
#define TAG_PHANTASMAL_FORM          1003
#define TAG_ETHEREAL_FORM            1004
#define TAG_MEMORIZE                 1005
#define TAG_PALADIN_VIT              1006
#define TAG_NOMISFIRE                1007
#define TAG_WITCHSPELL               1008
#define TAG_VAMPIRE_BITE             1009
#define TAG_EMBRACE_DEATH            1010
#define TAG_INNATE_TIMER             1011
#define TAG_SET_MASTER               1012
#define TAG_IMMOLATE                 1013
#define TAG_DECREPIFY		     1014
#define TAG_HATRED		     1015
#define TAG_PRESSURE_POINTS	     1016
#define TAG_EATING                   1017
#define TAG_RECENT_FRAG              1018
#define TAG_KNOWN_SHAPE              1019
#define TAG_EPIC_SKILLPOINTS         1020
#define TAG_EPIC_MONOLITH            1021
#define TAG_EPIC_ERRAND              1022
#define TAG_EPIC_COMPLETED           1023
#define TAG_EPIC_POINTS              1024
#define TAG_SKILL_TIMER              1025
#define TAG_WET                      1026
#define TAG_POOL                     1027
#define TAG_SETPROC                  1028
#define TAG_IMMUNE_AREA              1029
#define TYPE_TRAP                    1037

#define FIRST_POISON                 1100
#define POISON_LIFELEAK              1100
#define POISON_WEAKNESS              1101
#define POISON_NEUROTOXIN            1102
#define POISON_HEART_TOXIN           1103
#define LAST_POISON                  1103

#define DAMAGE_FALLING               1220       /* From falling to the ground */

#define SAVING_PARA   0
#define SAVING_ROD    1
#define SAVING_PETRI  2
#define SAVING_BREATH 3
#define SAVING_SPELL  4

#define TAR_IGNORE        BIT_1
#define TAR_CHAR_ROOM     BIT_2
#define TAR_CHAR_WORLD    BIT_3
#define TAR_FIGHT_SELF    BIT_4
#define TAR_FIGHT_VICT    BIT_5
#define TAR_SELF_ONLY     BIT_6     /* Only a check, use with ei. TAR_CHAR_ROOM */
#define TAR_SELF_NONO     BIT_7     /* Only a check, use with ei. TAR_CHAR_ROOM */
#define TAR_OBJ_INV       BIT_8
#define TAR_OBJ_ROOM      BIT_9
#define TAR_OBJ_WORLD     BIT_10
#define TAR_OBJ_EQUIP     BIT_11
#define TAR_CHAR_RANGE    BIT_12
#define TAR_RANGE1        BIT_13
#define TAR_RANGE2        BIT_14
#define TAR_AREA          BIT_15
#define TAR_OFFAREA       BIT_16
#define TAR_INSTACAST     BIT_17

/* Possible Targets:

   bit 0 : IGNORE TARGET
   bit 1 : PC/NPC in room
   bit 2 : PC/NPC in world
   bit 3 : Object held
   bit 4 : Object in inventory
   bit 5 : Object in room
   bit 6 : Object in world
   bit 7 : If fighting, and no argument, select tar_char as self
   bit 8 : If fighting, and no argument, select tar_char as victim (fighting)
   bit 9 : If no argument, select self, if argument check that it IS self.

*/

#define SPELL_TYPE_SPELL   0
#define SPELL_TYPE_POTION  1
#define SPELL_TYPE_WAND    2
#define SPELL_TYPE_STAFF   3
#define SPELL_TYPE_SCROLL  4

#define GOOD_AVATAR_MOB 950
#define EVIL_AVATAR_MOB 951
#define GOOD_AVATAR_OBJ 950
#define EVIL_AVATAR_OBJ 951

#endif /* _SOJ_SPELLS_H_ */
