/* stuff related to new combat system */

#ifndef _NEWCOMBAT_H_
#define _NEWCOMBAT_H_

#include "structs.h"

// structures

//   location info for body location of certain physiology type

#define MAX_DEPENDENT_LOCS        10
#define MAX_BODYLOCNAME_LEN       30

#define BODY_LOC_OVERALL_VERYLOW   0  // feet
#define BODY_LOC_OVERALL_LOW       1  // legs, lower arms (?)
#define BODY_LOC_OVERALL_MIDDLE    2  // torso, arms
#define BODY_LOC_OVERALL_HIGH      3  // neck (?)
#define BODY_LOC_OVERALL_VERYHIGH  4  // head

typedef struct _bodyLocInfo
{
  char bodyLocName[MAX_BODYLOCNAME_LEN];
  float maxHPmult;             // this * GET_MAX_HIT(ch) = hp of body loc
  int bodyLocTargettingMod;    // +/- added to to-hit roll
  char bodyLocOverall;         // top of body, middle, etc
  int randomTargetWeight;      // if char is randomly targetting, weight of loc
  int dismemberedWeight;       // weight when detached

  unsigned short dependentBodyLocs[MAX_DEPENDENT_LOCS];
  int (*bodyLocHit) (P_char, P_char, const int, const int);       // ch, victim, loc, damage done
  int (*bodyLocDestroyed) (P_char, P_char, const int, const int); // ch, victim, loc, damage done
} bodyLocInfo;

// global combat 'variables'

#define ITEM_DEFLECTION_MULT      (float)1.0
#define ITEM_ABSORBTION_MULT      (float)1.0
#define ARMOR_DEFLECTION_MULT     (float)0.65
#define ARMOR_ABSORBTION_MULT     (float)0.65

#define MAX_ITEM_DEFLECTION       (float)0.40
#define MAX_ITEM_ABSORBTION       (float)0.95
#define MAX_ARMOR_DEFLECTION      (float)0.40
#define MAX_ARMOR_ABSORBTION      (float)0.95

#define MAX_SP_ITEM_MULT          (float)1.0  // all items - note that
                                              // changing this will also
                                              // affect armor/shields
#define MAX_SP_ARMOR_MULT         (float)1.0  // armor/shield items

#define OBJ_BODYPART_VNUM           8  // used for all bodyparts

#define BODYPART_GONE_VAL       -9999

// physiology types

#define PHYS_TYPE_HUMANOID          0
#define PHYS_TYPE_FOUR_ARMED_HUMANOID 1
#define PHYS_TYPE_QUADRUPED         2
#define PHYS_TYPE_CENTAUR           3
#define PHYS_TYPE_BIRD              4
#define PHYS_TYPE_WINGED_HUMANOID   5
#define PHYS_TYPE_WINGED_QUADRUPED  6
#define PHYS_TYPE_NO_EXTREMITIES    7
#define PHYS_TYPE_INSECTOID         8
#define PHYS_TYPE_ARACHNID          9
#define PHYS_TYPE_BEHOLDER         10

#define NUMB_PHYS_TYPES            11

// body locations

// humanoid

#define BODY_LOC_LOWEST_HUMANOID    0
#define BODY_LOC_HUMANOID_HEAD               0
#define BODY_LOC_HUMANOID_LEFT_EYE           1
#define BODY_LOC_HUMANOID_RIGHT_EYE          2
#define BODY_LOC_HUMANOID_LEFT_EAR           3
#define BODY_LOC_HUMANOID_RIGHT_EAR          4
#define BODY_LOC_HUMANOID_NECK               5
#define BODY_LOC_HUMANOID_UPPER_TORSO        6
#define BODY_LOC_HUMANOID_LOWER_TORSO        7
#define BODY_LOC_HUMANOID_UPPER_LEFT_ARM     8
#define BODY_LOC_HUMANOID_LOWER_LEFT_ARM     9
#define BODY_LOC_HUMANOID_LEFT_ELBOW        10
#define BODY_LOC_HUMANOID_UPPER_RIGHT_ARM   11
#define BODY_LOC_HUMANOID_LOWER_RIGHT_ARM   12
#define BODY_LOC_HUMANOID_RIGHT_ELBOW       13
#define BODY_LOC_HUMANOID_LEFT_WRIST        14
#define BODY_LOC_HUMANOID_RIGHT_WRIST       15
#define BODY_LOC_HUMANOID_LEFT_HAND         16
#define BODY_LOC_HUMANOID_RIGHT_HAND        17
#define BODY_LOC_HUMANOID_UPPER_LEFT_LEG    18
#define BODY_LOC_HUMANOID_LOWER_LEFT_LEG    19
#define BODY_LOC_HUMANOID_UPPER_RIGHT_LEG   20
#define BODY_LOC_HUMANOID_LOWER_RIGHT_LEG   21
#define BODY_LOC_HUMANOID_LEFT_KNEE         22
#define BODY_LOC_HUMANOID_RIGHT_KNEE        23
#define BODY_LOC_HUMANOID_LEFT_FOOT         24
#define BODY_LOC_HUMANOID_RIGHT_FOOT        25
#define BODY_LOC_HUMANOID_LEFT_ANKLE        26
#define BODY_LOC_HUMANOID_RIGHT_ANKLE       27
#define BODY_LOC_HUMANOID_CHIN              28
#define BODY_LOC_HUMANOID_LEFT_SHOULDER     29
#define BODY_LOC_HUMANOID_RIGHT_SHOULDER    30
#define BODY_LOC_HIGHEST_HUMANOID  30
#define NUMB_HUMANOID_BODY_LOCS   ((BODY_LOC_HIGHEST_HUMANOID - BODY_LOC_LOWEST_HUMANOID) + 1)

// four-armed humanoid

#define BODY_LOC_LOWEST_FOUR_ARMED_HUMANOID 0
#define BODY_LOC_FOUR_ARMED_HUMANOID_HEAD               0
#define BODY_LOC_FOUR_ARMED_HUMANOID_LEFT_EYE           1
#define BODY_LOC_FOUR_ARMED_HUMANOID_RIGHT_EYE          2
#define BODY_LOC_FOUR_ARMED_HUMANOID_LEFT_EAR           3
#define BODY_LOC_FOUR_ARMED_HUMANOID_RIGHT_EAR          4
#define BODY_LOC_FOUR_ARMED_HUMANOID_NECK               5
#define BODY_LOC_FOUR_ARMED_HUMANOID_UPPER_TORSO        6
#define BODY_LOC_FOUR_ARMED_HUMANOID_LOWER_TORSO        7
#define BODY_LOC_FOUR_ARMED_HUMANOID_UPPER_LEFT_UPPER_ARM 8  // upper part of the upper left arm
#define BODY_LOC_FOUR_ARMED_HUMANOID_LOWER_LEFT_UPPER_ARM 9 // lower part of upper left arm
#define BODY_LOC_FOUR_ARMED_HUMANOID_UPPER_LEFT_ELBOW  10
#define BODY_LOC_FOUR_ARMED_HUMANOID_UPPER_RIGHT_UPPER_ARM 11  // etc ..
#define BODY_LOC_FOUR_ARMED_HUMANOID_LOWER_RIGHT_UPPER_ARM 12
#define BODY_LOC_FOUR_ARMED_HUMANOID_UPPER_RIGHT_ELBOW 13
#define BODY_LOC_FOUR_ARMED_HUMANOID_UPPER_LEFT_WRIST  14
#define BODY_LOC_FOUR_ARMED_HUMANOID_UPPER_RIGHT_WRIST 15
#define BODY_LOC_FOUR_ARMED_HUMANOID_UPPER_LEFT_HAND   16
#define BODY_LOC_FOUR_ARMED_HUMANOID_UPPER_RIGHT_HAND  17
#define BODY_LOC_FOUR_ARMED_HUMANOID_UPPER_LEFT_LEG    18
#define BODY_LOC_FOUR_ARMED_HUMANOID_LOWER_LEFT_LEG    19
#define BODY_LOC_FOUR_ARMED_HUMANOID_UPPER_RIGHT_LEG   20
#define BODY_LOC_FOUR_ARMED_HUMANOID_LOWER_RIGHT_LEG   21
#define BODY_LOC_FOUR_ARMED_HUMANOID_LEFT_KNEE         22
#define BODY_LOC_FOUR_ARMED_HUMANOID_RIGHT_KNEE        23
#define BODY_LOC_FOUR_ARMED_HUMANOID_LEFT_FOOT         24
#define BODY_LOC_FOUR_ARMED_HUMANOID_RIGHT_FOOT        25
#define BODY_LOC_FOUR_ARMED_HUMANOID_LEFT_ANKLE        26
#define BODY_LOC_FOUR_ARMED_HUMANOID_RIGHT_ANKLE       27
#define BODY_LOC_FOUR_ARMED_HUMANOID_CHIN              28
#define BODY_LOC_FOUR_ARMED_HUMANOID_UPPER_LEFT_SHOULDER 29
#define BODY_LOC_FOUR_ARMED_HUMANOID_UPPER_RIGHT_SHOULDER 30
#define BODY_LOC_FOUR_ARMED_HUMANOID_UPPER_LEFT_LOWER_ARM 31
#define BODY_LOC_FOUR_ARMED_HUMANOID_LOWER_LEFT_LOWER_ARM 32
#define BODY_LOC_FOUR_ARMED_HUMANOID_LOWER_LEFT_ELBOW  33
#define BODY_LOC_FOUR_ARMED_HUMANOID_UPPER_RIGHT_LOWER_ARM 34
#define BODY_LOC_FOUR_ARMED_HUMANOID_LOWER_RIGHT_LOWER_ARM 35
#define BODY_LOC_FOUR_ARMED_HUMANOID_LOWER_RIGHT_ELBOW 36
#define BODY_LOC_FOUR_ARMED_HUMANOID_LOWER_LEFT_WRIST  37
#define BODY_LOC_FOUR_ARMED_HUMANOID_LOWER_RIGHT_WRIST 38
#define BODY_LOC_FOUR_ARMED_HUMANOID_LOWER_LEFT_HAND   39
#define BODY_LOC_FOUR_ARMED_HUMANOID_LOWER_RIGHT_HAND  40
#define BODY_LOC_FOUR_ARMED_HUMANOID_LOWER_LEFT_SHOULDER 41
#define BODY_LOC_FOUR_ARMED_HUMANOID_LOWER_RIGHT_SHOULDER 42
#define BODY_LOC_HIGHEST_FOUR_ARMED_HUMANOID 42
#define NUMB_FOUR_ARMED_HUMANOID_BODY_LOCS   ((BODY_LOC_HIGHEST_FOUR_ARMED_HUMANOID - BODY_LOC_LOWEST_FOUR_ARMED_HUMANOID) + 1)

// quadraped

#define BODY_LOC_LOWEST_QUADRUPED   0
#define BODY_LOC_QUADRUPED_HEAD               0
#define BODY_LOC_QUADRUPED_LEFT_EYE           1
#define BODY_LOC_QUADRUPED_RIGHT_EYE          2
#define BODY_LOC_QUADRUPED_LEFT_EAR           3
#define BODY_LOC_QUADRUPED_RIGHT_EAR          4
#define BODY_LOC_QUADRUPED_NECK               5
#define BODY_LOC_QUADRUPED_FRONT_BODY         6
#define BODY_LOC_QUADRUPED_REAR_BODY          7
#define BODY_LOC_QUADRUPED_UPPER_LEFT_FRONT_LEG 8
#define BODY_LOC_QUADRUPED_LOWER_LEFT_FRONT_LEG 9
#define BODY_LOC_QUADRUPED_UPPER_RIGHT_FRONT_LEG 10
#define BODY_LOC_QUADRUPED_LOWER_RIGHT_FRONT_LEG 11
#define BODY_LOC_QUADRUPED_LEFT_FRONT_KNEE    12
#define BODY_LOC_QUADRUPED_RIGHT_FRONT_KNEE   13
#define BODY_LOC_QUADRUPED_LEFT_FRONT_HOOF    14
#define BODY_LOC_QUADRUPED_RIGHT_FRONT_HOOF   15
#define BODY_LOC_QUADRUPED_LEFT_FRONT_ANKLE   16
#define BODY_LOC_QUADRUPED_RIGHT_FRONT_ANKLE  17
#define BODY_LOC_QUADRUPED_UPPER_LEFT_REAR_LEG 18
#define BODY_LOC_QUADRUPED_LOWER_LEFT_REAR_LEG 19
#define BODY_LOC_QUADRUPED_UPPER_RIGHT_REAR_LEG 20
#define BODY_LOC_QUADRUPED_LOWER_RIGHT_REAR_LEG 21
#define BODY_LOC_QUADRUPED_LEFT_REAR_KNEE     22
#define BODY_LOC_QUADRUPED_RIGHT_REAR_KNEE    23
#define BODY_LOC_QUADRUPED_LEFT_REAR_HOOF     24
#define BODY_LOC_QUADRUPED_RIGHT_REAR_HOOF    25
#define BODY_LOC_QUADRUPED_LEFT_REAR_ANKLE    26
#define BODY_LOC_QUADRUPED_RIGHT_REAR_ANKLE   27
#define BODY_LOC_QUADRUPED_CHIN               28
#define BODY_LOC_HIGHEST_QUADRUPED  28
#define NUMB_QUADRUPED_BODY_LOCS   ((BODY_LOC_HIGHEST_QUADRUPED - BODY_LOC_LOWEST_QUADRUPED) + 1)

// centaur

#define BODY_LOC_LOWEST_CENTAUR     0
#define BODY_LOC_CENTAUR_HEAD               0
#define BODY_LOC_CENTAUR_LEFT_EYE           1
#define BODY_LOC_CENTAUR_RIGHT_EYE          2
#define BODY_LOC_CENTAUR_LEFT_EAR           3
#define BODY_LOC_CENTAUR_RIGHT_EAR          4
#define BODY_LOC_CENTAUR_NECK               5
#define BODY_LOC_CENTAUR_FRONT_HORSE_BODY   6
#define BODY_LOC_CENTAUR_REAR_HORSE_BODY    7
#define BODY_LOC_CENTAUR_UPPER_LEFT_FRONT_LEG 8
#define BODY_LOC_CENTAUR_LOWER_LEFT_FRONT_LEG 9
#define BODY_LOC_CENTAUR_UPPER_RIGHT_FRONT_LEG 10
#define BODY_LOC_CENTAUR_LOWER_RIGHT_FRONT_LEG 11
#define BODY_LOC_CENTAUR_LEFT_FRONT_KNEE    12
#define BODY_LOC_CENTAUR_RIGHT_FRONT_KNEE   13
#define BODY_LOC_CENTAUR_LEFT_FRONT_HOOF    14
#define BODY_LOC_CENTAUR_RIGHT_FRONT_HOOF   15
#define BODY_LOC_CENTAUR_LEFT_FRONT_ANKLE   16
#define BODY_LOC_CENTAUR_RIGHT_FRONT_ANKLE  17
#define BODY_LOC_CENTAUR_UPPER_LEFT_REAR_LEG 18
#define BODY_LOC_CENTAUR_LOWER_LEFT_REAR_LEG 19
#define BODY_LOC_CENTAUR_UPPER_RIGHT_REAR_LEG 20
#define BODY_LOC_CENTAUR_LOWER_RIGHT_REAR_LEG 21
#define BODY_LOC_CENTAUR_LEFT_REAR_KNEE     22
#define BODY_LOC_CENTAUR_RIGHT_REAR_KNEE    23
#define BODY_LOC_CENTAUR_LEFT_REAR_HOOF     24
#define BODY_LOC_CENTAUR_RIGHT_REAR_HOOF    25
#define BODY_LOC_CENTAUR_LEFT_REAR_ANKLE    26
#define BODY_LOC_CENTAUR_RIGHT_REAR_ANKLE   27
#define BODY_LOC_CENTAUR_CHIN               28
#define BODY_LOC_CENTAUR_UPPER_TORSO        29
#define BODY_LOC_CENTAUR_LOWER_TORSO        30
#define BODY_LOC_CENTAUR_UPPER_LEFT_ARM     31
#define BODY_LOC_CENTAUR_LOWER_LEFT_ARM     32
#define BODY_LOC_CENTAUR_LEFT_ELBOW        33
#define BODY_LOC_CENTAUR_UPPER_RIGHT_ARM   34
#define BODY_LOC_CENTAUR_LOWER_RIGHT_ARM   35
#define BODY_LOC_CENTAUR_RIGHT_ELBOW       36
#define BODY_LOC_CENTAUR_LEFT_WRIST        37
#define BODY_LOC_CENTAUR_RIGHT_WRIST       38
#define BODY_LOC_CENTAUR_LEFT_HAND         39
#define BODY_LOC_CENTAUR_RIGHT_HAND        40
#define BODY_LOC_CENTAUR_LEFT_SHOULDER     41
#define BODY_LOC_CENTAUR_RIGHT_SHOULDER    42
#define BODY_LOC_HIGHEST_CENTAUR  42
#define NUMB_CENTAUR_BODY_LOCS   ((BODY_LOC_HIGHEST_CENTAUR - BODY_LOC_LOWEST_CENTAUR) + 1)

// bird

#define BODY_LOC_LOWEST_BIRD    0
#define BODY_LOC_BIRD_HEAD               0
#define BODY_LOC_BIRD_LEFT_EYE           1
#define BODY_LOC_BIRD_RIGHT_EYE          2
#define BODY_LOC_BIRD_NECK               3
#define BODY_LOC_BIRD_BODY        4
#define BODY_LOC_BIRD_UPPER_LEFT_LEG    5
#define BODY_LOC_BIRD_LOWER_LEFT_LEG    6
#define BODY_LOC_BIRD_UPPER_RIGHT_LEG   7
#define BODY_LOC_BIRD_LOWER_RIGHT_LEG   8
#define BODY_LOC_BIRD_LEFT_KNEE         9
#define BODY_LOC_BIRD_RIGHT_KNEE        10
#define BODY_LOC_BIRD_LEFT_FOOT         11
#define BODY_LOC_BIRD_RIGHT_FOOT        12
#define BODY_LOC_BIRD_LEFT_ANKLE        13
#define BODY_LOC_BIRD_RIGHT_ANKLE       14
#define BODY_LOC_BIRD_LEFT_WING         15
#define BODY_LOC_BIRD_RIGHT_WING        16
#define BODY_LOC_BIRD_BEAK              17
#define BODY_LOC_HIGHEST_BIRD  17
#define NUMB_BIRD_BODY_LOCS   ((BODY_LOC_HIGHEST_BIRD - BODY_LOC_LOWEST_BIRD) + 1)

// winged humanoid

#define BODY_LOC_LOWEST_WINGED_HUMANOID    0
#define BODY_LOC_WINGED_HUMANOID_HEAD               0
#define BODY_LOC_WINGED_HUMANOID_LEFT_EYE           1
#define BODY_LOC_WINGED_HUMANOID_RIGHT_EYE          2
#define BODY_LOC_WINGED_HUMANOID_LEFT_EAR           3
#define BODY_LOC_WINGED_HUMANOID_RIGHT_EAR          4
#define BODY_LOC_WINGED_HUMANOID_NECK               5
#define BODY_LOC_WINGED_HUMANOID_UPPER_TORSO        6
#define BODY_LOC_WINGED_HUMANOID_LOWER_TORSO        7
#define BODY_LOC_WINGED_HUMANOID_UPPER_LEFT_ARM     8
#define BODY_LOC_WINGED_HUMANOID_LOWER_LEFT_ARM     9
#define BODY_LOC_WINGED_HUMANOID_LEFT_ELBOW        10
#define BODY_LOC_WINGED_HUMANOID_UPPER_RIGHT_ARM   11
#define BODY_LOC_WINGED_HUMANOID_LOWER_RIGHT_ARM   12
#define BODY_LOC_WINGED_HUMANOID_RIGHT_ELBOW       13
#define BODY_LOC_WINGED_HUMANOID_LEFT_WRIST        14
#define BODY_LOC_WINGED_HUMANOID_RIGHT_WRIST       15
#define BODY_LOC_WINGED_HUMANOID_LEFT_HAND         16
#define BODY_LOC_WINGED_HUMANOID_RIGHT_HAND        17
#define BODY_LOC_WINGED_HUMANOID_UPPER_LEFT_LEG    18
#define BODY_LOC_WINGED_HUMANOID_LOWER_LEFT_LEG    19
#define BODY_LOC_WINGED_HUMANOID_UPPER_RIGHT_LEG   20
#define BODY_LOC_WINGED_HUMANOID_LOWER_RIGHT_LEG   21
#define BODY_LOC_WINGED_HUMANOID_LEFT_KNEE         22
#define BODY_LOC_WINGED_HUMANOID_RIGHT_KNEE        23
#define BODY_LOC_WINGED_HUMANOID_LEFT_FOOT         24
#define BODY_LOC_WINGED_HUMANOID_RIGHT_FOOT        25
#define BODY_LOC_WINGED_HUMANOID_LEFT_ANKLE        26
#define BODY_LOC_WINGED_HUMANOID_RIGHT_ANKLE       27
#define BODY_LOC_WINGED_HUMANOID_CHIN              28
#define BODY_LOC_WINGED_HUMANOID_LEFT_SHOULDER     29
#define BODY_LOC_WINGED_HUMANOID_RIGHT_SHOULDER    30
#define BODY_LOC_WINGED_HUMANOID_LEFT_WING         31
#define BODY_LOC_WINGED_HUMANOID_RIGHT_WING        32
#define BODY_LOC_HIGHEST_WINGED_HUMANOID  32
#define NUMB_WINGED_HUMANOID_BODY_LOCS   ((BODY_LOC_HIGHEST_WINGED_HUMANOID - BODY_LOC_LOWEST_WINGED_HUMANOID) + 1)

// winged quadraped

#define BODY_LOC_LOWEST_WINGED_QUADRUPED   0
#define BODY_LOC_WINGED_QUADRUPED_HEAD               0
#define BODY_LOC_WINGED_QUADRUPED_LEFT_EYE           1
#define BODY_LOC_WINGED_QUADRUPED_RIGHT_EYE          2
#define BODY_LOC_WINGED_QUADRUPED_LEFT_EAR           3
#define BODY_LOC_WINGED_QUADRUPED_RIGHT_EAR          4
#define BODY_LOC_WINGED_QUADRUPED_NECK               5
#define BODY_LOC_WINGED_QUADRUPED_FRONT_BODY         6
#define BODY_LOC_WINGED_QUADRUPED_REAR_BODY          7
#define BODY_LOC_WINGED_QUADRUPED_UPPER_LEFT_FRONT_LEG 8
#define BODY_LOC_WINGED_QUADRUPED_LOWER_LEFT_FRONT_LEG 9
#define BODY_LOC_WINGED_QUADRUPED_UPPER_RIGHT_FRONT_LEG 10
#define BODY_LOC_WINGED_QUADRUPED_LOWER_RIGHT_FRONT_LEG 11
#define BODY_LOC_WINGED_QUADRUPED_LEFT_FRONT_KNEE    12
#define BODY_LOC_WINGED_QUADRUPED_RIGHT_FRONT_KNEE   13
#define BODY_LOC_WINGED_QUADRUPED_LEFT_FRONT_HOOF    14
#define BODY_LOC_WINGED_QUADRUPED_RIGHT_FRONT_HOOF   15
#define BODY_LOC_WINGED_QUADRUPED_LEFT_FRONT_ANKLE   16
#define BODY_LOC_WINGED_QUADRUPED_RIGHT_FRONT_ANKLE  17
#define BODY_LOC_WINGED_QUADRUPED_UPPER_LEFT_REAR_LEG 18
#define BODY_LOC_WINGED_QUADRUPED_LOWER_LEFT_REAR_LEG 19
#define BODY_LOC_WINGED_QUADRUPED_UPPER_RIGHT_REAR_LEG 20
#define BODY_LOC_WINGED_QUADRUPED_LOWER_RIGHT_REAR_LEG 21
#define BODY_LOC_WINGED_QUADRUPED_LEFT_REAR_KNEE     22
#define BODY_LOC_WINGED_QUADRUPED_RIGHT_REAR_KNEE    23
#define BODY_LOC_WINGED_QUADRUPED_LEFT_REAR_HOOF     24
#define BODY_LOC_WINGED_QUADRUPED_RIGHT_REAR_HOOF    25
#define BODY_LOC_WINGED_QUADRUPED_LEFT_REAR_ANKLE    26
#define BODY_LOC_WINGED_QUADRUPED_RIGHT_REAR_ANKLE   27
#define BODY_LOC_WINGED_QUADRUPED_CHIN               28
#define BODY_LOC_WINGED_QUADRUPED_LEFT_WING          29
#define BODY_LOC_WINGED_QUADRUPED_RIGHT_WING         30
#define BODY_LOC_HIGHEST_WINGED_QUADRUPED  30
#define NUMB_WINGED_QUADRUPED_BODY_LOCS   ((BODY_LOC_HIGHEST_WINGED_QUADRUPED - BODY_LOC_LOWEST_WINGED_QUADRUPED) + 1)

// no extremities

#define BODY_LOC_LOWEST_NO_EXTREMITIES   0
#define BODY_LOC_NO_EXTREMITIES_HEAD               0
#define BODY_LOC_NO_EXTREMITIES_LEFT_EYE           1
#define BODY_LOC_NO_EXTREMITIES_RIGHT_EYE          2
#define BODY_LOC_NO_EXTREMITIES_BODY   3
#define BODY_LOC_HIGHEST_NO_EXTREMITIES  3
#define NUMB_NO_EXTREMITIES_BODY_LOCS   ((BODY_LOC_HIGHEST_NO_EXTREMITIES - BODY_LOC_LOWEST_NO_EXTREMITIES) + 1)

// insectoid

#define BODY_LOC_LOWEST_INSECTOID 0
#define BODY_LOC_INSECTOID_HEAD               0
#define BODY_LOC_INSECTOID_LEFT_EYE           1
#define BODY_LOC_INSECTOID_RIGHT_EYE          2
#define BODY_LOC_INSECTOID_UPPER_BODY        3
#define BODY_LOC_INSECTOID_LOWER_BODY        4
#define BODY_LOC_INSECTOID_FRONT_LEFT_UPPER_LEG 5
#define BODY_LOC_INSECTOID_FRONT_LEFT_LOWER_LEG 6 
#define BODY_LOC_INSECTOID_FRONT_LEFT_LOWER_JOINT  7
#define BODY_LOC_INSECTOID_FRONT_RIGHT_UPPER_LEG 8
#define BODY_LOC_INSECTOID_FRONT_RIGHT_LOWER_LEG 9
#define BODY_LOC_INSECTOID_FRONT_RIGHT_LOWER_JOINT 10
#define BODY_LOC_INSECTOID_FRONT_LEFT_UPPER_JOINT 11
#define BODY_LOC_INSECTOID_FRONT_RIGHT_UPPER_JOINT 12
#define BODY_LOC_INSECTOID_MIDDLE_LEFT_UPPER_LEG 13
#define BODY_LOC_INSECTOID_MIDDLE_LEFT_LOWER_LEG 14
#define BODY_LOC_INSECTOID_MIDDLE_LEFT_LOWER_JOINT  15
#define BODY_LOC_INSECTOID_MIDDLE_RIGHT_UPPER_LEG 16
#define BODY_LOC_INSECTOID_MIDDLE_RIGHT_LOWER_LEG 17
#define BODY_LOC_INSECTOID_MIDDLE_RIGHT_LOWER_JOINT 18
#define BODY_LOC_INSECTOID_MIDDLE_LEFT_UPPER_JOINT 19
#define BODY_LOC_INSECTOID_MIDDLE_RIGHT_UPPER_JOINT 20
#define BODY_LOC_INSECTOID_BACK_LEFT_UPPER_LEG 21
#define BODY_LOC_INSECTOID_BACK_LEFT_LOWER_LEG 22
#define BODY_LOC_INSECTOID_BACK_LEFT_LOWER_JOINT  23
#define BODY_LOC_INSECTOID_BACK_RIGHT_UPPER_LEG 24
#define BODY_LOC_INSECTOID_BACK_RIGHT_LOWER_LEG 25
#define BODY_LOC_INSECTOID_BACK_RIGHT_LOWER_JOINT 26
#define BODY_LOC_INSECTOID_BACK_LEFT_UPPER_JOINT 27
#define BODY_LOC_INSECTOID_BACK_RIGHT_UPPER_JOINT 28
#define BODY_LOC_HIGHEST_INSECTOID 28
#define NUMB_INSECTOID_BODY_LOCS   ((BODY_LOC_HIGHEST_INSECTOID - BODY_LOC_LOWEST_INSECTOID) + 1)

// arachnid

#define BODY_LOC_LOWEST_ARACHNID 0
#define BODY_LOC_ARACHNID_HEAD               0
#define BODY_LOC_ARACHNID_LEFT_EYE           1
#define BODY_LOC_ARACHNID_RIGHT_EYE          2
#define BODY_LOC_ARACHNID_UPPER_BODY        3
#define BODY_LOC_ARACHNID_LOWER_BODY        4
#define BODY_LOC_ARACHNID_FRONT_LEFT_UPPER_LEG 5
#define BODY_LOC_ARACHNID_FRONT_LEFT_LOWER_LEG 6 
#define BODY_LOC_ARACHNID_FRONT_LEFT_LOWER_JOINT  7
#define BODY_LOC_ARACHNID_FRONT_RIGHT_UPPER_LEG 8
#define BODY_LOC_ARACHNID_FRONT_RIGHT_LOWER_LEG 9
#define BODY_LOC_ARACHNID_FRONT_RIGHT_LOWER_JOINT 10
#define BODY_LOC_ARACHNID_FRONT_LEFT_UPPER_JOINT 11
#define BODY_LOC_ARACHNID_FRONT_RIGHT_UPPER_JOINT 12
#define BODY_LOC_ARACHNID_MIDDLE_LEFT_UPPER_LEG 13     // right behind front legs
#define BODY_LOC_ARACHNID_MIDDLE_LEFT_LOWER_LEG 14
#define BODY_LOC_ARACHNID_MIDDLE_LEFT_LOWER_JOINT  15
#define BODY_LOC_ARACHNID_MIDDLE_RIGHT_UPPER_LEG 16
#define BODY_LOC_ARACHNID_MIDDLE_RIGHT_LOWER_LEG 17
#define BODY_LOC_ARACHNID_MIDDLE_RIGHT_LOWER_JOINT 18
#define BODY_LOC_ARACHNID_MIDDLE_LEFT_UPPER_JOINT 19
#define BODY_LOC_ARACHNID_MIDDLE_RIGHT_UPPER_JOINT 20
#define BODY_LOC_ARACHNID_MIDDLE2_LEFT_UPPER_LEG 21    // right in front of back legs
#define BODY_LOC_ARACHNID_MIDDLE2_LEFT_LOWER_LEG 22
#define BODY_LOC_ARACHNID_MIDDLE2_LEFT_LOWER_JOINT  23
#define BODY_LOC_ARACHNID_MIDDLE2_RIGHT_UPPER_LEG 24
#define BODY_LOC_ARACHNID_MIDDLE2_RIGHT_LOWER_LEG 25
#define BODY_LOC_ARACHNID_MIDDLE2_RIGHT_LOWER_JOINT 26
#define BODY_LOC_ARACHNID_MIDDLE2_LEFT_UPPER_JOINT 27
#define BODY_LOC_ARACHNID_MIDDLE2_RIGHT_UPPER_JOINT 28
#define BODY_LOC_ARACHNID_BACK_LEFT_UPPER_LEG 29
#define BODY_LOC_ARACHNID_BACK_LEFT_LOWER_LEG 30
#define BODY_LOC_ARACHNID_BACK_LEFT_LOWER_JOINT  31
#define BODY_LOC_ARACHNID_BACK_RIGHT_UPPER_LEG 32
#define BODY_LOC_ARACHNID_BACK_RIGHT_LOWER_LEG 33
#define BODY_LOC_ARACHNID_BACK_RIGHT_LOWER_JOINT 34
#define BODY_LOC_ARACHNID_BACK_LEFT_UPPER_JOINT 35
#define BODY_LOC_ARACHNID_BACK_RIGHT_UPPER_JOINT 36
#define BODY_LOC_HIGHEST_ARACHNID 36
#define NUMB_ARACHNID_BODY_LOCS   ((BODY_LOC_HIGHEST_ARACHNID - BODY_LOC_LOWEST_ARACHNID) + 1)

// beholder - 8 eyestalks, big mass for a body, one big eye in middle

#define BODY_LOC_LOWEST_BEHOLDER             0
#define BODY_LOC_BEHOLDER_BODY               0
#define BODY_LOC_BEHOLDER_MAIN_EYE           1  // eye in body
#define BODY_LOC_BEHOLDER_EYESTALK1          2  // all face forward, 8 of em
#define BODY_LOC_BEHOLDER_EYESTALK2          3  // all face forward, 8 of em
#define BODY_LOC_BEHOLDER_EYESTALK3          4  // all face forward, 8 of em
#define BODY_LOC_BEHOLDER_EYESTALK4          5  // all face forward, 8 of em
#define BODY_LOC_BEHOLDER_EYESTALK5          6  // all face forward, 8 of em
#define BODY_LOC_BEHOLDER_EYESTALK6          7  // all face forward, 8 of em
#define BODY_LOC_BEHOLDER_EYESTALK7          8  // all face forward, 8 of em
#define BODY_LOC_BEHOLDER_EYESTALK8          9  // all face forward, 8 of em
#define BODY_LOC_HIGHEST_BEHOLDER            9
#define NUMB_BEHOLDER_BODY_LOCS   ((BODY_LOC_HIGHEST_BEHOLDER - BODY_LOC_LOWEST_BEHOLDER) + 1)

#endif
