/*
 * skill.rec.h - Provide an uniformed way to handle skills
 *
 */

#ifndef _SOJ_SKILLREC_H_
#define _SOJ_SKILLREC_H_

#define SKILL_TYPE_NONE 0
#define SKILL_TYPE_MENTAL_INT 1
#define SKILL_TYPE_MENTAL_WIS 2
#define SKILL_TYPE_PHYS_STR 3
#define SKILL_TYPE_PHYS_CON 4
#define SKILL_TYPE_PHYS_DEX 5
#define SKILL_TYPE_PHYS_AGI 6

#define SPELL_TYPE_GENERIC SKILL_CAST_GENERIC
#define SPELL_TYPE_FIRE SKILL_CAST_FIRE
#define SPELL_TYPE_COLD SKILL_CAST_COLD
#define SPELL_TYPE_HEALING SKILL_CAST_HEALING
#define SPELL_TYPE_TELEPORTATION SKILL_CAST_TELEPORTATION
#define SPELL_TYPE_SUMMONING SKILL_CAST_SUMMONING
#define SPELL_TYPE_PROTECTION SKILL_CAST_PROTECTION
#define SPELL_TYPE_DIVINATION SKILL_CAST_DIVINATION
#define SPELL_TYPE_ELECTRIC SKILL_CAST_ELECTRIC
#define SPELL_TYPE_ACID SKILL_CAST_ACID
#define SPELL_TYPE_ENCHANT SKILL_CAST_ENCHANT

#endif /* _SOJ_SKILLREC_H_ */
