/*
 **************************************************************************
 *  File: sound.h                                             Part of Duris 
 *  Usage: sound fonction for MSP
 *  Copyright 1994 - 2008 - Duris Systems Ltd.
 **************************************************************************
 */

#define SOUND_OFF            "!!SOUND(off)"
#define SOUND_ACID_BLAST     "!!SOUND(acid_blast.* L=1)"
#define SOUND_ARGH           "!!SOUND(argh.* L=1)"
#define SOUND_ARROW1         "!!SOUND(arrow1.* L=1)"
#define SOUND_ARROW2         "!!SOUND(arrow2.* L=1)"
#define SOUND_ARROW3         "!!SOUND(arrow3.* L=1)"
#define SOUND_BACKSTAB       "!!SOUND(backstab.* L=1)"
#define SOUND_BIRDS1         "!!SOUND(birds1.* L=1)"
#define SOUND_BIRDS2         "!!SOUND(birds2.* L=1)"
#define SOUND_BIRDS3         "!!SOUND(birds3.* L=1)"
#define SOUND_BLESS          "!!SOUND(bless.* L=1)"
#define SOUND_BOING          "!!SOUND(boing.* L=1)"
#define SOUND_BOW_DOWN       "!!SOUND(bow_down.* L=1)"
#define SOUND_CALL_LIGHTNING "!!SOUND(call_lightning.* L=1)"
#define SOUND_CHANT1         "!!SOUND(chant1.* L=1)"
#define SOUND_COME_BACK      "!!SOUND(come_back.* L=1)"
#define SOUND_CRICKETS       "!!SOUND(crickets.* L=1)"
#define SOUND_CROSSBOW_BOLT  "!!SOUND(crossbow_bolt.* L=1)"
#define SOUND_CROWD_CLAPPING "!!SOUND(crowd_clapping.* L=1)"
#define SOUND_CURSE          "!!SOUND(curse.* L=1)"
#define SOUND_DEAD           "!!SOUND(dead.* L=1)"
#define SOUND_DEATH_CRY      "!!SOUND(death_cry.* L=1)"
#define SOUND_DOG1           "!!SOUND(dog1.* L=1)"
#define SOUND_DOOR           "!!SOUND(door.* L=1)"
#define SOUND_DOOR1          "!!SOUND(door1.* L=1)"
#define SOUND_DRAGON1        "!!SOUND(dragon1.* L=1)"
#define SOUND_DRAGON2        "!!SOUND(dragon2.* L=1)"
#define SOUND_DRAGON3        "!!SOUND(dragon3.* L=1)"
#define SOUND_EARTHQUAKE1    "!!SOUND(earthquake1.* L=1)"
#define SOUND_EARTHQUAKE2    "!!SOUND(earthquake2.* L=1)"
#define SOUND_ELECTRIC       "!!SOUND(electric.* L=1)"
#define SOUND_ELEMENTAL      "!!SOUND(elemental.* L=1)"
#define SOUND_EXIT_GAME      "!!SOUND(exit_game.* L=1)"
#define SOUND_FALLING1       "!!SOUND(falling1.* L=1)"
#define SOUND_FARSITE        "!!SOUND(farsite.* L=1)"
#define SOUND_FIREBALL       "!!SOUND(fireball.* L=1)"
#define SOUND_FIRESTORM      "!!SOUND(firestorm.* L=1)"
#define SOUND_FIST           "!!SOUND(Fist.* L=1)"
#define SOUND_F_SHARDS       "!!SOUND(f_shards.* L=1)"
#define SOUND_GLASS1         "!!SOUND(glass1.* L=1)"
#define SOUND_GLASS2         "!!SOUND(glass2.* L=1)"
#define SOUND_GLASS3         "!!SOUND(glass3.* L=1)"
#define SOUND_GLASS4         "!!SOUND(glass4.* L=1)"
#define SOUND_TRANS_PLAYER   "!!SOUND(god_trans_player.* L=1)"
#define SOUND_GOOD_MASTER    "!!SOUND(good_master.* L=1)"
#define SOUND_HAMMER         "!!SOUND(hammer_on_shield.* L=1)"
#define SOUND_HARP           "!!SOUND(harp.* L=1)"
#define SOUND_HORSE1         "!!SOUND(horse1.* L=1)"
#define SOUND_HORSE2         "!!SOUND(horse2.* L=1)"
#define SOUND_LAUGH          "!!SOUND(laugh.* L=1)"
#define SOUND_LAWPAY         "!!SOUND(lawpay.* L=1)"
#define SOUND_MMISSILE       "!!SOUND(magic_missle.* L=1)"
#define SOUND_MISC1          "!!SOUND(misc1.* L=1)"
#define SOUND_MOONWELL       "!!SOUND(moonwell.* L=1)"
#define SOUND_MUMMY          "!!SOUND(mummy.* L=1)"
#define SOUND_NONEPASS       "!!SOUND(nonepass.* L=1)"
#define SOUND_PEOPLE         "!!SOUND(people.* L=1)"
#define SOUND_PORTAL         "!!SOUND(portal.* L=1)"
#define SOUND_PUNCH          "!!SOUND(punch.* L=1)"
#define SOUND_PUNCH2         "!!SOUND(punch2.* L=1)"
#define SOUND_RAISE_DEAD     "!!SOUND(raise_dead.* L=1)"
#define SOUND_RECALL         "!!SOUND(recall.* L=1)"
#define SOUND_RECALL2        "!!SOUND(recall2.* L=1)"
#define SOUND_RESSURECTION   "!!SOUND(ressurection.* L=1)"
#define SOUND_RETREAT_CAVE   "!!SOUND(retreat_cave.* L=1)"
#define SOUND_RUMBLE         "!!SOUND(rumble.* L=1)"
#define SOUND_RUNAWAY        "!!SOUND(runaway.* L=1)"
#define SOUND_RUN_FOOLS      "!!SOUND(run_fools.* L=1)"
#define SOUND_SANC           "!!SOUND(sanc.* L=1)"
#define SOUND_SANC_OUT       "!!SOUND(sanc_out.* L=1)"
#define SOUND_SCREAM         "!!SOUND(scream.* L=1)"
#define SOUND_SHOCKING_GRASP "!!SOUND(shocking_grasp.* L=1)"
#define SOUND_SHOCKWAVE      "!!SOUND(shoc.*e.wav L=1)"
#define SOUND_SPELL1         "!!SOUND(spell_type1.* L=1)"
#define SOUND_SPELL2         "!!SOUND(spell_type2.* L=1)"
#define SOUND_SPELL3         "!!SOUND(spell_type3.* L=1)"
#define SOUND_START_GAME     "!!SOUND(start_game.* L=1)"
#define SOUND_STEEL_DOOR     "!!SOUND(steel_door.* L=1)"
#define SOUND_SWORD1         "!!SOUND(sword1.* L=1)"
#define SOUND_SWORD2         "!!SOUND(sword2.* L=1)"
#define SOUND_SWORD3         "!!SOUND(sword3.* L=1)"
#define SOUND_THUNDER        "!!SOUND(thunder.* L=1)"
#define SOUND_THUNDER1       "!!SOUND(thunder1.* L=1)"
#define SOUND_THUNDER2       "!!SOUND(thunder2.* L=1)"
#define SOUND_TOWN_JANITOR   "!!SOUND(town_janitor.* L=1)"
#define SOUND_TREMOR         "!!SOUND(tremor.* L=1)"
#define SOUND_TRUMPET        "!!SOUND(trumpet.* L=1)"
#define SOUND_WATER          "!!SOUND(water.* L=1)"
#define SOUND_WATER1         "!!SOUND(water1.* L=1)"
#define SOUND_WATER_DROP     "!!SOUND(water_drop.* L=1)"
#define SOUND_WHIP           "!!SOUND(whip.* L=1)"
#define SOUND_WHIP2          "!!SOUND(whip2.* L=1)"
#define SOUND_WIND           "!!SOUND(wind.* L=1)"
#define SOUND_WIND1          "!!SOUND(wind1.* L=1)"
#define SOUND_WIND2          "!!SOUND(wind2.* L=1)"
#define SOUND_WIND3          "!!SOUND(wind3.* L=1)"

#define MUSIC_OFF            "!!MUSIC(off)"
#define MUSIC_BAL            "!!MUSIC(Bal.mid L=1)"
#define MUSIC_COMBAT         "!!MUSIC(combat_music.mid L=1)"
#define MUSIC_CAST_AWE       "!!MUSIC(cstl_awe.mid L=1)"
#define MUSIC_HAUNTED_HOUSE  "!!MUSIC(haunted_house_music.mid L=1)"
#define MUSIC_CAVE_AWE       "!!MUSIC(cave_awe.mid L=1)"
#define MUSIC_TIAMAT         "!!MUSIC(tiamat_song.mid L=1)"
#define MUSIC_WALK_AWE       "!!MUSIC(walk_awe.mid L=1)"
