#include <stdio.h>
#include <cstring>
#include <vector>
using namespace std;

#include "comm.h"
#include "interp.h"
#include "utils.h"
#include "prototypes.h"
#include "spells.h"
#include "structs.h"
#include "sql.h"
#include "epic.h"
#include "specializations.h"

extern P_room world;
extern char *specdata[][MAX_SPEC];
extern const struct class_names class_names_table[];
extern const struct race_names race_names_table[];

#define SPEC_ALL 0

// this is the list of class specialziations blocked for certain races
struct allowed_race_spec_struct {
  int race;
  uint m_class;
  int spec;
} allowed_race_specs[] =
{
    /* War Ran Psi Pal APa Cle Mon Dru Sha Sor Nec Con Rog Mer Bar Ber Rea Illu Dre Eth Ave The */
	/* RACE_HUMAN,     RACE_BARBARIAN, RACE_DROW,      RACE_GREY,      RACE_MOUNTAIN, RACE_DUERGAR,
	 * RACE_HALFLING,  RACE_GNOME,     RACE_OGRE,      RACE_TROLL,     RACE_HALFELF,  RACE_ORC,
	 * RACE_THRIKREEN, RACE_CENTAUR,   RACE_GITHYANKI, RACE_MINOTAUR,  RACE_GOBLIN,   RACE_PLICH,
	 * RACE_PVAMPIRE,  RACE_GITHZERAI, RACE_DRIDER,    RACE_AGATHINON, RACE_ELADRIN,  RACE_KOBOLD,
	 * RACE_PILLITHID, RACE_KUOTOA,    RACE_WOODELF,   RACE_FIRBOLG */
	/* Start Human Options */
<<<<<<< HEAD
	{RACE_HUMAN, CLASS_WARRIOR,     SPEC_ALL},
	{RACE_HUMAN, CLASS_RANGER,      SPEC_HUNTSMAN},
	{RACE_HUMAN, CLASS_PALADIN,     SPEC_CAVALIER},
	{RACE_HUMAN, CLASS_CLERIC,      SPEC_ZEALOT},
	{RACE_HUMAN, CLASS_DRUID,       SPEC_STORM},
	{RACE_HUMAN, CLASS_SORCERER,    SPEC_ALL},
	{RACE_HUMAN, CLASS_CONJURER,    SPEC_WATER},
        {RACE_HUMAN, CLASS_CONJURER,    SPEC_AIR},
=======
	{RACE_HUMAN, CLASS_WARRIOR,   SPEC_GUARDIAN},
	{RACE_HUMAN, CLASS_WARRIOR,   SPEC_SWORDSMAN},
	{RACE_HUMAN, CLASS_RANGER,      SPEC_ALL},
	{RACE_HUMAN, CLASS_PALADIN,     SPEC_ALL},
	{RACE_HUMAN, CLASS_CLERIC,      SPEC_ALL},
       {RACE_HUMAN, CLASS_ANTIPALADIN,    SPEC_ALL},
	{RACE_HUMAN, CLASS_DRUID,       SPEC_ALL},
	{RACE_HUMAN, CLASS_SHAMAN,      SPEC_ALL},
	{RACE_HUMAN, CLASS_SHAMAN,      SPEC_ALL},
	{RACE_HUMAN, CLASS_SORCERER,    SPEC_ALL},
	{RACE_HUMAN, CLASS_CONJURER,    SPEC_AIR},
	{RACE_HUMAN, CLASS_CONJURER,    SPEC_WATER},
	{RACE_HUMAN, CLASS_CONJURER,    SPEC_EARTH},
>>>>>>> master
	{RACE_HUMAN, CLASS_ROGUE,       SPEC_THIEF},
	{RACE_HUMAN, CLASS_ROGUE,       SPEC_ASSASSIN},
	{RACE_HUMAN, CLASS_MERCENARY,   SPEC_BRIGAND},
	{RACE_HUMAN, CLASS_BARD,        SPEC_ALL},
<<<<<<< HEAD
	{RACE_HUMAN, CLASS_ILLUSIONIST, SPEC_MAGICIAN},
        {RACE_HUMAN, CLASS_CABALIST,    SPEC_ALL},
	{RACE_HUMAN, CLASS_NECROMANCER, SPEC_ALL},
	{RACE_HUMAN, CLASS_MONK,        SPEC_ALL},
	/* End Human Options */

	/* Start Barbarian Options */
	{RACE_BARBARIAN, CLASS_WARRIOR,   SPEC_GUARDIAN},
	{RACE_BARBARIAN, CLASS_SHAMAN,    SPEC_SPIRITUALIST},
	{RACE_BARBARIAN, CLASS_SHAMAN,    SPEC_ANIMALIST},
	{RACE_BARBARIAN, CLASS_MERCENARY, SPEC_BRIGAND},
	/* End Barbarian Options */

	/* Start Drow Elf Options */
	{RACE_DROW, CLASS_WARRIOR,     SPEC_SWORDSMAN},
	{RACE_DROW, CLASS_CLERIC,      SPEC_HEALER},
	{RACE_DROW, CLASS_CLERIC,      SPEC_ZEALOT},
	{RACE_DROW, CLASS_SORCERER,    SPEC_WIZARD},
	{RACE_DROW, CLASS_SORCERER,    SPEC_WILDMAGE},
	{RACE_DROW, CLASS_NECROMANCER, SPEC_DIABOLIS},
	{RACE_DROW, CLASS_NECROMANCER, SPEC_REAPER},
	{RACE_DROW, CLASS_CONJURER,    SPEC_AIR},
	{RACE_DROW, CLASS_CONJURER,    SPEC_EARTH},
	{RACE_DROW, CLASS_ROGUE,       SPEC_THIEF},
	{RACE_DROW, CLASS_BARD,        SPEC_MINSTREL},
	{RACE_DROW, CLASS_REAVER,      SPEC_FLAME_REAVER},
	{RACE_DROW, CLASS_REAVER,      SPEC_SHOCK_REAVER},
	/* End Drow Elf Options */

	/* Start Grey Elf Options */
	{RACE_GREY, CLASS_WARRIOR,  SPEC_SWORDSMAN},
	{RACE_GREY, CLASS_RANGER,   SPEC_BLADEMASTER},
	{RACE_GREY, CLASS_CLERIC,   SPEC_HEALER},
	{RACE_GREY, CLASS_CLERIC,   SPEC_ZEALOT},
	{RACE_GREY, CLASS_DRUID,    SPEC_FOREST},
	{RACE_GREY, CLASS_SORCERER, SPEC_WIZARD},
	{RACE_GREY, CLASS_SORCERER, SPEC_WILDMAGE},
	{RACE_GREY, CLASS_CONJURER, SPEC_AIR},
	{RACE_GREY, CLASS_CONJURER, SPEC_EARTH},
	{RACE_GREY, CLASS_BARD,     SPEC_MINSTREL},
        {RACE_GREY, CLASS_PALADIN,  SPEC_CRUSADER},
	/* End Grey Elf Options */

	/* Start Mountain Dwarf Options */
	{RACE_MOUNTAIN, CLASS_WARRIOR,   SPEC_GUARDIAN},
	{RACE_MOUNTAIN, CLASS_CLERIC,    SPEC_HOLYMAN},
	{RACE_MOUNTAIN, CLASS_CLERIC,    SPEC_HEALER},
	{RACE_MOUNTAIN, CLASS_MERCENARY, SPEC_BRIGAND},
        {RACE_MOUNTAIN, CLASS_BARD,      SPEC_DISHARMONIST},
=======
	{RACE_HUMAN, CLASS_BERSERKER,   SPEC_ALL},
	{RACE_HUMAN, CLASS_ILLUSIONIST, SPEC_ALL},
       {RACE_HUMAN, CLASS_CABALIST,    SPEC_ALL},
	{RACE_HUMAN, CLASS_ETHERMANCER, SPEC_ALL},
	{RACE_HUMAN, CLASS_THEURGIST,   SPEC_ALL},
 	{RACE_HUMAN, CLASS_MONK,        SPEC_ALL},
	{RACE_HUMAN, CLASS_NECROMANCER, SPEC_ALL},
       {RACE_HUMAN, CLASS_PSIONICIST,  SPEC_ALL},
	{RACE_HUMAN, CLASS_REAVER,        SPEC_ICE_REAVER}, 
        {RACE_HUMAN, CLASS_REAVER,        SPEC_SHOCK_REAVER},
        {RACE_HUMAN, CLASS_REAVER,        SPEC_FLAME_REAVER},
	/* End Human Options */

	/* Start Barbarian Options */
       {RACE_BARBARIAN, CLASS_WARRIOR,   SPEC_GUARDIAN},
	{RACE_BARBARIAN, CLASS_WARRIOR,   SPEC_SWORDSMAN},
	{RACE_BARBARIAN, CLASS_RANGER,      SPEC_ALL},
	{RACE_BARBARIAN, CLASS_PALADIN,     SPEC_ALL},
	{RACE_BARBARIAN, CLASS_CLERIC,      SPEC_ALL},
       {RACE_BARBARIAN, CLASS_ANTIPALADIN,    SPEC_ALL},
	{RACE_BARBARIAN, CLASS_DRUID,       SPEC_ALL},
	{RACE_BARBARIAN, CLASS_SHAMAN,      SPEC_ALL},
	{RACE_BARBARIAN, CLASS_SHAMAN,      SPEC_ALL},
	{RACE_BARBARIAN, CLASS_SORCERER,    SPEC_ALL},
	{RACE_BARBARIAN, CLASS_CONJURER,    SPEC_AIR},
	{RACE_BARBARIAN, CLASS_CONJURER,    SPEC_WATER},
	{RACE_BARBARIAN, CLASS_CONJURER,    SPEC_EARTH},
	{RACE_BARBARIAN, CLASS_ROGUE,       SPEC_THIEF},
	{RACE_BARBARIAN, CLASS_ROGUE,       SPEC_ASSASSIN},
	{RACE_BARBARIAN, CLASS_MERCENARY,   SPEC_ALL},
	{RACE_BARBARIAN, CLASS_BARD,        SPEC_ALL},
	{RACE_BARBARIAN, CLASS_BERSERKER,   SPEC_ALL},
	{RACE_BARBARIAN, CLASS_ILLUSIONIST, SPEC_ALL},
       {RACE_BARBARIAN, CLASS_CABALIST,    SPEC_ALL},
	{RACE_BARBARIAN, CLASS_ETHERMANCER, SPEC_ALL},
	{RACE_BARBARIAN, CLASS_THEURGIST,   SPEC_ALL},
 	{RACE_BARBARIAN, CLASS_MONK,        SPEC_ALL},
	{RACE_BARBARIAN, CLASS_NECROMANCER, SPEC_ALL},
       {RACE_BARBARIAN, CLASS_PSIONICIST,  SPEC_ALL},
	{RACE_BARBARIAN, CLASS_REAVER,        SPEC_ICE_REAVER}, 
        {RACE_BARBARIAN, CLASS_REAVER,        SPEC_SHOCK_REAVER},
        {RACE_BARBARIAN, CLASS_REAVER,        SPEC_FLAME_REAVER},
	/* End Barbarian Options */

	/* Start Drow Elf Options */
	{RACE_DROW, CLASS_WARRIOR,   SPEC_GUARDIAN},
	{RACE_DROW, CLASS_WARRIOR,   SPEC_SWORDSMAN},
	{RACE_DROW, CLASS_RANGER,      SPEC_ALL},
	{RACE_DROW, CLASS_ANTIPALADIN,   SPEC_ALL},
       {RACE_DROW, CLASS_DRUID,         SPEC_ALL},
	{RACE_DROW, CLASS_CLERIC,        SPEC_ALL},
	{RACE_DROW, CLASS_SHAMAN,        SPEC_ALL},
	{RACE_DROW, CLASS_PSIONICIST,      SPEC_ALL},
       {RACE_DROW, CLASS_SORCERER,      SPEC_ALL},
	{RACE_DROW, CLASS_CONJURER,    SPEC_AIR},
	{RACE_DROW, CLASS_CONJURER,    SPEC_WATER},
	{RACE_DROW, CLASS_CONJURER,    SPEC_EARTH},
	{RACE_DROW, CLASS_ROGUE,         SPEC_THIEF},
	{RACE_DROW, CLASS_ROGUE,         SPEC_ASSASSIN},
	{RACE_DROW, CLASS_MERCENARY,     SPEC_ALL},
	{RACE_DROW, CLASS_BARD,          SPEC_ALL},
	{RACE_DROW, CLASS_BERSERKER,     SPEC_ALL},
	{RACE_DROW, CLASS_REAVER,        SPEC_ICE_REAVER}, 
        {RACE_DROW, CLASS_REAVER,        SPEC_SHOCK_REAVER},
        {RACE_DROW, CLASS_REAVER,        SPEC_FLAME_REAVER},
	{RACE_DROW, CLASS_ETHERMANCER,   SPEC_ALL},
	{RACE_DROW, CLASS_NECROMANCER,   SPEC_ALL},
       {RACE_DROW, CLASS_MONK, 	    SPEC_ALL},
       {RACE_DROW, CLASS_ILLUSIONIST,   SPEC_ALL},
	/* End Drow Elf Options */

	/* Start Grey Elf Options */
	       {RACE_GREY, CLASS_WARRIOR,   SPEC_GUARDIAN},
	{RACE_GREY, CLASS_WARRIOR,   SPEC_SWORDSMAN},
	{RACE_GREY, CLASS_RANGER,      SPEC_ALL},
	{RACE_GREY, CLASS_PALADIN,     SPEC_ALL},
	{RACE_GREY, CLASS_CLERIC,      SPEC_ALL},
       {RACE_GREY, CLASS_ANTIPALADIN,    SPEC_ALL},
	{RACE_GREY, CLASS_DRUID,       SPEC_ALL},
	{RACE_GREY, CLASS_SHAMAN,      SPEC_ALL},
	{RACE_GREY, CLASS_SHAMAN,      SPEC_ALL},
	{RACE_GREY, CLASS_SORCERER,    SPEC_ALL},
	{RACE_GREY, CLASS_CONJURER,    SPEC_AIR},
	{RACE_GREY, CLASS_CONJURER,    SPEC_WATER},
	{RACE_GREY, CLASS_CONJURER,    SPEC_EARTH},
	{RACE_GREY, CLASS_ROGUE,       SPEC_THIEF},
	{RACE_GREY, CLASS_ROGUE,       SPEC_ASSASSIN},
	{RACE_GREY, CLASS_MERCENARY,   SPEC_ALL},
	{RACE_GREY, CLASS_BARD,        SPEC_ALL},
	{RACE_GREY, CLASS_BERSERKER,   SPEC_ALL},
	{RACE_GREY, CLASS_ILLUSIONIST, SPEC_ALL},
       {RACE_GREY, CLASS_CABALIST,    SPEC_ALL},
	{RACE_GREY, CLASS_ETHERMANCER, SPEC_ALL},
	{RACE_GREY, CLASS_THEURGIST,   SPEC_ALL},
 	{RACE_GREY, CLASS_MONK,        SPEC_ALL},
	{RACE_GREY, CLASS_NECROMANCER, SPEC_ALL},
       {RACE_GREY, CLASS_PSIONICIST,  SPEC_ALL},
	{RACE_GREY, CLASS_REAVER,        SPEC_ICE_REAVER}, 
        {RACE_GREY, CLASS_REAVER,        SPEC_SHOCK_REAVER},
        {RACE_GREY, CLASS_REAVER,        SPEC_FLAME_REAVER},
	/* End Grey Elf Options */

	/* Start Mountain Dwarf Options */
	       {RACE_MOUNTAIN, CLASS_WARRIOR,   SPEC_GUARDIAN},
	{RACE_MOUNTAIN, CLASS_WARRIOR,   SPEC_SWORDSMAN},
	{RACE_MOUNTAIN, CLASS_RANGER,      SPEC_ALL},
	{RACE_MOUNTAIN, CLASS_PALADIN,     SPEC_ALL},
	{RACE_MOUNTAIN, CLASS_CLERIC,      SPEC_ALL},
       {RACE_MOUNTAIN, CLASS_ANTIPALADIN,    SPEC_ALL},
	{RACE_MOUNTAIN, CLASS_DRUID,       SPEC_ALL},
	{RACE_MOUNTAIN, CLASS_SHAMAN,      SPEC_ALL},
	{RACE_MOUNTAIN, CLASS_SHAMAN,      SPEC_ALL},
	{RACE_MOUNTAIN, CLASS_SORCERER,    SPEC_ALL},
	{RACE_MOUNTAIN, CLASS_CONJURER,    SPEC_AIR},
	{RACE_MOUNTAIN, CLASS_CONJURER,    SPEC_WATER},
	{RACE_MOUNTAIN, CLASS_CONJURER,    SPEC_EARTH},
	{RACE_MOUNTAIN, CLASS_ROGUE,       SPEC_THIEF},
	{RACE_MOUNTAIN, CLASS_ROGUE,       SPEC_ASSASSIN},
	{RACE_MOUNTAIN, CLASS_MERCENARY,   SPEC_ALL},
	{RACE_MOUNTAIN, CLASS_BARD,        SPEC_ALL},
	{RACE_MOUNTAIN, CLASS_BERSERKER,   SPEC_ALL},
	{RACE_MOUNTAIN, CLASS_ILLUSIONIST, SPEC_ALL},
       {RACE_MOUNTAIN, CLASS_CABALIST,    SPEC_ALL},
	{RACE_MOUNTAIN, CLASS_ETHERMANCER, SPEC_ALL},
	{RACE_MOUNTAIN, CLASS_THEURGIST,   SPEC_ALL},
 	{RACE_MOUNTAIN, CLASS_MONK,        SPEC_ALL},
	{RACE_MOUNTAIN, CLASS_NECROMANCER, SPEC_ALL},
       {RACE_MOUNTAIN, CLASS_PSIONICIST,  SPEC_ALL},
	{RACE_MOUNTAIN, CLASS_REAVER,        SPEC_ICE_REAVER}, 
        {RACE_MOUNTAIN, CLASS_REAVER,        SPEC_SHOCK_REAVER},
        {RACE_MOUNTAIN, CLASS_REAVER,        SPEC_FLAME_REAVER},
>>>>>>> master
	/* End Mountain Dwarf Options */

	/* Start Duergar Dwarf Options */
	{RACE_DUERGAR, CLASS_WARRIOR,   SPEC_GUARDIAN},
<<<<<<< HEAD
	{RACE_DUERGAR, CLASS_CLERIC,    SPEC_HOLYMAN},
	{RACE_DUERGAR, CLASS_CLERIC,    SPEC_HEALER},
	{RACE_DUERGAR, CLASS_MERCENARY, SPEC_BRIGAND},
	/* End Duergar Dwarf Options */

	/* Start Halfling Options */
	{RACE_HALFLING, CLASS_WARRIOR,     SPEC_SWASHBUCKLER},
	{RACE_HALFLING, CLASS_SORCERER,    SPEC_WILDMAGE},
	{RACE_HALFLING, CLASS_SORCERER,    SPEC_SHADOW},
        {RACE_HALFLING, CLASS_RANGER,      SPEC_HUNTSMAN},
        {RACE_HALFLING, CLASS_MERCENARY,   SPEC_BOUNTY},
        {RACE_HALFLING, CLASS_CONJURER,    SPEC_FIRE},
        {RACE_HALFLING, CLASS_CONJURER,    SPEC_WATER},
	{RACE_HALFLING, CLASS_ROGUE,       SPEC_THIEF},
	{RACE_HALFLING, CLASS_ROGUE,       SPEC_ASSASSIN},
	{RACE_HALFLING, CLASS_BARD,        SPEC_SCOUNDREL},
	{RACE_HALFLING, CLASS_ILLUSIONIST, SPEC_DARK_DREAMER},
	/* End Halfling Options */

	/* Start Gnome Options */
	{RACE_GNOME, CLASS_CLERIC,      SPEC_HOLYMAN},
	{RACE_GNOME, CLASS_SHAMAN,      SPEC_ELEMENTALIST},
	{RACE_GNOME, CLASS_SORCERER,    SPEC_WILDMAGE},
	{RACE_GNOME, CLASS_CONJURER,    SPEC_EARTH},
	{RACE_GNOME, CLASS_CONJURER,    SPEC_FIRE},
        {RACE_GNOME, CLASS_ROGUE,       SPEC_THIEF},
	{RACE_GNOME, CLASS_ILLUSIONIST, SPEC_MAGICIAN},
	/* End Gnome Options */

	/* Start Ogre Options */
	{RACE_OGRE, CLASS_WARRIOR, SPEC_SWORDSMAN},
	{RACE_OGRE, CLASS_SHAMAN, SPEC_SPIRITUALIST},
	{RACE_OGRE, CLASS_SHAMAN, SPEC_ANIMALIST},
	/* End Ogre Options */

	/* Start Troll Options */
	{RACE_TROLL, CLASS_WARRIOR, SPEC_GUARDIAN},
	{RACE_TROLL, CLASS_MERCENARY, SPEC_BOUNTY},
	{RACE_TROLL, CLASS_SHAMAN, SPEC_ELEMENTALIST},
=======
	{RACE_DUERGAR, CLASS_WARRIOR,   SPEC_SWORDSMAN},
	{RACE_DUERGAR, CLASS_ANTIPALADIN,   SPEC_ALL},
	{RACE_DUERGAR, CLASS_RANGER,      SPEC_ALL},
       {RACE_DUERGAR, CLASS_DRUID,         SPEC_ALL},
	{RACE_DUERGAR, CLASS_CLERIC,        SPEC_ALL},
	{RACE_DUERGAR, CLASS_SHAMAN,        SPEC_ALL},
	{RACE_DUERGAR, CLASS_PSIONICIST,      SPEC_ALL},
       {RACE_DUERGAR, CLASS_SORCERER,      SPEC_ALL},
	{RACE_DUERGAR, CLASS_CONJURER,    SPEC_AIR},
	{RACE_DUERGAR, CLASS_CONJURER,    SPEC_WATER},
	{RACE_DUERGAR, CLASS_CONJURER,    SPEC_EARTH},
	{RACE_DUERGAR, CLASS_ROGUE,         SPEC_THIEF},
	{RACE_DUERGAR, CLASS_ROGUE,         SPEC_ASSASSIN},
	{RACE_DUERGAR, CLASS_MERCENARY,     SPEC_ALL},
	{RACE_DUERGAR, CLASS_BARD,          SPEC_ALL},
	{RACE_DUERGAR, CLASS_BERSERKER,     SPEC_ALL},
	{RACE_DUERGAR, CLASS_REAVER,        SPEC_ICE_REAVER}, 
        {RACE_DUERGAR, CLASS_REAVER,        SPEC_SHOCK_REAVER},
        {RACE_DUERGAR, CLASS_REAVER,        SPEC_FLAME_REAVER},
	{RACE_DUERGAR, CLASS_ETHERMANCER,   SPEC_ALL},
	{RACE_DUERGAR, CLASS_NECROMANCER,   SPEC_ALL},
       {RACE_DUERGAR, CLASS_MONK, 	    SPEC_ALL},
       {RACE_DUERGAR, CLASS_ILLUSIONIST,   SPEC_ALL},	

       /* End Duergar Dwarf Options */

	/* Start Halfling Options */
       {RACE_HALFLING, CLASS_WARRIOR,   SPEC_GUARDIAN},
	{RACE_HALFLING, CLASS_WARRIOR,   SPEC_SWORDSMAN},
	{RACE_HALFLING, CLASS_RANGER,      SPEC_ALL},
	{RACE_HALFLING, CLASS_PALADIN,     SPEC_ALL},
	{RACE_HALFLING, CLASS_CLERIC,      SPEC_ALL},
       {RACE_HALFLING, CLASS_ANTIPALADIN,    SPEC_ALL},
	{RACE_HALFLING, CLASS_DRUID,       SPEC_ALL},
	{RACE_HALFLING, CLASS_SHAMAN,      SPEC_ALL},
	{RACE_HALFLING, CLASS_SHAMAN,      SPEC_ALL},
	{RACE_HALFLING, CLASS_SORCERER,    SPEC_ALL},
	{RACE_HALFLING, CLASS_CONJURER,    SPEC_AIR},
	{RACE_HALFLING, CLASS_CONJURER,    SPEC_WATER},
	{RACE_HALFLING, CLASS_CONJURER,    SPEC_EARTH},
	{RACE_HALFLING, CLASS_ROGUE,       SPEC_THIEF},
	{RACE_HALFLING, CLASS_ROGUE,       SPEC_ASSASSIN},
	{RACE_HALFLING, CLASS_MERCENARY,   SPEC_ALL},
	{RACE_HALFLING, CLASS_BARD,        SPEC_ALL},
	{RACE_HALFLING, CLASS_BERSERKER,   SPEC_ALL},
	{RACE_HALFLING, CLASS_ILLUSIONIST, SPEC_ALL},
       {RACE_HALFLING, CLASS_CABALIST,    SPEC_ALL},
	{RACE_HALFLING, CLASS_ETHERMANCER, SPEC_ALL},
	{RACE_HALFLING, CLASS_THEURGIST,   SPEC_ALL},
 	{RACE_HALFLING, CLASS_MONK,        SPEC_ALL},
	{RACE_HALFLING, CLASS_NECROMANCER, SPEC_ALL},
       {RACE_HALFLING, CLASS_PSIONICIST,  SPEC_ALL},
	{RACE_HALFLING, CLASS_REAVER,        SPEC_ICE_REAVER}, 
        {RACE_HALFLING, CLASS_REAVER,        SPEC_SHOCK_REAVER},
        {RACE_HALFLING, CLASS_REAVER,        SPEC_FLAME_REAVER},
	/* End Halfling Options */

	/* Start Gnome Options */
       {RACE_GNOME, CLASS_WARRIOR,   SPEC_GUARDIAN},
	{RACE_GNOME, CLASS_WARRIOR,   SPEC_SWORDSMAN},
	{RACE_GNOME, CLASS_RANGER,      SPEC_ALL},
	{RACE_GNOME, CLASS_PALADIN,     SPEC_ALL},
	{RACE_GNOME, CLASS_CLERIC,      SPEC_ALL},
       {RACE_GNOME, CLASS_ANTIPALADIN,    SPEC_ALL},
	{RACE_GNOME, CLASS_DRUID,       SPEC_ALL},
	{RACE_GNOME, CLASS_SHAMAN,      SPEC_ALL},
	{RACE_GNOME, CLASS_SHAMAN,      SPEC_ALL},
	{RACE_GNOME, CLASS_SORCERER,    SPEC_ALL},
	{RACE_GNOME, CLASS_CONJURER,    SPEC_AIR},
	{RACE_GNOME, CLASS_CONJURER,    SPEC_WATER},
	{RACE_GNOME, CLASS_CONJURER,    SPEC_EARTH},
	{RACE_GNOME, CLASS_ROGUE,       SPEC_THIEF},
	{RACE_GNOME, CLASS_ROGUE,       SPEC_ASSASSIN},
	{RACE_GNOME, CLASS_MERCENARY,   SPEC_ALL},
	{RACE_GNOME, CLASS_BARD,        SPEC_ALL},
	{RACE_GNOME, CLASS_BERSERKER,   SPEC_ALL},
	{RACE_GNOME, CLASS_ILLUSIONIST, SPEC_ALL},
       {RACE_GNOME, CLASS_CABALIST,    SPEC_ALL},
	{RACE_GNOME, CLASS_ETHERMANCER, SPEC_ALL},
	{RACE_GNOME, CLASS_THEURGIST,   SPEC_ALL},
 	{RACE_GNOME, CLASS_MONK,        SPEC_ALL},
	{RACE_GNOME, CLASS_NECROMANCER, SPEC_ALL},
       {RACE_GNOME, CLASS_PSIONICIST,  SPEC_ALL},
	{RACE_GNOME, CLASS_REAVER,        SPEC_ICE_REAVER}, 
        {RACE_GNOME, CLASS_REAVER,        SPEC_SHOCK_REAVER},
        {RACE_GNOME, CLASS_REAVER,        SPEC_FLAME_REAVER},
	/* End Gnome Options */

	/* Start Ogre Options */
	{RACE_OGRE, CLASS_WARRIOR,   SPEC_GUARDIAN},
	{RACE_OGRE, CLASS_WARRIOR,   SPEC_SWORDSMAN},
	{RACE_OGRE, CLASS_ANTIPALADIN,   SPEC_ALL},
	{RACE_OGRE, CLASS_RANGER,      SPEC_ALL},
       {RACE_OGRE, CLASS_DRUID,         SPEC_ALL},
	{RACE_OGRE, CLASS_CLERIC,        SPEC_ALL},
	{RACE_OGRE, CLASS_SHAMAN,        SPEC_ALL},
	{RACE_OGRE, CLASS_PSIONICIST,      SPEC_ALL},
       {RACE_OGRE, CLASS_SORCERER,      SPEC_ALL},
	{RACE_OGRE, CLASS_CONJURER,    SPEC_AIR},
	{RACE_OGRE, CLASS_CONJURER,    SPEC_WATER},
	{RACE_OGRE, CLASS_CONJURER,    SPEC_EARTH},
	{RACE_OGRE, CLASS_ROGUE,         SPEC_THIEF},
	{RACE_OGRE, CLASS_ROGUE,         SPEC_ASSASSIN},
	{RACE_OGRE, CLASS_MERCENARY,     SPEC_ALL},
	{RACE_OGRE, CLASS_BARD,          SPEC_ALL},
	{RACE_OGRE, CLASS_BERSERKER,     SPEC_ALL},
	{RACE_OGRE, CLASS_REAVER,        SPEC_ICE_REAVER}, 
        {RACE_OGRE, CLASS_REAVER,        SPEC_SHOCK_REAVER},
        {RACE_OGRE, CLASS_REAVER,        SPEC_FLAME_REAVER},
	{RACE_OGRE, CLASS_ETHERMANCER,   SPEC_ALL},
	{RACE_OGRE, CLASS_NECROMANCER,   SPEC_ALL},
       {RACE_OGRE, CLASS_MONK, 	    SPEC_ALL},
       {RACE_OGRE, CLASS_ILLUSIONIST,   SPEC_ALL},

	/* End Ogre Options */

	/* Start Troll Options */
	{RACE_TROLL, CLASS_WARRIOR,   SPEC_GUARDIAN},
	{RACE_TROLL, CLASS_WARRIOR,   SPEC_SWORDSMAN},
	{RACE_TROLL, CLASS_ANTIPALADIN,   SPEC_ALL},
	{RACE_TROLL, CLASS_RANGER,      SPEC_ALL},
       {RACE_TROLL, CLASS_DRUID,         SPEC_ALL},
	{RACE_TROLL, CLASS_CLERIC,        SPEC_ALL},
	{RACE_TROLL, CLASS_SHAMAN,        SPEC_ALL},
	{RACE_TROLL, CLASS_PSIONICIST,      SPEC_ALL},
       {RACE_TROLL, CLASS_SORCERER,      SPEC_ALL},
	{RACE_TROLL, CLASS_CONJURER,    SPEC_AIR},
	{RACE_TROLL, CLASS_CONJURER,    SPEC_WATER},
	{RACE_TROLL, CLASS_CONJURER,    SPEC_EARTH},
	{RACE_TROLL, CLASS_ROGUE,         SPEC_THIEF},
	{RACE_TROLL, CLASS_ROGUE,         SPEC_ASSASSIN},
	{RACE_TROLL, CLASS_MERCENARY,     SPEC_ALL},
	{RACE_TROLL, CLASS_BARD,          SPEC_ALL},
	{RACE_TROLL, CLASS_BERSERKER,     SPEC_ALL},
	{RACE_TROLL, CLASS_REAVER,        SPEC_ICE_REAVER}, 
        {RACE_TROLL, CLASS_REAVER,        SPEC_SHOCK_REAVER},
        {RACE_TROLL, CLASS_REAVER,        SPEC_FLAME_REAVER},
	{RACE_TROLL, CLASS_ETHERMANCER,   SPEC_ALL},
	{RACE_TROLL, CLASS_NECROMANCER,   SPEC_ALL},
       {RACE_TROLL, CLASS_MONK, 	    SPEC_ALL},
       {RACE_TROLL, CLASS_ILLUSIONIST,   SPEC_ALL},
>>>>>>> master
	/* End Troll Options */

	/* Start Half-Elf Options */
/*	{RACE_HALFELF, CLASS_WARRIOR,     SPEC_GUARDIAN},
	{RACE_HALFELF, CLASS_WARRIOR,     SPEC_SWASHBUCKLER},
	{RACE_HALFELF, CLASS_RANGER,      SPEC_BLADEMASTER},
	{RACE_HALFELF, CLASS_PALADIN,     SPEC_ALL},
	{RACE_HALFELF, CLASS_CLERIC,      SPEC_ZEALOT},
	{RACE_HALFELF, CLASS_DRUID,       SPEC_STORM},
	{RACE_HALFELF, CLASS_SORCERER,    SPEC_ALL},
	{RACE_HALFELF, CLASS_CONJURER,    SPEC_AIR},
	{RACE_HALFELF, CLASS_CONJURER,    SPEC_WATER},
	{RACE_HALFELF, CLASS_ROGUE,       SPEC_ALL},
	{RACE_HALFELF, CLASS_MERCENARY,   SPEC_BRIGAND},
	{RACE_HALFELF, CLASS_BARD,        SPEC_ALL},
	{RACE_HALFELF, CLASS_ILLUSIONIST, SPEC_ALL},
	{RACE_HALFELF, CLASS_THEURGIST,   SPEC_TEMPLAR},
	{RACE_HALFELF, CLASS_THEURGIST,   SPEC_THAUMATURGE},
*/	/* End Half-Elf Options */

	/* Start Orc Options */
<<<<<<< HEAD
	{RACE_ORC, CLASS_WARRIOR,       SPEC_ALL},
	{RACE_ORC, CLASS_ANTIPALADIN,   SPEC_DEMONIC},
	{RACE_ORC, CLASS_CLERIC,        SPEC_ZEALOT},
	{RACE_ORC, CLASS_SORCERER,      SPEC_ALL},
	{RACE_ORC, CLASS_NECROMANCER,   SPEC_ALL},
	{RACE_ORC, CLASS_CONJURER,      SPEC_ALL},
=======
	{RACE_ORC, CLASS_WARRIOR,   SPEC_GUARDIAN},
	{RACE_ORC, CLASS_WARRIOR,   SPEC_SWORDSMAN},
	{RACE_ORC, CLASS_ANTIPALADIN,   SPEC_ALL},
	{RACE_ORC, CLASS_RANGER,      SPEC_ALL},
       {RACE_ORC, CLASS_DRUID,         SPEC_ALL},
	{RACE_ORC, CLASS_CLERIC,        SPEC_ALL},
	{RACE_ORC, CLASS_SHAMAN,        SPEC_ALL},
	{RACE_ORC, CLASS_PSIONICIST,      SPEC_ALL},
       {RACE_ORC, CLASS_SORCERER,      SPEC_ALL},
	{RACE_ORC, CLASS_CONJURER,    SPEC_AIR},
	{RACE_ORC, CLASS_CONJURER,    SPEC_WATER},
	{RACE_ORC, CLASS_CONJURER,    SPEC_EARTH},
>>>>>>> master
	{RACE_ORC, CLASS_ROGUE,         SPEC_THIEF},
	{RACE_ORC, CLASS_ROGUE,         SPEC_ASSASSIN},
	{RACE_ORC, CLASS_MERCENARY,     SPEC_BRIGAND},
	{RACE_ORC, CLASS_BARD,          SPEC_ALL},
	{RACE_ORC, CLASS_REAVER,        SPEC_ICE_REAVER}, 
        {RACE_ORC, CLASS_REAVER,        SPEC_SHOCK_REAVER},
<<<<<<< HEAD
	{RACE_ORC, CLASS_ILLUSIONIST,   SPEC_MAGICIAN},
        {RACE_ORC, CLASS_CABALIST,      SPEC_ALL},
=======
        {RACE_ORC, CLASS_REAVER,        SPEC_FLAME_REAVER},
	{RACE_ORC, CLASS_ETHERMANCER,   SPEC_ALL},
	{RACE_ORC, CLASS_NECROMANCER,   SPEC_ALL},
       {RACE_ORC, CLASS_MONK, 	    SPEC_ALL},
       {RACE_ORC, CLASS_ILLUSIONIST,   SPEC_ALL},
>>>>>>> master
	/* End Orc Options */

	/* Start Thri-Kreen Options */
	{RACE_THRIKREEN, CLASS_WARRIOR, SPEC_SWORDSMAN},
        {RACE_THRIKREEN, CLASS_CLERIC,  SPEC_HOLYMAN},
	/* End Thri-Kreen Options */

	/* Start Centaur Options */
<<<<<<< HEAD
	{RACE_CENTAUR, CLASS_WARRIOR,     SPEC_SWORDSMAN},
	{RACE_CENTAUR, CLASS_RANGER,      SPEC_MARSHALL},
	{RACE_CENTAUR, CLASS_DRUID,       SPEC_STORM},
	{RACE_CENTAUR, CLASS_SHAMAN,      SPEC_ANIMALIST},
=======
       {RACE_CENTAUR, CLASS_WARRIOR,   SPEC_GUARDIAN},
	{RACE_CENTAUR, CLASS_WARRIOR,   SPEC_SWORDSMAN},
	{RACE_CENTAUR, CLASS_RANGER,      SPEC_ALL},
	{RACE_CENTAUR, CLASS_PALADIN,     SPEC_ALL},
	{RACE_CENTAUR, CLASS_CLERIC,      SPEC_ALL},
       {RACE_CENTAUR, CLASS_ANTIPALADIN,    SPEC_ALL},
	{RACE_CENTAUR, CLASS_DRUID,       SPEC_ALL},
	{RACE_CENTAUR, CLASS_SHAMAN,      SPEC_ALL},
	{RACE_CENTAUR, CLASS_SHAMAN,      SPEC_ALL},
	{RACE_CENTAUR, CLASS_SORCERER,    SPEC_ALL},
	{RACE_CENTAUR, CLASS_CONJURER,    SPEC_AIR},
	{RACE_CENTAUR, CLASS_CONJURER,    SPEC_WATER},
	{RACE_CENTAUR, CLASS_CONJURER,    SPEC_EARTH},
	{RACE_CENTAUR, CLASS_ROGUE,       SPEC_THIEF},
	{RACE_CENTAUR, CLASS_ROGUE,       SPEC_ASSASSIN},
	{RACE_CENTAUR, CLASS_MERCENARY,   SPEC_ALL},
	{RACE_CENTAUR, CLASS_BARD,        SPEC_ALL},
	{RACE_CENTAUR, CLASS_BERSERKER,   SPEC_ALL},
	{RACE_CENTAUR, CLASS_ILLUSIONIST, SPEC_ALL},
       {RACE_CENTAUR, CLASS_CABALIST,    SPEC_ALL},
	{RACE_CENTAUR, CLASS_ETHERMANCER, SPEC_ALL},
	{RACE_CENTAUR, CLASS_THEURGIST,   SPEC_ALL},
 	{RACE_CENTAUR, CLASS_MONK,        SPEC_ALL},
	{RACE_CENTAUR, CLASS_NECROMANCER, SPEC_ALL},
       {RACE_CENTAUR, CLASS_PSIONICIST,  SPEC_ALL},
	{RACE_CENTAUR, CLASS_REAVER,        SPEC_ICE_REAVER}, 
        {RACE_CENTAUR, CLASS_REAVER,        SPEC_SHOCK_REAVER},
        {RACE_CENTAUR, CLASS_REAVER,        SPEC_FLAME_REAVER},
>>>>>>> master
	/* End Centaur Options */

       /* Start Firbolg Options */
       {RACE_FIRBOLG, CLASS_WARRIOR,   SPEC_GUARDIAN},
	{RACE_FIRBOLG, CLASS_WARRIOR,   SPEC_SWORDSMAN},
	{RACE_FIRBOLG, CLASS_RANGER,      SPEC_ALL},
	{RACE_FIRBOLG, CLASS_PALADIN,     SPEC_ALL},
	{RACE_FIRBOLG, CLASS_CLERIC,      SPEC_ALL},
       {RACE_FIRBOLG, CLASS_ANTIPALADIN,    SPEC_ALL},
	{RACE_FIRBOLG, CLASS_DRUID,       SPEC_ALL},
	{RACE_FIRBOLG, CLASS_SHAMAN,      SPEC_ALL},
	{RACE_FIRBOLG, CLASS_SHAMAN,      SPEC_ALL},
	{RACE_FIRBOLG, CLASS_SORCERER,    SPEC_ALL},
	{RACE_FIRBOLG, CLASS_CONJURER,    SPEC_AIR},
	{RACE_FIRBOLG, CLASS_CONJURER,    SPEC_WATER},
	{RACE_FIRBOLG, CLASS_CONJURER,    SPEC_EARTH},
	{RACE_FIRBOLG, CLASS_ROGUE,       SPEC_THIEF},
	{RACE_FIRBOLG, CLASS_ROGUE,       SPEC_ASSASSIN},
	{RACE_FIRBOLG, CLASS_MERCENARY,   SPEC_ALL},
	{RACE_FIRBOLG, CLASS_BARD,        SPEC_ALL},
	{RACE_FIRBOLG, CLASS_BERSERKER,   SPEC_ALL},
	{RACE_FIRBOLG, CLASS_ILLUSIONIST, SPEC_ALL},
       {RACE_FIRBOLG, CLASS_CABALIST,    SPEC_ALL},
	{RACE_FIRBOLG, CLASS_ETHERMANCER, SPEC_ALL},
	{RACE_FIRBOLG, CLASS_THEURGIST,   SPEC_ALL},
 	{RACE_FIRBOLG, CLASS_MONK,        SPEC_ALL},
	{RACE_FIRBOLG, CLASS_NECROMANCER, SPEC_ALL},
       {RACE_FIRBOLG, CLASS_PSIONICIST,  SPEC_ALL},
	{RACE_FIRBOLG, CLASS_REAVER,        SPEC_ICE_REAVER}, 
        {RACE_FIRBOLG, CLASS_REAVER,        SPEC_SHOCK_REAVER},
        {RACE_FIRBOLG, CLASS_REAVER,        SPEC_FLAME_REAVER},

	/* Start Githyanki Options */
<<<<<<< HEAD
	{RACE_GITHYANKI, CLASS_PSIONICIST,  SPEC_ALL},
	{RACE_GITHYANKI, CLASS_ANTIPALADIN, SPEC_KNIGHT},
	{RACE_GITHYANKI, CLASS_SORCERER,    SPEC_WILDMAGE},
        {RACE_GITHYANKI, CLASS_ROGUE,       SPEC_ASSASSIN},
	{RACE_GITHYANKI, CLASS_REAVER,      SPEC_ICE_REAVER},
	{RACE_GITHYANKI, CLASS_REAVER,      SPEC_FLAME_REAVER},
        {RACE_GITHYANKI, CLASS_BARD,        SPEC_DISHARMONIST},
	/* End Githyanki Options */
=======
	{RACE_GITHYANKI, CLASS_WARRIOR,   SPEC_GUARDIAN},
	{RACE_GITHYANKI, CLASS_WARRIOR,   SPEC_SWORDSMAN},
	{RACE_GITHYANKI, CLASS_ANTIPALADIN,   SPEC_ALL},
	{RACE_GITHYANKI, CLASS_RANGER,      SPEC_ALL},
       {RACE_GITHYANKI, CLASS_DRUID,         SPEC_ALL},
	{RACE_GITHYANKI, CLASS_CLERIC,        SPEC_ALL},
	{RACE_GITHYANKI, CLASS_SHAMAN,        SPEC_ALL},
	{RACE_GITHYANKI, CLASS_PSIONICIST,      SPEC_ALL},
       {RACE_GITHYANKI, CLASS_SORCERER,      SPEC_ALL},
	{RACE_GITHYANKI, CLASS_CONJURER,    SPEC_AIR},
	{RACE_GITHYANKI, CLASS_CONJURER,    SPEC_WATER},
	{RACE_GITHYANKI, CLASS_CONJURER,    SPEC_EARTH},
	{RACE_GITHYANKI, CLASS_ROGUE,         SPEC_THIEF},
	{RACE_GITHYANKI, CLASS_ROGUE,         SPEC_ASSASSIN},
	{RACE_GITHYANKI, CLASS_MERCENARY,     SPEC_ALL},
	{RACE_GITHYANKI, CLASS_BARD,          SPEC_ALL},
	{RACE_GITHYANKI, CLASS_BERSERKER,     SPEC_ALL},
	{RACE_GITHYANKI, CLASS_REAVER,        SPEC_ICE_REAVER}, 
        {RACE_GITHYANKI, CLASS_REAVER,        SPEC_SHOCK_REAVER},
        {RACE_GITHYANKI, CLASS_REAVER,        SPEC_FLAME_REAVER},
	{RACE_GITHYANKI, CLASS_ETHERMANCER,   SPEC_ALL},
	{RACE_GITHYANKI, CLASS_NECROMANCER,   SPEC_ALL},
       {RACE_GITHYANKI, CLASS_MONK, 	    SPEC_ALL},
       {RACE_GITHYANKI, CLASS_ILLUSIONIST,   SPEC_ALL},

        /* End Githyanki Options */
>>>>>>> master

	/* Start Minotaur Options */
	{RACE_MINOTAUR, CLASS_WARRIOR,   SPEC_GUARDIAN},
	{RACE_MINOTAUR, CLASS_WARRIOR,   SPEC_SWORDSMAN},
<<<<<<< HEAD
	{RACE_MINOTAUR, CLASS_MERCENARY, SPEC_ALL},
	{RACE_MINOTAUR, CLASS_BERSERKER, SPEC_ALL},
        {RACE_MINOTAUR, CLASS_SORCERER,  SPEC_WILDMAGE},
	/* End Minotaur Options */

	/* Start Goblin Options */
	{RACE_GOBLIN, CLASS_CLERIC,      SPEC_HOLYMAN},
	{RACE_GOBLIN, CLASS_BARD,        SPEC_SCOUNDREL},
        {RACE_GOBLIN, CLASS_ILLUSIONIST, SPEC_DARK_DREAMER},
        {RACE_GOBLIN, CLASS_CONJURER,    SPEC_FIRE},
        {RACE_GOBLIN, CLASS_CONJURER,    SPEC_WATER},
        {RACE_GOBLIN, CLASS_SORCERER,    SPEC_WILDMAGE},
        {RACE_GOBLIN, CLASS_SORCERER,    SPEC_SHADOW},
	{RACE_GOBLIN, CLASS_ROGUE,       SPEC_THIEF},
	{RACE_GOBLIN, CLASS_ROGUE,       SPEC_ASSASSIN},
=======
	{RACE_MINOTAUR, CLASS_ANTIPALADIN,   SPEC_ALL},
       {RACE_MINOTAUR, CLASS_DRUID,         SPEC_ALL},
	{RACE_MINOTAUR, CLASS_RANGER,      SPEC_ALL},
	{RACE_MINOTAUR, CLASS_CLERIC,        SPEC_ALL},
	{RACE_MINOTAUR, CLASS_SHAMAN,        SPEC_ALL},
	{RACE_MINOTAUR, CLASS_PSIONICIST,      SPEC_ALL},
       {RACE_MINOTAUR, CLASS_SORCERER,      SPEC_ALL},
	{RACE_MINOTAUR, CLASS_CONJURER,    SPEC_AIR},
	{RACE_MINOTAUR, CLASS_CONJURER,    SPEC_WATER},
       {RACE_MINOTAUR, CLASS_PALADIN,	SPEC_ALL},
	{RACE_MINOTAUR, CLASS_CONJURER,    SPEC_EARTH},
	{RACE_MINOTAUR, CLASS_ROGUE,         SPEC_THIEF},
	{RACE_MINOTAUR, CLASS_ROGUE,         SPEC_ASSASSIN},
	{RACE_MINOTAUR, CLASS_MERCENARY,     SPEC_ALL},
	{RACE_MINOTAUR, CLASS_BARD,          SPEC_ALL},
	{RACE_MINOTAUR, CLASS_BERSERKER,     SPEC_ALL},
	{RACE_MINOTAUR, CLASS_ETHERMANCER,   SPEC_ALL},
	{RACE_MINOTAUR, CLASS_NECROMANCER,   SPEC_ALL},
       {RACE_MINOTAUR, CLASS_MONK, 	    SPEC_ALL},
       {RACE_MINOTAUR, CLASS_ILLUSIONIST,   SPEC_ALL},
	{RACE_MINOTAUR, CLASS_REAVER,        SPEC_ICE_REAVER}, 
        {RACE_MINOTAUR, CLASS_REAVER,        SPEC_SHOCK_REAVER},
        {RACE_MINOTAUR, CLASS_REAVER,        SPEC_FLAME_REAVER},
   	/* End Minotaur Options */

	/* Start Goblin Options */
	{RACE_GOBLIN, CLASS_WARRIOR,   SPEC_GUARDIAN},
	{RACE_GOBLIN, CLASS_WARRIOR,   SPEC_SWORDSMAN},
	{RACE_GOBLIN, CLASS_ANTIPALADIN,   SPEC_ALL},
	{RACE_GOBLIN, CLASS_RANGER,      SPEC_ALL},
       {RACE_GOBLIN, CLASS_DRUID,         SPEC_ALL},
	{RACE_GOBLIN, CLASS_CLERIC,        SPEC_ALL},
	{RACE_GOBLIN, CLASS_SHAMAN,        SPEC_ALL},
	{RACE_GOBLIN, CLASS_PSIONICIST,      SPEC_ALL},
       {RACE_GOBLIN, CLASS_SORCERER,      SPEC_ALL},
	{RACE_GOBLIN, CLASS_CONJURER,    SPEC_AIR},
	{RACE_GOBLIN, CLASS_CONJURER,    SPEC_WATER},
	{RACE_GOBLIN, CLASS_CONJURER,    SPEC_EARTH},
	{RACE_GOBLIN, CLASS_ROGUE,         SPEC_THIEF},
	{RACE_GOBLIN, CLASS_ROGUE,         SPEC_ASSASSIN},
	{RACE_GOBLIN, CLASS_MERCENARY,     SPEC_ALL},
	{RACE_GOBLIN, CLASS_BARD,          SPEC_ALL},
	{RACE_GOBLIN, CLASS_BERSERKER,     SPEC_ALL},
	{RACE_GOBLIN, CLASS_REAVER,        SPEC_ICE_REAVER}, 
        {RACE_GOBLIN, CLASS_REAVER,        SPEC_SHOCK_REAVER},
        {RACE_GOBLIN, CLASS_REAVER,        SPEC_FLAME_REAVER},
	{RACE_GOBLIN, CLASS_ETHERMANCER,   SPEC_ALL},
	{RACE_GOBLIN, CLASS_NECROMANCER,   SPEC_ALL},
       {RACE_GOBLIN, CLASS_MONK, 	    SPEC_ALL},
       {RACE_GOBLIN, CLASS_ILLUSIONIST,   SPEC_ALL},
>>>>>>> master
	/* End Goblin Options */

	/* Start Lich Options */
	{RACE_PLICH, CLASS_NECROMANCER, SPEC_ALL},
	/* End Lich Options */

	/* Start Vampire Options */
	//{RACE_PVAMPIRE, CLASS_DREADLORD, SPEC_ALL},
	/* End Vampire Options */

	/* Start Githzerai Options */
<<<<<<< HEAD
	{RACE_GITHZERAI, CLASS_SORCERER, SPEC_WILDMAGE},
	{RACE_GITHZERAI, CLASS_ROGUE,    SPEC_ASSASSIN},
	{RACE_GITHZERAI, CLASS_CONJURER, SPEC_ALL},
	{RACE_GITHZERAI, CLASS_SORCERER, SPEC_MAGICIAN},
=======
       {RACE_GITHZERAI, CLASS_WARRIOR,   SPEC_GUARDIAN},
	{RACE_GITHZERAI, CLASS_WARRIOR,   SPEC_SWORDSMAN},
	{RACE_GITHZERAI, CLASS_RANGER,      SPEC_ALL},
	{RACE_GITHZERAI, CLASS_PALADIN,     SPEC_ALL},
	{RACE_GITHZERAI, CLASS_CLERIC,      SPEC_ALL},
       {RACE_GITHZERAI, CLASS_ANTIPALADIN,    SPEC_ALL},
	{RACE_GITHZERAI, CLASS_DRUID,       SPEC_ALL},
	{RACE_GITHZERAI, CLASS_SHAMAN,      SPEC_ALL},
	{RACE_GITHZERAI, CLASS_SHAMAN,      SPEC_ALL},
	{RACE_GITHZERAI, CLASS_SORCERER,    SPEC_ALL},
	{RACE_GITHZERAI, CLASS_CONJURER,    SPEC_AIR},
	{RACE_GITHZERAI, CLASS_CONJURER,    SPEC_WATER},
	{RACE_GITHZERAI, CLASS_CONJURER,    SPEC_EARTH},
	{RACE_GITHZERAI, CLASS_ROGUE,       SPEC_THIEF},
	{RACE_GITHZERAI, CLASS_ROGUE,       SPEC_ASSASSIN},
	{RACE_GITHZERAI, CLASS_MERCENARY,   SPEC_ALL},
	{RACE_GITHZERAI, CLASS_BARD,        SPEC_ALL},
	{RACE_GITHZERAI, CLASS_BERSERKER,   SPEC_ALL},
	{RACE_GITHZERAI, CLASS_ILLUSIONIST, SPEC_ALL},
       {RACE_GITHZERAI, CLASS_CABALIST,    SPEC_ALL},
	{RACE_GITHZERAI, CLASS_ETHERMANCER, SPEC_ALL},
	{RACE_GITHZERAI, CLASS_THEURGIST,   SPEC_ALL},
 	{RACE_GITHZERAI, CLASS_MONK,        SPEC_ALL},
	{RACE_GITHZERAI, CLASS_NECROMANCER, SPEC_ALL},
       {RACE_GITHZERAI, CLASS_PSIONICIST,  SPEC_ALL},
	{RACE_GITHZERAI, CLASS_REAVER,        SPEC_ICE_REAVER}, 
        {RACE_GITHZERAI, CLASS_REAVER,        SPEC_SHOCK_REAVER},
        {RACE_GITHZERAI, CLASS_REAVER,        SPEC_FLAME_REAVER},
>>>>>>> master
	/* End Githzerai Options */

	/* Start Drider Options */
/*	{RACE_DRIDER, CLASS_WARRIOR, SPEC_SWORDSMAN},
	{RACE_DRIDER, CLASS_SORCERER, SPEC_SHADOW},
	{RACE_DRIDER, CLASS_REAVER, SPEC_ICE_REAVER}, 
        {RACE_DRIDER, CLASS_REAVER, SPEC_FLAME_REAVER}, 
        {RACE_DRIDER, CLASS_REAVER, SPEC_SHOCK_REAVER},
*/	/* End Drider Options */

	/* Start Agathinon Options */
	//{RACE_AGATHINON, CLASS_AVENGER, SPEC_ALL},
	/* End Agathinon Options */

	/* Start Eladrin Options */
	//{RACE_ELADRIN, CLASS_THEURGIST, SPEC_ALL},
	/* End Eladrin Options */

	/* Start Kobold Options */
	{RACE_KOBOLD, CLASS_WARRIOR,   SPEC_GUARDIAN},
	{RACE_KOBOLD, CLASS_WARRIOR,   SPEC_SWORDSMAN},
	{RACE_KOBOLD, CLASS_ANTIPALADIN,   SPEC_ALL},
	{RACE_KOBOLD, CLASS_RANGER,      SPEC_ALL},
       {RACE_KOBOLD, CLASS_DRUID,         SPEC_ALL},
	{RACE_KOBOLD, CLASS_CLERIC,        SPEC_ALL},
	{RACE_KOBOLD, CLASS_SHAMAN,        SPEC_ALL},
	{RACE_KOBOLD, CLASS_PSIONICIST,      SPEC_ALL},
       {RACE_KOBOLD, CLASS_SORCERER,      SPEC_ALL},
	{RACE_KOBOLD, CLASS_CONJURER,    SPEC_AIR},
	{RACE_KOBOLD, CLASS_CONJURER,    SPEC_WATER},
	{RACE_KOBOLD, CLASS_CONJURER,    SPEC_EARTH},
	{RACE_KOBOLD, CLASS_ROGUE,         SPEC_THIEF},
	{RACE_KOBOLD, CLASS_ROGUE,         SPEC_ASSASSIN},
	{RACE_KOBOLD, CLASS_MERCENARY,     SPEC_ALL},
	{RACE_KOBOLD, CLASS_BARD,          SPEC_ALL},
	{RACE_KOBOLD, CLASS_BERSERKER,     SPEC_ALL},
	{RACE_KOBOLD, CLASS_REAVER,        SPEC_ICE_REAVER}, 
        {RACE_KOBOLD, CLASS_REAVER,        SPEC_SHOCK_REAVER},
        {RACE_KOBOLD, CLASS_REAVER,        SPEC_FLAME_REAVER},
	{RACE_KOBOLD, CLASS_ETHERMANCER,   SPEC_ALL},
	{RACE_KOBOLD, CLASS_NECROMANCER,   SPEC_ALL},
       {RACE_KOBOLD, CLASS_MONK, 	    SPEC_ALL},
       {RACE_KOBOLD, CLASS_ILLUSIONIST,   SPEC_ALL},
	/* End Kobold Options */

	/* Start Illithid Options */
	//{RACE_PILLITHID, CLASS_WARRIOR,     SPEC_SWORDSMAN},
/*	{RACE_PILLITHID, CLASS_PSIONICIST,  SPEC_ALL},
	{RACE_PILLITHID, CLASS_SORCERER,    SPEC_SHADOW},
	{RACE_PILLITHID, CLASS_SORCERER,    SPEC_WIZARD},
	{RACE_PILLITHID, CLASS_CONJURER,    SPEC_AIR},
	{RACE_PILLITHID, CLASS_CONJURER,    SPEC_WATER},
	//{RACE_PILLITHID, CLASS_ILLUSIONIST, SPEC_DARK_DREAMER},
	//{RACE_PILLITHID, CLASS_ILLUSIONIST, SPEC_MAGICIAN},
	//{RACE_PILLITHID, CLASS_ETHERMANCER, SPEC_COSMOMANCER},
*/	/* End Illithid Options */

	/* Start Kuo Toa Options */
/*	{RACE_KUOTOA, CLASS_WARRIOR, SPEC_GUARDIAN},
	{RACE_KUOTOA, CLASS_WARRIOR, SPEC_SWORDSMAN},
	{RACE_KUOTOA, CLASS_CLERIC,  SPEC_ZEALOT},
	{RACE_KUOTOA, CLASS_SHAMAN,  SPEC_ELEMENTALIST},
	{RACE_KUOTOA, CLASS_ROGUE,   SPEC_ASSASSIN},
*/	/* End Kuo Toa Options */

	/* Start Wood Elf Options */
/*	{RACE_WOODELF, CLASS_WARRIOR, SPEC_GUARDIAN},
	{RACE_WOODELF, CLASS_WARRIOR, SPEC_SWORDSMAN},
	{RACE_WOODELF, CLASS_RANGER,  SPEC_ALL},
	{RACE_WOODELF, CLASS_DRUID,   SPEC_FOREST},
	{RACE_WOODELF, CLASS_ROGUE,   SPEC_ASSASSIN},
	{RACE_WOODELF, CLASS_ROGUE,   SPEC_THIEF},
*/	/* End Wood Elf Options */
	
<<<<<<< HEAD
	/* Start Firbolg Options */
	{RACE_FIRBOLG, CLASS_WARRIOR,   SPEC_SWORDSMAN},
	{RACE_FIRBOLG, CLASS_DRUID,     SPEC_FOREST},
	{RACE_FIRBOLG, CLASS_MERCENARY, SPEC_BOUNTY},
      
        /* Start Harpy Options */
        {RACE_HARPY, CLASS_ETHERMANCER, SPEC_ALL},

	{0}
=======
	
	//{0}
>>>>>>> master
};

bool is_allowed_race_spec(int race, uint m_class, int spec)
{
  for( int i = 0; allowed_race_specs[i].race; i++ )
  {
    if( allowed_race_specs[i].race == race &&
        allowed_race_specs[i].m_class == m_class &&
        (allowed_race_specs[i].spec == SPEC_ALL ||
         allowed_race_specs[i].spec == spec ) )
    {
      return TRUE;
    }
  }
  return FALSE;
}

bool append_valid_specs(char *buf, P_char ch)
{
  if( !ch )
    return false;
  
  bool found_one = false;
  for (int i = 0; i < MAX_SPEC; i++)
  {
    if ( *GET_SPEC_NAME(ch->player.m_class, i) && 
         is_allowed_race_spec(GET_RACE(ch), ch->player.m_class, i+1) )
    {
      strcat(buf, GET_SPEC_NAME(ch->player.m_class, i));
      strcat(buf, "\r\n");
      found_one = true;
    }
  }
  
  return found_one;  
}

string single_spec_list(int race, int cls)
{
  int spec, comma = 0;
  string return_str;

  for (spec = 0; spec < MAX_SPEC; spec++)
  {
    if (!strcmp(specdata[cls][spec], "") ||
        !strcmp(specdata[cls][spec], "Not Used"))
    {
      continue;
    }
    if (is_allowed_race_spec(race, 1 << (cls - 1), spec+1))
    {
      if (comma)
	return_str += "&n, ";
      else
	comma = 1;
	
      return_str += string(specdata[cls][spec]);
    }
  }

  return return_str;
}

void do_spec_list(P_char ch)
{
  char Gbuf[MAX_STRING_LENGTH], list[MAX_STRING_LENGTH];
  int race, cls, spec, comma, show;

  send_to_char("&+WCurrent list of specializations available:&n\n\n", ch);
  for (cls = 1; cls <= CLASS_COUNT; cls++)
  {
    for (spec = 0; spec < MAX_SPEC; spec++)
    {
      show = 0;
      if (strcmp(specdata[cls][spec], "") &&
	  strcmp(specdata[cls][spec], "Not Used"))
      {
	show = 1;
	break;
      }
    }
    if (show)
    {
      sprintf(Gbuf, "&+W*&n %s &+W*&n\n", class_names_table[cls].ansi);
      send_to_char(Gbuf, ch);
    }
    for (spec = 0; spec < MAX_SPEC; spec++)
    {
      if (strcmp(specdata[cls][spec], "") &&
	  strcmp(specdata[cls][spec], "Not Used"))
      {
        sprintf(list, "%s:", specdata[cls][spec]);
        comma = 0;
	for (race = 1; race <= RACE_PLAYER_MAX; race++)
        {
	  if (is_allowed_race_spec(race, 1 << (cls - 1), spec+1))
          {
            if (comma)
	    {
              sprintf(list + strlen(list), ", %s&n", race_names_table[race].ansi);
	    }
	    else
	    {
              comma = 1;
	      sprintf(list + strlen(list), " %s&n", race_names_table[race].ansi);
	    }
	  }
          continue;
	}
        send_to_char(list, ch);
        send_to_char("\n", ch);
      }
      continue;
    }
    if (show)
    {
      send_to_char("\n", ch);
    }
    continue;
  }
}

void do_specialize(P_char ch, char *argument, int cmd)
{
  P_char teacher;
  int      i;
  char     buf[MAX_STRING_LENGTH] = "";
  bool found_one;

  if (!strcmp(argument, "list"))
  {
    do_spec_list(ch);
    return;
  }

  if (IS_MULTICLASS_PC(ch)) {
    send_to_char("You have already chosen another path!\n", ch);
    return;
  }
  
  if (!*argument)
  {
    strcpy(buf, "You can choose from the following specializations:\n\r");
    
    found_one = append_valid_specs(buf, ch);;
    
    if( !found_one )
    {
      send_to_char("There are no specializations available to you.\r\n", ch);
      return;      
    }

    send_to_char(buf, ch);
    return;
  }
  
  for (teacher = world[ch->in_room].people; teacher; teacher = teacher->next_in_room)
    if (IS_NPC(teacher) && GET_CLASS(teacher, ch->player.m_class) &&
        IS_SET(teacher->specials.act, ACT_SPEC_TEACHER))
      break;
  
  if (!teacher) {
    send_to_char("You need to find a teacher first.\n", ch);
    return;
  }
  
  if (IS_NPC(ch))
  {
    mobsay(teacher, "Please stop trying to crash the game by ordering pets to specialize.");
    return;
  }
  
  if (teacher->player.m_class != ch->player.m_class)
  {
    mobsay(teacher, "I know nothing of your kind. Be gone.");
    return;
  }
  
  if (IS_SPECIALIZED(ch))
  {
    mobsay(teacher, "You are already specialized.");
    return;
  }
  
  char     tmp[512];
  
  while (*argument == ' ')
    argument++;
  
  if (time(NULL) < ch->only.pc->time_unspecced)
  {
    sprintf(buf, "You cannot specialize until %s.\r\n",
            asctime(localtime(&ch->only.pc->time_unspecced)));
    send_to_char(buf, ch);
    return;
  }
  
  if (GET_LEVEL(ch) < 30)
  {
    mobsay(teacher, "You are not yet experienced enough to specialize.");
    return;
  }
  
  for (i = 0; i < MAX_SPEC; i++)
  {
    if( !*GET_SPEC_NAME(ch->player.m_class, i))
      continue;
    
    if( !is_allowed_race_spec(GET_RACE(ch), ch->player.m_class, i+1) )
      continue;
    
    if( is_abbrev( argument, strip_ansi(GET_SPEC_NAME(ch->player.m_class, i)).c_str()) )
    {
      sprintf(buf, "From this day onwards you will follow the path of the %s&n!", GET_SPEC_NAME(ch->player.m_class, i));
      ch->player.spec = i+1;
      update_skills(ch);
      mobsay(teacher, buf);
      return;
    }    
  }
  
  mobsay(teacher, "I'm sorry, but that specialization isn't available to you.");
}

void unspecialize(P_char ch, P_obj obj)
{
  if (!IS_SPECIALIZED(ch)) {
    send_to_char("You pray to the &+bWater Goddess&n but you get no response.",
                 ch);
  } if (epic_skillpoints(ch) < 1) {
    send_to_char("You need one practice point to pay for this.\n", ch);
  } else {
    act("You kneel in front of $p and pray to the \n"
        "&+bWater Goddess&n. As you continue your meditation, you begin\n"
        "to feel your mind is breaking free from the old habits and you\n"
        "feel ready to learn new ways.\n", FALSE, ch, obj, 0, TO_CHAR);
    act("$n kneels before $p and sinks in prayers.\n"
        "After few moments of silence $e smiles and stands up looking reborn.\n", FALSE, ch, obj, 0, TO_ROOM);
    ch->player.spec = 0;
    update_skills(ch);
    epic_gain_skillpoints(ch, -1);
    forget_spells(ch, -1);
  }
}
