/**************************************************************************
 *  file: spells.h , Implementation of magic spells.                       *
 *  Usage : Spells                                                         *
 ************************************************************************* */

#ifndef _SOJ_SPELLS_H_
#define _SOJ_SPELLS_H_

#define TYPE_UNDEFINED               -1
#define SPELL_RESERVED_DBC            0 /* SKILL NUMBER ZERO */
#define SKILL_NONE                    0

#define FIRST_SPELL                   1
#define SPELL_ARMOR                   1
#define SPELL_TELEPORT                2
#define SPELL_BLESS                   3
#define SPELL_BLINDNESS               4
#define SPELL_BURNING_HANDS           5
#define SPELL_CALL_LIGHTNING          6
#define SPELL_CHARM_PERSON            7
#define SPELL_CHILL_TOUCH             8
#define SPELL_FULL_HEAL               9
#define SPELL_CONE_OF_COLD           10
#define SPELL_CONTROL_WEATHER        11
#define SPELL_CREATE_FOOD            12
#define SPELL_CREATE_WATER           13
#define SPELL_CURE_BLIND             14
#define SPELL_CURE_CRITIC            15
#define SPELL_CURE_LIGHT             16
#define SPELL_CURSE                  17
#define SPELL_CONTINUAL_LIGHT        18
#define SPELL_DETECT_INVISIBLE       19
#define SPELL_MINOR_CREATION         20
#define SPELL_FLAMESTRIKE            21
#define SPELL_DISPEL_EVIL            22
#define SPELL_EARTHQUAKE             23
#define SPELL_ENCHANT_WEAPON         24
#define SPELL_ENERGY_DRAIN           25
#define SPELL_FIREBALL               26
#define SPELL_HARM                   27
#define SPELL_HEAL                   28
#define SPELL_INVISIBLE              29
#define SPELL_LIGHTNING_BOLT         30
#define SPELL_LOCATE_OBJECT          31
#define SPELL_MAGIC_MISSILE          32
#define SPELL_POISON                 33
#define SPELL_PROTECT_FROM_EVIL      34
#define SPELL_REMOVE_CURSE           35
#define SPELL_STONE_SKIN             36
#define SPELL_SHOCKING_GRASP         37
#define SPELL_SLEEP                  38
#define SPELL_STRENGTH               39
#define SPELL_SUMMON                 40
#define SPELL_HASTE                  41
#define SPELL_WORD_OF_RECALL         42
#define SPELL_REMOVE_POISON          43
#define SPELL_SENSE_LIFE             44
#define SPELL_IDENTIFY               45
#define SPELL_PRAYER                 46
#define SPELL_FIRESTORM              47
#define SPELL_FIRE_BREATH            48
#define SPELL_GAS_BREATH             49
#define SPELL_FROST_BREATH           50
#define SPELL_ACID_BREATH            51
#define SPELL_LIGHTNING_BREATH       52
#define SPELL_FARSEE                 53
#define SPELL_FEAR                   54
#define SPELL_RECHARGER              55
#define SPELL_VITALITY               56
#define SPELL_CURE_SERIOUS           57
#define SPELL_DESTROY_UNDEAD         58
#define SPELL_METEOR_SWARM           59
#define SPELL_CREEPING               60
#define SPELL_MINOR_GLOBE            61
#define SPELL_CHAIN_LIGHTNING        62
#define SPELL_DIMENSION_DOOR         63
#define SPELL_VIGORIZE_LIGHT         64
#define SPELL_VIGORIZE_SERIOUS       65
#define SPELL_VIGORIZE_CRITIC        66
#define SPELL_DISPEL_INVISIBLE       67
#define SPELL_WIZARD_EYE             68
#define SPELL_CLAIRVOYANCE           69
#define SPELL_REJUVENATE_MAJOR       70
#define SPELL_RAY_OF_ENFEEBLEMENT    71
#define SPELL_DISPEL_GOOD            72
#define SPELL_DEXTERITY              73
#define SPELL_REJUVENATE_MINOR       74
#define SPELL_AGE                    75
#define SPELL_CYCLONE                76
#define SPELL_BIGBYS_CLENCHED_FIST   77
#define SPELL_CONJURE_ELEMENTAL      78
#define SPELL_VITALIZE_MANA          79
#define SPELL_RELOCATE               80
#define SPELL_PROTECT_FROM_GOOD      81
#define SPELL_ANIMATE_DEAD           82
#define SPELL_LEVITATE               83
#define SPELL_FLY                    84
#define SPELL_WATERBREATH            85
#define SPELL_PLANE_SHIFT            86
#define SPELL_GATE                   87
#define SPELL_RESURRECT              88
#define SPELL_MASS_CHARM             89
#define SPELL_DETECT_EVIL            90
#define SPELL_DETECT_GOOD            91
#define SPELL_DETECT_MAGIC           92
#define SPELL_DISPEL_MAGIC           93
#define SPELL_PRESERVE               94
#define SPELL_MASS_INVIS             95
#define SPELL_PROTECT_FROM_FIRE      96
#define SPELL_PROTECT_FROM_COLD      97
#define SPELL_PROTECT_FROM_LIGHTNING 98
#define SPELL_DARKNESS               99
#define SPELL_MINOR_PARALYSIS        100
#define SPELL_MAJOR_PARALYSIS        101
#define SPELL_SLOW                   102
#define SPELL_WITHER                 103
#define SPELL_PROTECT_FROM_GAS       104
#define SPELL_PROTECT_FROM_ACID      105
#define SPELL_INFRAVISION            106
#define SPELL_PRISMATIC_SPRAY        107
#define SPELL_FIRESHIELD             108
#define SPELL_COLOR_SPRAY            109
#define SPELL_INCENDIARY_CLOUD       110
#define SPELL_ICE_STORM              111
#define SPELL_DISINTEGRATE           112
#define SPELL_CAUSE_LIGHT            113
#define SPELL_CAUSE_SERIOUS          114
#define SPELL_CAUSE_CRITICAL         115
#define SPELL_ACID_BLAST             116
#define SPELL_FAERIE_FIRE            117
#define SPELL_FAERIE_FOG             118
#define SPELL_PWORD_KILL             119
#define SPELL_PWORD_BLIND            120
#define SPELL_PWORD_STUN             121
#define SPELL_UNHOLY_WORD            122
#define SPELL_HOLY_WORD              123
#define SPELL_SUNRAY                 124
#define SPELL_FEEBLEMIND             126
#define SPELL_SILENCE                127
#define SPELL_TURN_UNDEAD            128
#define SPELL_COMMAND_UNDEAD         129
#define SPELL_SLOW_POISON            130
#define SPELL_COLDSHIELD             131
#define SPELL_COMPREHEND_LANGUAGES   132
#define SPELL_WRAITHFORM             133
#define SPELL_VAMPIRIC_TOUCH         134
#define SPELL_PROT_UNDEAD            135
#define SPELL_PROT_FROM_UNDEAD       136
#define SPELL_COMMAND_HORDE          137
#define SPELL_HEAL_UNDEAD            138
#define SPELL_ENTANGLE               139
#define SPELL_CREATE_SPRING          140
#define SPELL_BARKSKIN               141
#define SPELL_MOONWELL               142
#define SPELL_CREATE_DRACOLICH       143
#define SPELL_GLOBE                  144
#define SPELL_EMBALM                 145
#define SPELL_SHADOW_BREATH_1        146
#define SPELL_SHADOW_BREATH_2        147
#define SPELL_WALL_OF_FLAMES         148
#define SPELL_WALL_OF_ICE            149
#define SPELL_WALL_OF_STONE          150
#define SPELL_WALL_OF_IRON           151
#define SPELL_WALL_OF_FORCE          152
#define SPELL_WALL_OF_BONES          153
#define SPELL_LIGHTNING_CURTAIN      154
#define SPELL_MOLECULAR_CONTROL      155
#define SPELL_MOLECULAR_AGITATION    156
#define SPELL_ADRENALINE_CONTROL     157
#define SPELL_AURA_SIGHT             158
#define SPELL_AWE                    159
#define SPELL_BALLISTIC_ATTACK       160
#define SPELL_BIOFEEDBACK            161
#define SPELL_CELL_ADJUSTMENT        162
#define SPELL_COMBAT_MIND            163
#define SPELL_EGO_BLAST              164
#define SPELL_CREATE_SOUND           165
#define SPELL_DEATH_FIELD            166
#define SPELL_DETONATE               167
#define SPELL_ASPHYXIATE             168
#define SPELL_DISPLACEMENT           169
#define SPELL_DOMINATION             170
#define SPELL_ECTOPLASMIC_FORM       171
#define SPELL_EGO_WHIP               172
#define SPELL_ENERGY_CONTAINMENT     173
#define SPELL_ENHANCE_ARMOR          174
#define SPELL_ENHANCED_STR           175
#define SPELL_ENHANCED_DEX           176
#define SPELL_ENHANCED_AGI           177
#define SPELL_ENHANCED_CON           178
#define SPELL_FLESH_ARMOR            179
#define SPELL_INERTIAL_BARRIER       180
#define SPELL_INFLICT_PAIN           181
#define SPELL_INTELLECT_FORTRESS     182
#define SPELL_LEND_HEALTH            183
#define SPELL_POWERCAST_FLY          184
#define SPELL_CONFUSE                185
#define SPELL_DISEASE                186
#define SPELL_CHARM_ANIMAL           187
#define SPELL_SOULSHIELD             188
#define SPELL_INVIS_MAJOR            189
#define SPELL_MASS_HEAL              190

/* shaman spells */

#define SPELL_ICE_MISSILE            191
#define SPELL_SPIRIT_ARMOR           192
#define SPELL_WOLFSPEED              193
#define SPELL_TRANSFER_WELLNESS      194
#define SPELL_FLAMEBURST             195
#define SPELL_SCALDING_BLAST         196
#define SPELL_PYTHONSTING            197
#define SPELL_SNAILSPEED             198
#define SPELL_MOLEVISION             199
#define SPELL_PURIFY_SPIRIT          200
#define SPELL_PANTHERSPEED           201
#define SPELL_MOUSESTRENGTH          202
#define SPELL_SUMMON_BEAST           203
#define SPELL_HAWKVISION             204
#define SPELL_SCORCHING_TOUCH        205
#define SPELL_MENDING                206
#define SPELL_SOUL_DISTURBANCE       207
#define SPELL_SPIRIT_SIGHT           208
#define SPELL_BEARSTRENGTH           209
#define SPELL_SHREWTAMENESS          210
#define SPELL_SENSE_SPIRIT           211
#define SPELL_MALISON                212
#define SPELL_WELLNESS               213
#define SPELL_GREATER_MENDING        214
#define SPELL_LIONRAGE               215
#define SPELL_SPIRIT_ANGUISH         216
#define SPELL_EARTHEN_GRASP          217
#define SPELL_SUMMON_SPIRIT          218
#define SPELL_GREATER_SOUL_DISTURB   219
#define SPELL_SPIRIT_WARD            220
#define SPELL_ELEPHANTSTRENGTH       221
#define SPELL_GREATER_PYTHONSTING    222
#define SPELL_SCATHING_WIND          223
#define SPELL_REVEAL_TRUE_FORM       224
#define SPELL_GREATER_SPIRIT_SIGHT   225
#define SPELL_EARTHEN_RAIN           226
#define SPELL_GREATER_SPIRIT_WARD    227
#define SPELL_SUSTENANCE             228
#define SPELL_CORROSIVE_BLAST        229
#define SPELL_RESTORATION            230
#define SPELL_GREATER_SUST           231
#define SPELL_COLD_WARD              232
#define SPELL_FIRE_WARD              233
#define SPELL_LESSER_MENDING         234
#define SPELL_MOLTEN_SPRAY           235
#define SPELL_TRUE_SEEING            236
#define SPELL_IRONWOOD               237
#define SPELL_RAVENFLIGHT            238
#define SPELL_GREATER_RAVENFLIGHT    239
#define SPELL_LORE                   240
#define SPELL_WORMHOLE               241
#define SPELL_ETHERPORTAL            242
#define SPELL_FULL_HARM              243
#define SPELL_CONJURE_GREATER_ELEMENTAL 244
#define SPELL_GROUP_RECALL           245
#define SPELL_GREATER_EARTHEN_GRASP  246
#define SPELL_GROUP_STONE_SKIN       247
#define SPELL_ENLARGE                248
#define SPELL_REDUCE                 249
#define SPELL_REVEAL_SPIRIT_ESSENCE  250
#define SPELL_SPIRIT_JUMP            251
#define SPELL_BEHOLDER_DISIN         252
#define SPELL_BEHOLDER_DAMAGE        253
#define SPELL_ARIEKS_SHATTERING_ICEBALL 254
#define SPELL_ENRAGE                 255
#define SPELL_BLINDING_BREATH        256
#define SPELL_MIND_BLANK             257
#define SPELL_SIGHT_LINK             258
#define SPELL_CANNIBALIZE            259
#define SPELL_TOWER_IRON_WILL        260
#define SPELL_MIRROR_IMAGE           261
#define SPELL_REVEAL_TRUE_NAME       262
#define SPELL_BLUR                   263
#define SPELL_PRISMATIC_CUBE         264
#define SPELL_JUDGEMENT              265
#define SPELL_GREATER_WRAITHFORM     266
#define SPELL_ELEMENTAL_FORM         267
#define SPELL_RAISE_SPECTRE          268
#define SPELL_RAISE_WRAITH           269
#define SPELL_RAISE_VAMPIRE          270
#define SPELL_RAISE_LICH             271
#define SPELL_PALADIN_AURA           272
#define SPELL_MINDSHIELD	     273
#define SPELL_AIRY_WATER	     274
#define SPELL_CURE_DISEASE           275
#define SPELL_POLYMORPH_OBJECT       276
#define SPELL_IMMOLATE               277
#define SPELL_APOCALYPSE	     278
#define SPELL_SENSE_FOLLOWER	     279
#define SPELL_PASS_WITHOUT_TRACE     280
#define SPELL_ETHER_WARP	     281
#define SPELL_STARSHELL              282
#define SPELL_CLOAK_OF_FEAR          283
#define SPELL_VAMPIRE                284
#define SPELL_BIGBYS_CRUSHING_HAND   285
#define SPELL_STORNOGS_SPHERES	     286
#define SPELL_STORNOGS_GREATER_SPHERES  287
#define SPELL_GROUP_GLOBE            288
#define SPELL_ETHER_SENSE            289
#define SPELL_CALL_OF_THE_WILD       290
#define SPELL_HOLY_SACRIFICE	     291
#define SPELL_BATTLE_ECSTASY	     292
#define SPELL_DAZZLE		     293
#define SPELL_REGENERATION	     294
#define SPELL_WEB		     295
#define SPELL_PLEASANTRY	     296
#define SPELL_MAGE_FLAME             297
#define SPELL_SELF_COMPREHENSION     298
#define SPELL_ENLARGE_ITEM           299
#define SPELL_REDUCE_ITEM            300
#define SPELL_DEFLECT		     301
#define SPELL_GLOBE_OF_DARKNESS      302
#define SPELL_RADIAL_NAV	     303
#define SPELL_MIRACLE                304
#define SPELL_MOONSTONE		     305
#define SPELL_COMMAND                306
#define SPELL_MASS_BARKSKIN          307
#define SPELL_PSYCHIC_CRUSH          308
#define SPELL_STORNOGS_LOWERED_RES   309
#define SPELL_DIVINE_FURY            310
#define SPELL_BARB_BREATH	     311
#define SPELL_BIGBYS_GRASPING_FIST   312
#define SPELL_CHANNEL		     313
#define SPELL_SANCTUARY		     314
#define SPELL_HELLFIRE	             315
#define SPELL_SENSE_HOLINESS         316
#define SPELL_UNHOLY_WIND            317
#define SPELL_PROTECT_FROM_LIVING    318
#define SPELL_UNMAKING               319
#define SPELL_INVOKE_NEG_ENERGY      320
#define SPELL_LIFELUST               321
#define SPELL_SOUL_LINK              322
#define SPELL_PURGE                  323
#define SPELL_DEVITALIZE             324
#define SPELL_FROSTBITE              325
#define SPELL_NETHER_TOUCH           326
#define SPELL_CHANNEL_NEG_ENERGY     327
#define SPELL_SHADOW_AURA            328
#define SPELL_VORTEX_OF_FEAR         329
#define SPELL_DISPEL_LIFEFORCE       330
#define SPELL_ALTER_ENERGY_POLARITY  331
#define SPELL_NETHER_GATE            332
#define SPELL_NEG_ENERGY_BARRIER     333
#define SPELL_SHADOW_GATE            334
#define SPELL_LIFE_WARD              335
#define SPELL_SHADOW_VISION          336
#define SPELL_ENTROPY_STORM          337
#define SPELL_MASS_EMBALM	     338
#define SPELL_MASS_PRESERVE	     339
#define SPELL_DARK_COMPACT	     340
#define SPELL_HANDOFDEATH	     341
#define SPELL_MENTAL_ANGUISH	     342
#define SPELL_SPINAL_CORRUPTION	     343
#define SPELL_MEMORY_BLOCK	     344
#define SPELL_PSIONIC_CLOUD	     345
#define SPELL_ETHEREAL_RIFT	     346
#define SPELL_PULCHRITUDE            347
#define SPELL_FORTITUDE	             348
#define SPELL_WANDERING_WOODS	     349
#define SPELL_FLAME_BLADE	     350
#define SPELL_ELEMENTAL_SWARM	     351
#define SPELL_SERENDIPITY	     352
#define SPELL_TRANQUILITY	     353
#define SPELL_AID		     354
#define SPELL_ENDURANCE		     355
#define SPELL_ACCEL_HEALING	     356
#define SPELL_VITALIZE_UNDEAD        357
#define SPELL_CONSECRATE_LAND	     358
#define SPELL_NOVA		     359
#define SPELL_SIREN_SONG	     360
#define SPELL_HARMONIC_RESONANCE     361
#define SPELL_ELEMENTAL_AURA         362
#define SPELL_ANTI_MAGIC_RAY	     363
#define SPELL_PRISMATIC_RAY	     364
#define SPELL_ACID_STREAM            365
#define SPELL_GASEOUS_CLOUD          366
#define SPELL_EARTHEN_MAUL           367
#define SPELL_RESTORE_ITEM           368
#define SPELL_NATURES_TOUCH          369
#define SPELL_STICKS_TO_SNAKES       370

/* SPEC SPELLS - KVARK */
#define SPELL_GROUP_HEAL             371
#define SPELL_LESSER_SANCTUARY       372
#define SPELL_AURA_OF_REBIRTH         373
#define SPELL_RING_LIGHTNING         374
#define SPELL_NAPALM                 375
#define SPELL_STRONG_ACID            376
#define SPELL_CORPSEFORM             377
#define SPELL_NEGATIVE_CONCUSSION_BLAST 378
#define SPELL_MIND_TRAVEL            379
#define SPELL_CREATE_GREATER_DRACOLICH 380
#define SPELL_GREATER_SPIRIT_ANGUISH 381
#define SPELL_ROPE_TRICK	     382
#define SPELL_PROTECT_FROM_ANIMAL    383
#define SPELL_ANIMAL_FRIENDSHIP      384
#define SPELL_ANIMAL_VISION          385
#define SPELL_CDOOM	 	     386

/* REAVER SPELLS - Ilienze */
#define SPELL_BALADORS_PROTECTION    387
#define SPELL_LLIENDILS_STORMSHOCK   388
#define SPELL_FERRIX_PRECISION       389
#define SPELL_ILIENZES_FLAME_SWORD   390
#define SPELL_ESHABALAS_VITALITY	   391
#define SPELL_KANCHELSIS_FURY        392
#define SPELL_THRYMS_ICERAZOR        393
/* END REAVER SPELLS  */

#define SPELL_MAGMA_BURST	     394
#define SPELL_BATTLETIDE	     395
#define SPELL_AIR_FORM			 396
#define SPELL_WATER_TO_LIFE		 397
#define SPELL_LIVING_STONE		398
#define SPELL_EARTHEN_TOMB		399

/* ILLUSIONIST SPELLS */

#define SPELL_PHANTOM_ARMOR     400
#define SPELL_SHADOW_MONSTER    401
#define SPELL_INSECTS           402
#define SPELL_ILLUSIONARY_WALL  403
#define SPELL_BOULDER           404
#define SPELL_SHADOW_TRAVEL     405
#define SPELL_STUNNING_VISIONS  406
#define SPELL_REFLECTION        407
#define SPELL_MASK              408
#define SPELL_WATCHING_WALL     409
#define SPELL_NIGHTMARE         410
#define SPELL_SHADOW_SHIELD     411
#define SPELL_VANISH            412
#define SPELL_HAMMER            413
#define SPELL_DETECT_ILLUSION   414
#define SPELL_DREAM_TRAVEL      415
#define SPELL_MAGIC_BARRIER     416
#define SPELL_CLONE_FORM        417
#define SPELL_DELIRIUM          418
#define SPELL_IMPRISON          419
#define SPELL_NONEXISTENCE      420
#define SPELL_TITAN             421
#define SPELL_DRAGON            422

#define SPELL_CONJURE_WATER     423
#define SPELL_DREAD_WAVE        424
#define SPELL_GREATER_LIVING_STONE  425

#define SPELL_ETHEREAL_GROUNDS		426
#define SPELL_SPAWN	427

// For Shabo Proc
#define SPELL_ACIDIMMOLATE              428
#define SPELL_FLICKER			429
#define SPELL_GREATER_FLICKER		430

#define SPELL_SOLAR_FLARE	431
#define SPELL_CHAOTIC_RIPPLE 432
#define SPELL_BLINK 433
#define SPELL_MORDENKAINENS_LUCUBRATION 434
#define SPELL_RACE_CHANGE 435
#define SPELL_BEASTFORM 436

#define SPELL_GREATER_HEAL_UNDEAD 437
#define SPELL_HEALING_SALVE  438
#define SPELL_PLAGUE  439
#define SPELL_FLARE   440
#define SPELL_PEACE   441
#define SPELL_SHADOW_PROJECTION  442
#define SPELL_DEATH_BLESSING 443

// Druid Specs
#define SPELL_GROW  444
#define SPELL_VINES 445
#define SPELL_AWAKEN_FOREST 446
#define SPELL_REFRESHING_FOUNTAIN 	     447
#define SPELL_MAGICAL_FOUNTAIN 	     448
#define SPELL_HURRICANE 	     449
#define SPELL_STORMSHIELD      450
#define SPELL_BLOODTOSTONE     451

// Ethermancer Spells
#define SPELL_VAPOR_ARMOR      452
#define SPELL_WINDWALK         453
#define SPELL_WIND_BLADE       454
#define SPELL_FROST_BOLT       455
#define SPELL_GUST             456
#define SPELL_ETHEREAL_FORM      457
#define SPELL_ETHEREAL_RECHARGE 458
#define SPELL_ARCANE_WHIRLWIND 459
#define SPELL_FORKED_LIGHTNING 460
#define SPELL_PURGE_LIVING     461
#define SPELL_WAY_OF_THE_WIND  462
#define SPELL_INDUCE_TUPOR     463
#define SPELL_GUARDIAN_SPIRIT  464
#define SPELL_STORM_EMPATHY    466
#define SPELL_VAPOR_STRIKE     467
#define SPELL_FROST_BEACON     468
#define SPELL_CONJURE_AIR      469
#define SPELL_MASS_FLY         470
#define SPELL_PATH_OF_FROST    471
#define SPELL_COLD_SNAP        472
#define SPELL_FAERIE_SIGHT     473
#define SPELL_INDOMITABILITY   474
#define SPELL_TEMPEST_TERRAIN  475

// Frost Magus Ethermancer Spec
#define SPELL_TEMPEST           465
#define SPELL_WIND_RAGE         476
#define SPELL_ETHEREAL_ALLIANCE 477
#define SPELL_GREATER_ETHEREAL  478
#define SPELL_DREAD_BLADE        479

#define SPELL_ELEM_FURY            480
#define SPELL_ELEM_AFFINITY        481
#define SPELL_SPIRIT_WALK          482
#define SPELL_ESSENCE_OF_WOLF      483
#define SPELL_GREATER_SUMMON_BEAST 484

#define SPELL_CREATE_GOLEM      485
#define SPELL_RAISE_SHADOW      486

#define SPELL_SHATTER		487
#define SPELL_GROUP_TELEPORT    488
#define SPELL_CONTROL_FLAMES    489
#define SPELL_LESSER_RESURRECT  490
#define SPELL_GLASS_BOMB        491
#define SPELL_FIRE_AURA         492
#define SPELL_GREASE            493
#define SPELL_NITROGEN          494
#define SPELL_BANISH            495
#define SPELL_BLOOD_ALLIANCE    496

#define SPELL_CALL_WOODLAND     497
#define SPELL_BINDING_WIND      498
#define SPELL_WIND_TUNNEL       499
#define SPELL_NATURES_BLESSING  500
#define SPELL_SUMMON_INSECTS    501
#define SPELL_ANIMAL_GROWTH     502
#define SPELL_SEVER_LINK        503
#define SPELL_SPORE_CLOUD       504
#define SPELL_SPORE_BURST       505
#define SPELL_GROW_SPIKES       506
#define SPELL_SPIKE_GROWTH      507
#define SPELL_TREE              508
#define SPELL_TRANS_MUD_ROCK    509
#define SPELL_TRANS_ROCK_MUD    510
#define SPELL_TRANS_MUD_WATER   511
#define SPELL_TRANS_WATER_MUD   512
#define SPELL_TRANS_WATER_AIR   513
#define SPELL_TRANS_AIR_WATER   514
#define SPELL_VIRTUE            515
#define SPELL_TRANS_ROCK_LAVA   516
#define SPELL_BLOODHOUND        517
#define SPELL_DEPRESSED_EARTH   518
#define SPELL_TRANS_LAVA_ROCK   519
#define SPELL_COMET             520

// Flame Reaver Spell
#define SPELL_CEGILUNE_BLADE      521
#define SPELL_RIGHTEOUS_AURA      522
#define SPELL_BLEAK_FOEMAN        523
#define SPELL_STORMCALLERS_FURY   524
#define SPELL_CHILLING_IMPLOSION  525
#define SPELL_LIGHTNINGSHIELD     526

#define SPELL_DOOM_BLADE        527

#define SPELL_COSMIC_VACUUM		  528
#define SPELL_SUPERNOVA			    529
#define SPELL_PLANETARY_ALIGNMENT	530
#define SPELL_ETHEREAL_DISCHARGE	531

// SPEC Spells Illusionist - Deceiver
#define SPELL_OBSCURING_MIST    532
#define SPELL_SUPPRESSION        533
// SPEC Spells Illusionist - Dark Dreamer
#define SPELL_SHADOW_MERGE      534
#define SPELL_SHADOW_SPAWN      535
#define SPELL_SHDW_GATE_ARDGRAL 536
#define SPELL_THOUGHT_BEACON    537
#define SPELL_DIVINE_BLESSING   538
#define SPELL_NATURES_CALLING   539


#define SPELL_PERM_INCREASE_STR   540
#define SPELL_PERM_INCREASE_AGI   541
#define SPELL_PERM_INCREASE_DEX   542
#define SPELL_PERM_INCREASE_CON   543
#define SPELL_PERM_INCREASE_LUCK  544
#define SPELL_PERM_INCREASE_POW   545
#define SPELL_PERM_INCREASE_INT   546
#define SPELL_PERM_INCREASE_WIS   547
#define SPELL_PERM_INCREASE_CHA   548

#define SPELL_MISSILE_BARRAGE       549
#define SPELL_POLAR_VORTEX          550
#define SPELL_ETHEREAL_TRAVEL       551
#define SPELL_COSMIC_RIFT           552
#define SPELL_CHAOS_VOLLEY          553
#define SPELL_KNOCK                 554
#define SPELL_FIREBRAND             555
#define SPELL_HOLY_SWORD            556
#define SPELL_DIVINE_POWER          557
#define SPELL_ATONEMENT             558
#define SPELL_GROUP_HASTE           559
#define SPELL_CHAOS_SHIELD          560
#define SPELL_SLASHING_DARKNESS     561
#define SPELL_DEATH_THROES          562
#define SPELL_STATIC_DISCHARGE      563
#define SPELL_PEBBLE                564
#define SPELL_BLOOD_SIROCCO         565
#define SPELL_EXTRACT_WATER_ELEMENTAL 566
#define SPELL_DEADFALL              567
//#define SPELL_                    568 Unused.
#define SPELL_EXPLOSIVE_CASCADE     569
#define SPELL_CELESTIAL_AURA        570
#define SPELL_SUMMON_GHASTS         571
#define SPELL_GHASTLY_TOUCH         572
#define SPELL_CASCADING_ELEMENTAL_BEAM        573
#define SPELL_EXCOGITATE            574
#define SPELL_HOLY_DHARMA           575
#define SPELL_UNDEAD_TO_DEATH       576
#define SPELL_ELECTRICAL_EXECUTION  577
#define SPELL_MIRAGE                578
#define SPELL_GUARDIAN_SPIRITS      579
#define SPELL_TORMENT_SPIRITS       580
#define SPELL_INVIGORATE            581
#define SPELL_PSIONIC_WAVE_BLAST     582
#define SPELL_DEPART                 583
#define SPELL_AGILITY                584
#define SPELL_ENERVATION             585
#define SPELL_LIFE_BOLT              586
#define SPELL_CELERITY               587
#define SPELL_MIELIKKI_VITALITY      588
#define SPELL_RAZOR_WIND             589
#define SPELL_CONJURE_VOID           590
#define SPELL_CONJURE_ICE            591
#define SPELL_ICE_ARMOR              592
#define SPELL_NEG_ARMOR              593
#define SPELL_ETHERIC_GUST           594
#define SPELL_REPAIR_ONE_ITEM        595
#define SPELL_TAINT                  596
#define SPELL_CALL_TITAN             597
#define SPELL_CALL_AVATAR            598
#define SPELL_CALL_ASURA             599
#define SPELL_CALL_BRALANI           600
#define SPELL_CALL_KNIGHT            601
#define SPELL_CALL_LIBERATOR         602
#define SPELL_CALL_DEVA              603
#define SPELL_RESTORE_SPIRIT         604
#define SPELL_VITALIZE_SOUL          605
#define SPELL_ANGELIC_COUNTENANCE    606
#define SPELL_PROTECT_SOUL           607
#define SPELL_MEND_SOUL              608
#define SPELL_HOLY_AURA              609
#define SPELL_AID_OF_THE_HEAVENS     610
#define SPELL_VOICE_OF_CREATION      611
#define SPELL_PYROKINESIS            612
#define SPELL_OBTENEBRATION          613
#define SPELL_HOLY_BLADE             614
#define SPELL_HOLY_LIGHT             615
#define SPELL_CALL_ARCHON            616
#define SPELL_LODESTONE              617
#define SPELL_LIFE_LEECH             618
#define SPELL_BMANTLE                619
#define SPELL_DECAYING_FLESH         620
#define SPELL_NOAUCTION	             621
#define SPELL_BATTLEMAGE	           622
#define SPELL_CORPSE_PORTAL	         623
#define SPELL_CONTAIN_BEING		       624
/* Blighter spells */
#define SPELL_THORNSKIN               625
#define SPELL_FLAME_SPHERE            626
#define SPELL_DESECRATE_LAND          627
#define SPELL_CONTAGION               628
#define SPELL_FORBIDDANCE             629
#define SPELL_WAVES_FATIGUE           630
#define SPELL_ACID_RAIN               631
#define SPELL_HORRID_WILTING          632
#define SPELL_SHAMBLER                633
#define SPELL_IMPLOSION               634
#define SPELL_BLIGHT                  635
#define SPELL_SANDSTORM               636
#define SPELL_FIRELANCE               637
#define SPELL_DRAIN_NATURE            638
#define SPELL_CREATE_POND             639
#define SPELL_TOXIC_FOG               640
#define SPELL_FALUZURES_VITALITY      641
#define SPELL_SAP_NATURE              642
#define SPELL_BLOODSTONE              643
#define SPELL_RETURN_SOUL             644
#define SPELL_AMATTER_COLLISION       645
#define SPELL_ARCTIC_BLAST            646
#define SPELL_CURSE_OF_YZAR           647
#define SPELL_ICE_SPIKES              648
#define SPELL_WALL_OF_AIR             649
#define SPELL_COMPACT_CORPSE          650
#define SPELL_REST                    651
#define SPELL_GIRILALS_GRANITE_HAMMER 652
#define SPELL_ILESHS_SMASHING_FURY    653
#define SPELL_INFERNAL_FURY           654
#define LAST_SPELL SPELL_INFERNAL_FURY


#define FIRST_SKILL                  1000  /* should be a decent split point */
#define SKILL_SNEAK                  1000
#define SKILL_HIDE                   1001
#define SKILL_STEAL                  1002
#define SKILL_BACKSTAB               1003
#define SKILL_PICK_LOCK              1004
#define SKILL_KICK                   1005
#define SKILL_BASH                   1006
#define SKILL_RESCUE                 1007
#define SKILL_DOUBLE_ATTACK          1008
#define SKILL_DUAL_WIELD             1009
#define SKILL_DODGE                  1010
#define SKILL_HITALL                 1011
#define SKILL_TRAP                   1012
#define SKILL_BERSERK                1013
#define SKILL_APPLY_POISON           1014
#define SKILL_TRACK                  1015
#define SKILL_LISTEN                 1016
#define SKILL_DISARM                 1017
#define SKILL_PARRY                  1018
#define SKILL_SHADOW                 1019
#define SKILL_INSTANT_KILL           1020
#define SKILL_HEADBUTT               1021
#define SKILL_MEDITATE               1022
#define SKILL_SURPRISE               1023
#define SKILL_AWARENESS              1024
#define SKILL_MOUNT                  1025
#define SKILL_FEIGN_DEATH            1026
#define SKILL_QUIVERING_PALM         1027
#define SKILL_FIRST_AID              1028
#define SKILL_SAFE_FALL              1029
#define SKILL_SWITCH_OPPONENTS       1030
#define SKILL_SPRINGLEAP             1031
#define SKILL_MARTIAL_ARTS           1032
#define SKILL_UNARMED_DAMAGE         1033
#define SKILL_BUDDHA_PALM            1034
#define SKILL_HEROISM                1035
#define SKILL_CHANT                  1036
#define SKILL_DRAGON_PUNCH           1037
#define SKILL_THROAT_CRUSH	         1038
#define SKILL_CALM                   1039
#define SKILL_RANGE_SPECIALIST       1040
#define SKILL_ARCHERY                1041
#define SKILL_RANGE_WEAPONS          1042
#define SKILL_CIRCLE                 1043
#define SKILL_RIPOSTE                1044
#define SKILL_UNUSED                 1045 // Used to be summon mount, but it's an innate ffs.
#define SKILL_BANDAGE                1046
#define SKILL_SCRIBE                 1047
#define SKILL_QUICK_CHANT            1048
#define SKILL_SPELL_KNOWLEDGE_CLERICAL 1049
#define SKILL_SPELL_KNOWLEDGE_MAGICAL  1050
#define SKILL_1H_BLUDGEON            1051
#define SKILL_1H_SLASHING            1052
#define SKILL_1H_PIERCING            1053
#define SKILL_1H_FLAYING             1054
#define SKILL_2H_BLUDGEON            1055
#define SKILL_2H_SLASHING            1056
#define SKILL_2H_FLAYING             1057
#define SKILL_BLINDFIGHTING          1058
#define SKILL_CLEAVE                 1059
#define SKILL_BEARHUG                1060
#define SKILL_OGRE_ROAR              1061
#define SKILL_CARVE                  1062
#define SKILL_SUBTERFUGE             1063
#define SKILL_TRIP                   1064
#define SKILL_DIRTTOSS               1065
#define SKILL_DISGUISE               1066
#define SKILL_SPELL_KNOWLEDGE_SHAMAN 1067
#define SKILL_CAST_SH_ANIMAL         1068
#define SKILL_CAST_SH_ELEMENT        1069
#define SKILL_CAST_SH_SPIRIT         1070
#define SKILL_CAPTURE                1071
#define SKILL_TRIPLE_ATTACK          1072
#define SKILL_APPRAISE               1073
#define SKILL_LORE                   1074
#define SKILL_SWIM                   1075
#define SKILL_AXE                    1076
#define SKILL_DAGGER                 1077
#define SKILL_FLAIL                  1078
#define SKILL_HAMMER                 1079
#define SKILL_LONGSWORD              1080
#define SKILL_MACE                   1081
#define SKILL_POLEARM                1082
#define SKILL_SHORTSWORD             1083
#define SKILL_CLUB                   1084
#define SKILL_2HANDSWORD             1085
#define SKILL_WHIP                   1086
#define SKILL_PARRY_AXE              1087
#define SKILL_PARRY_DAGGER           1088
#define SKILL_PARRY_FLAIL            1089
#define SKILL_PARRY_HAMMER           1090
#define SKILL_PARRY_LONGSWORD        1091
#define SKILL_PARRY_MACE             1092
#define SKILL_PARRY_POLEARM          1093
#define SKILL_PARRY_SHORTSWORD       1094
#define SKILL_PARRY_CLUB             1095
#define SKILL_PARRY_2HANDSWORD       1096
#define SKILL_PARRY_WHIP             1097
#define SKILL_SHIELD                 1098
#define SKILL_TWOHANDED_SWORD        1099
#define SKILL_STAFF                  1100
#define SKILL_PICK                   1101
#define SKILL_LANCE		               1102
#define SKILL_SICKLE		             1103
#define SKILL_FORK		               1104
#define SKILL_HORN		               1105
#define SKILL_NUMCHUCKS		           1106
#define SKILL_BAREHANDED_FIGHTING    1107
#define SKILL_GRAPPLE		             1108
#define SKILL_MOUNTED_COMBAT	       1109
#define SKILL_CLIMB		               1110
#define SKILL_ROUNDKICK 	           1111
#define SKILL_REGENERATE 	           1112
#define SKILL_AERIAL_COMBAT          1113
#define SKILL_AERIAL_CASTING         1114
#define SKILL_JIN_TOUCH              1115
#define SKILL_HAMSTRING              1116
#define SKILL_BODYSLAM               1117
#define SKILL_SHIELD_BLOCK	         1118
#define SKILL_COMBINATION	           1119
#define SKILL_GUARD	                 1120
#define SKILL_SHIELDLESS_BASH	       1121
#define SKILL_AGE_CORPSE             1122
#define SKILL_QUADRUPLE_ATTACK	     1123
#define SKILL_CRITICAL_ATTACK	       1124
#define SKILL_EVADE                  1125
#define SKILL_VICIOUS_ATTACK         1126
#define SKILL_SPINAL_TAP	           1127
#define SKILL_WAR_CRY    	           1128
#define SKILL_TACKLE		             1129
#define SKILL_CONTROL_FLEE           1130
#define SKILL_CRITICAL_STAB	         1131
#define SKILL_CRAFT                  1132
#define SKILL_MIX	                   1133
#define SKILL_FORGE	                 1134
#define SKILL_THROW_POTIONS          1135
#define SKILL_RAGE		               1136
#define SKILL_MAUL		               1137
#define SKILL_RAMPAGE                1138
#define SKILL_LOTUS                  1139
#define SKILL_CHI                    1140
#define SKILL_TRUE_STRIKE            1141
#define SKILL_RECONSTRUCTION         1142
#define SKILL_DISPLACEMENT           1143
#define SKILL_SIGHT                  1144
#define SKILL_SHIELDPUNCH	           1145
#define SKILL_SWEEPING_THRUST	       1146
#define SKILL_INFURIATE		           1147
#define SKILL_ENCRUST		             1148
#define SKILL_FOLLOWUP_RIPOSTE	     1149
#define SKILL_FIX		                 1150
#define SKILL_SKEWER		             1151
#define SKILL_LANCE_CHARGE           1152
#define SKILL_SIDESTEP		           1153
#define SKILL_ARCANE_RIPOSTE		     1154
#define SKILL_ARCANE_BLOCK		       1155
#define SKILL_DOUBLE_STRIKE		       1156
#define SKILL_WHIRLWIND		 	         1157
#define SKILL_CHARGE      	         1158
#define SKILL_DARTS			             1159
#define SKILL_REMIX   		           1160
#define SKILL_ENCHANT  		           1161
#define SKILL_VICIOUS_STRIKE         1162
#define SKILL_RUSH                   1163
#define SKILL_FLANK                  1164
#define SKILL_GAZE                   1165
#define SKILL_TAINTED_BLADE          1166
#define SKILL_BATTLE_SENSES          1167
#define SKILL_BLOOD_SCENT            1168
#define SKILL_BATTLE_ORDERS	         1169
#define SKILL_CALL_GRAVE             1170
#define SKILL_DISRUPTIVE_BLOW	       1171
#define SKILL_CRIPPLING_STRIKE	     1172
#define SKILL_REACH_WEAPONS          1173
#define SKILL_AMBUSH	               1174
#define SKILL_QUICK_STEP             1175
#define SKILL_SNEAKY_STRIKE          1176
#define SKILL_MANGLE                 1177
#define SKILL_BOILING_BLOOD          1178
#define SKILL_EXHUME                 1179
#define SKILL_HOLY_BLADE             1180
#define SKILL_MUG                    1181
#define SKILL_FADE                   1182
#define SKILL_SHADOW_MOVEMENT        1183
#define SKILL_SHRIEK		             1184
#define SKILL_LEGEND_LORE            1185
//#define SONG_DRIFTING                1186
#define SKILL_DISPERSE_FLAMES        1187
#define SKILL_FLAME_MASTERY          1188
#define SKILL_SOUL_TRAP              1189
#define SKILL_MINE                   1190
#define SKILL_FLURRY_OF_BLOWS	       1191
#define SKILL_FIST_OF_DRAGON	       1192
#define SKILL_FISHING                1193
#define SKILL_HEALING_MASTERY        1194
#define SKILL_DOUBLE_HEADBUTT        1195
#define SKILL_SPELLBIND              1196
#define SKILL_RETREAT				         1197
#define SKILL_EXPEDITED_RETREAT		   1198
#define SKILL_CHANT_MASTERY          1199
#define SKILL_SPELL_MASTERY          1200
#define SKILL_ANATOMY                1201
#define SKILL_SUMMON_BLIZZARD        1202
#define SKILL_SUMMON_FAMILIAR        1203
#define SKILL_ADVANCED_MEDITATION    1204
#define SKILL_SMELT	                 1205
#define SKILL_TOTEMIC_MASTERY        1206
#define SKILL_SMITE_EVIL             1207
#define SKILL_PARLAY                 1208
#define SKILL_DEVOTION               1209
#define SKILL_SPELLWEAVE             1210
#define SKILL_ROAR_OF_HEROES         1211
#define SKILL_GROUND_CASTING         1212
#define SKILL_SCRIBE_MASTERY         1213
#define SKILL_SILENT_SPELL           1214
#define SKILL_SHIELD_COMBAT          1215
#define SKILL_IMPROVED_SHIELD_COMBAT 1216
#define SKILL_SLIP		               1217
#define SKILL_IMPROVED_LISTEN        1218
#define SKILL_TWOWEAPON 	           1219
#define SKILL_IMPROVED_TWOWEAPON     1220
#define SKILL_KI_STRIKE              1221
#define SKILL_INFUSE_LIFE            1222
#define SKILL_SPELL_PENETRATION      1223
#define SKILL_HEADLOCK               1224
#define SKILL_ARMLOCK                1225
#define SKILL_GRAPPLER_COMBAT        1226
#define SKILL_GROUNDSLAM             1227
#define SKILL_LEGLOCK                1228
#define SKILL_DEVASTATING_CRITICAL   1229
#define SKILL_TOUGHNESS              1230
#define SKILL_SPATIAL_FOCUS          1231
#define SKILL_IMPROVED_ENDURANCE     1232
#define SKILL_IMPROVED_TRACK         1233
#define SKILL_EMPOWER_SONG           1234
#define SKILL_POINT_BLANK_SHOT       1235
#define SKILL_CRITICAL_SHOT          1236
#define SKILL_SHADOW_ARCHERY         1237
#define SKILL_EXPEDITIOUS_RETREAT    1238 // NOT to be confused with SKILL_EXPEDITED_RETREAT. who the hell named these skills?? --Maybe your momma
#define SKILL_CURSED_ARROWS          1239
#define SKILL_ENCHANT_ARROWS         1240
#define SKILL_INFUSE_MAGICAL_DEVICE  1241
#define SKILL_INDOMITABLE_RAGE       1242
#define SKILL_CHI_PURGE              1243
#define SKILL_HOLY_SMITE             1244
#define SKILL_NATURES_SANCTITY       1245
#define SKILL_INDIRECT_SHOT          1246
#define SKILL_SHORT_VAMP             1247
#define SKILL_DREAD_WRATH            1248
#define SKILL_EXPERT_PARRY           1249
#define SKILL_EXPERT_RIPOSTE         1250
#define SKILL_EPIC_STRENGTH          1251
#define SKILL_EPIC_POWER             1252
#define SKILL_EPIC_AGILITY           1253
#define SKILL_EPIC_INTELLIGENCE      1254
#define SKILL_EPIC_DEXTERITY         1255
#define SKILL_EPIC_WISDOM            1256
#define SKILL_EPIC_CONSTITUTION      1257
#define SKILL_EPIC_CHARISMA          1258
#define SKILL_EPIC_LUCK              1259
#define SKILL_THROAT_CRUSHER         1260 // Just a bogus skill to prevent wrong wear off message to the attacker.
#define SKILL_SHIP_DAMAGE_CONTROL    1261
#define SKILL_RAGE_REORIENT          1262 // Added to handle reorient on rage skill
#define SKILL_TIGER_PALM             1263
#define SKILL_DIAMOND_SOUL           1264
#define SKILL_BASEWARR               1265
#define SKILL_BASEROGUE              1266
#define SKILL_BASEPRIEST             1267
#define SKILL_BASEMAGE               1268
#define SKILL_1HCOMBAT               1269
#define SKILL_2HCOMBAT               1270
#define SKILL_BAREHANDEDCOMBAT       1271
#define SKILL_TAKEDOWNS              1272
#define SKILL_DEFENSIVETRAINING      1273
#define SKILL_CHANTS                 1274
#define SKILL_NATURALMAGIC           1275
#define SKILL_OCCULTMAGIC            1276
#define SKILL_HOLYMAGIC              1277
#define SKILL_RAGETACTICS            1278
#define SKILL_ENHANCEDMELEE          1279
#define SKILL_RESCUEALL              1280
#define SKILL_ENHANCEDBASH           1281
#define SKILL_GROUNDFIGHTING         1282
#define SKILL_MELEE_MASTERY          1283
#define SKILL_TRAMPLE                1284
#define SKILL_HANDCONTROL            1285
#define SKILL_BODYCONTROL            1286
#define SKILL_ONEWITHMIND            1287
#define SKILL_ONEWITHBODY            1288
#define SKILL_CELLADJUSTMENT         1289
#define SKILL_NATURESPROTECTIONS     1290
#define SKILL_PROTECT_FROM_EVIL      1291
#define SKILL_NATURESSENSES          1292
#define SKILL_RESTRAIN               1293
#define SKILL_BLADE_BARRAGE		       1294
#define SKILL_RIFF                   1295
#define SKILL_CONCENTRATION          1296
#define SKILL_SALVAGE		             1297
#define SKILL_DREADNAUGHT            1298
#define SKILL_SHADOWSTEP             1299
#define SKILL_GARROTE                1300
#define SKILL_LEGSWEEP               1301
#define SKILL_NATURES_RUIN           1302
// Slots SKILL_ ...  1045 and 1186 are unused.

#define LAST_SKILL                   SKILL_NATURES_RUIN

//#ifdef SKILLPOINTS
//#define WHITE_SKILL                  -1
//#define BLUE_SKILL                   -2
//#define LAST_SKILL                   SKILL_NATURESSENSES
//#endif

#define FIRST_SECONDARY_SKILL        1501

/* paladin auras */
#define FIRST_AURA                   (FIRST_SECONDARY_SKILL+1)
#define AURA_PROTECTION              (FIRST_AURA)
#define AURA_PRECISION               (FIRST_AURA+1)
#define AURA_BATTLELUST              (FIRST_AURA+2)
#define AURA_HEALING                 (FIRST_AURA+3)
#define AURA_ENDURANCE               (FIRST_AURA+4)
#define AURA_VIGOR                   (FIRST_AURA+5)
#define AURA_SPELL_PROTECTION        (FIRST_AURA+6)
#define LAST_AURA                    (FIRST_AURA+6)

/* Instrument stuff */
#define FIRST_INSTRUMENT             (LAST_AURA+1)
#define INSTRUMENT_FLUTE             (FIRST_INSTRUMENT)
#define INSTRUMENT_LYRE              (FIRST_INSTRUMENT+1)
#define INSTRUMENT_MANDOLIN          (FIRST_INSTRUMENT+2)
#define INSTRUMENT_HARP              (FIRST_INSTRUMENT+3)
#define INSTRUMENT_DRUMS             (FIRST_INSTRUMENT+4)
#define INSTRUMENT_HORN              (FIRST_INSTRUMENT+5)
#define LAST_INSTRUMENT              (INSTRUMENT_HORN)

/* Bard related. Diff names, but still skills */
#define FIRST_SONG                   (LAST_INSTRUMENT+1)
#define SONG_MINDSHIELD              (FIRST_SONG)
#define SONG_CHARMING                (FIRST_SONG+1)
#define SONG_SLEEP                   (FIRST_SONG+2)
#define SONG_CALMING                 (FIRST_SONG+3)
#define SONG_HEALING                 (FIRST_SONG+4)
#define SONG_REVELATION              (FIRST_SONG+5)
#define SONG_HARMING                 (FIRST_SONG+6)
#define SONG_FLIGHT                  (FIRST_SONG+7)
#define SONG_PROTECTION              (FIRST_SONG+8)
#define SONG_HEROISM                 (FIRST_SONG+9)
#define SONG_COWARDICE               (FIRST_SONG+10)
#define SONG_FORGETFULNESS           (FIRST_SONG+11)
#define SONG_PEACE                   (FIRST_SONG+12)
#define SONG_CHAOS                   (FIRST_SONG+13)
#define SONG_DRAGONS                 (FIRST_SONG+14)
#define SONG_STORMS                  (FIRST_SONG+15)
#define SONG_DISCORD                 (FIRST_SONG+16)
#define SONG_HARMONY                 (FIRST_SONG+17)
#define SONG_SNATCHING               (FIRST_SONG+18)
#define SONG_DISSONANCE              (FIRST_SONG+19)
#define SONG_DRIFTING                (FIRST_SONG+20)
// Currently 19 instead of 21 (first+20 more), because SNATCHING and MINDSHIELD ?!?
//   These two songs are not included in the songs[] array in bard.c, nor do they seem implemented.
#define NUM_SONGS                    19
#define LAST_SONG                    (SONG_DRIFTING)

#define FIRST_POISON                 (LAST_SONG+1)
#define POISON_LIFELEAK              (FIRST_POISON)
#define POISON_WEAKNESS              (FIRST_POISON+1)
#define POISON_NEUROTOXIN            (FIRST_POISON+2)
#define POISON_HEART_TOXIN           (FIRST_POISON+3)
#define LAST_POISON                  (POISON_HEART_TOXIN)

// These need to be static since they're set in .obj files in zones.
#define HERB_SMOKED         1900
#define HERB_OCULARIUS      1901
#define HERB_BLUE_HAZE      1902
#define HERB_MEDICUS        1903
#define HERB_BLACK_KUSH     1904
#define HERB_GOOTWIET       1905

/* everything below does not make part of players skill data */
#define FIRST_TAG                    2001
#define TAG_OBJ_DECAY                2001
#define TAG_ALTERED_EXTRA2           2002
#define TAG_PHANTASMAL_FORM          2003
#define TAG_ETHEREAL_FORM            2004
#define TAG_MEMORIZE                 2005
#define TAG_PALADIN_VIT              2006
#define TAG_NOMISFIRE                2007
#define TAG_WITCHSPELL               2008
#define TAG_VAMPIRE_BITE             2009
#define TAG_EMBRACE_DEATH            2010
#define TAG_INNATE_TIMER             2011
#define TAG_SET_MASTER               2012
#define TAG_ILIENZE_SWORD_CHARGE     2013
#define TAG_DECREPIFY                2014
#define TAG_HATRED                   2015
#define TAG_PRESSURE_POINTS          2016
#define TAG_EATEN                    2017
#define TAG_OBJ_RECENT_FRAG          2018
#define TAG_KNOWN_SHAPE              2019
#define TAG_UNUSED                   2020
#define TAG_EPIC_MONOLITH            2021
#define TAG_EPIC_ERRAND              2022
#define TAG_EPIC_COMPLETED           2023
#define TAG_EPIC_POINTS              2024
#define TAG_SKILL_TIMER              2025
#define TAG_WET                      2026
#define TAG_POOL                     2027
#define TAG_SETPROC                  2028
#define TAG_IMMUNE_AREA              2029
#define TAG_PVPDELAY                 2030
#define TAG_MENTAL_SKILL_NOTCH       2031
#define TAG_PHYS_SKILL_NOTCH         2032
#define TAG_CEGILUNE_FIRE            2033
#define TAG_EPIC_LEVEL               2034
#define TAG_BAREFEET                 2035
#define TAG_GUARD_NEXUS_STONE        2036
#define TYPE_TRAP                    2037
#define TAG_HIT_COUNTER              2038
#define TAG_NUKED_COUNTER            2039
#define TAG_STORMCALLERS_FURY_TARGET 2040
#define TAG_CHILLING_IMPLOSION_TARGET 2041
#define TAG_ENHANCE_HEALING          2042
#define TAG_GRAPPLE                  2043
#define TAG_BEARHUG                  2044
#define TAG_HEADLOCK                 2045
#define TAG_ARMLOCK                  2046
#define TAG_LEGLOCK                  2047
#define TAG_BUILDING                 2048
#define TAG_ALLIANCE                 2049
#define TAG_REDUCED_EXP              2050
#define TAG_DREAD_WRATH              2051
#define TAG_FIRING                   2052
#define TAG_PLR_RECENT_FRAG          2053
#define TAG_DIVINE_FORCE_AFFECT      2054 // Divine force
#define TAG_DIVINE_FORCE_TIMER       2055 // Divine force
#define TAG_TRANSMUTE_ROOM           2056 // mark room transmute is in progress
#define TAG_ARROW_BLEED              2057
#define TAG_STOP_PROC                2058
#define TAG_TROLL_BURN               2059
#define TAG_RACE_CHANGE              2060
#define TAG_GUILDHALL                2061
#define TAG_DIRECTION                2062
#define TAG_SPAWN                    2063
#define TAG_HOLY_OFFENSE             2064  // for holy_weapon proc
#define TAG_HOLY_DEFENSE             2065  // for holy_weapon proc
#define TAG_BOON                     2066
#define TAG_CTF	                     2067
#define TAG_CTF_BONUS                2068
#define TAG_RACIAL_SKILLS            2069 // deprecated - 4/25/14
#define TAG_SOULBIND                 2070
#define ACH_UNSTOPPABLE              2071
#define ACH_LETSGETDIRTY             2072
#define ACH_SERIALKILLER             2073
#define AIP_LEVELACHIEVEMENT         2074
#define AIP_ARACHNOPHOBIA            2075
#define ACH_ARACHNOPHOBIA            2076
#define ACH_TROLLIN                  2077
#define ACH_MOOJUICE                 2078
#define ACH_DRAGONSLAYER             2079
#define ACH_MAYIHEALSYOU             2080
#define ACH_YOUSTRAHDME              2081
#define AIP_MOOJUICE                 2082
#define AIP_DRAGONSLAYER             2083
#define AIP_MAYIHEALSYOU             2084
#define AIP_YOUSTRAHDME              2085
#define AIP_TROLLIN                  2086
#define TAG_SALVATION                2087
#define TAG_DREADNAUGHT              2088
#define TAG_CRIPPLED                 2089
#define AIP_YOUSTRAHDME2             2090
#define AIP_DECEPTICON               2091
#define ACH_DECEPTICON               2092
#define TAG_RECENTLY_FRAGGED         2093
#define TAG_MINOTAUR_RAGE            2094
#define TAG_CONJURED_PET             2095
#define TAG_POTION_TIMER             2096
#define TAG_INTERCEPT                2097
#define TAG_LAYONHANDS               2098
#define PR_DEEPGNOME                 2099
#define DAMAGE_FALLING               2100 /* From falling to the ground */
#define PR_FORESTGNOME               2101
#define PR_ROCKGNOME                 2102
#define TAG_ADDICTED_BLOOD           2103
#define TAG_BLOODLUST                2104
#define TAG_EPICS                    2105
#define AIP_FREESLOOP                2106
#define TAG_RESTED                   2107
#define TAG_WELLRESTED               2108
#define TAG_EPICS_GAINED             2109
#define AIP_CARGOCOUNT               2110
#define ACH_DEATHSDOOR               2111
#define TAG_DEATHSDOOR               2112
#define TAG_BARDSONG_FAILURE         2113
#define TAG_CAMP                     2114
#define TAG_PERMINVIS                2115
#define TAG_LIFESTREAMNEWBIE         2116
#define TAG_SUICIDE_COUNT            2117
#define TAG_SQUIDRAGE                2118
#define AIP_DEMONSLAYER              2119
#define ACH_DEMONSLAYER              2120
#define TAG_NCHATSPAMMER             2121
#define AIP_ORE_MINED                2122
#define ACH_DO_YOU_MINE              2123
#define TAG_HELP_COOLDOWN            2124

#define SAVING_PARA   0
#define SAVING_ROD    1
#define SAVING_FEAR   2
#define SAVING_BREATH 3
#define SAVING_SPELL  4

#define BREATH_WEAPON_SAVE( ch, vict ) \
  (GET_LEVEL(ch) + breath_save_modifier - GET_LEVEL(vict))

#define TAR_IGNORE        BIT_1
#define TAR_CHAR_ROOM     BIT_2
#define TAR_CHAR_WORLD    BIT_3
#define TAR_FIGHT_SELF    BIT_4
#define TAR_FIGHT_VICT    BIT_5
#define TAR_SELF_ONLY     BIT_6     /* Only a check, use with ei. TAR_CHAR_ROOM */
#define TAR_SELF_NONO     BIT_7     /* Only a check, use with ei. TAR_CHAR_ROOM */
#define TAR_OBJ_INV       BIT_8
#define TAR_OBJ_ROOM      BIT_9
#define TAR_OBJ_WORLD     BIT_10
#define TAR_OBJ_EQUIP     BIT_11
#define TAR_CHAR_RANGE    BIT_12
#define TAR_RANGE1        BIT_13
#define TAR_RANGE2        BIT_14
#define TAR_AREA          BIT_15
#define TAR_OFFAREA       BIT_16
#define TAR_INSTACAST     BIT_17
#define TAR_AGGRO         BIT_18
#define TAR_NOCOMBAT      BIT_19
#define TAR_ANIMAL        BIT_20
#define TAR_SPIRIT        BIT_21
#define TAR_ELEMENTAL     BIT_22
#define TAR_MENTAL        BIT_23
#define TAR_PHYS          BIT_24
#define TAR_SKILL         BIT_25
#define TAR_EPIC          BIT_26
#define TAR_SPELL         BIT_27
#define TAR_POISON        BIT_28
#define TAR_WALL          BIT_29 
/* TAR_WALL checks arguments for directional keywords, and returns pointer 
   to a target object if ch can see a wall in that direction */

/* Possible Targets:

   bit 0 : IGNORE TARGET
   bit 1 : PC/NPC in room
   bit 2 : PC/NPC in world
   bit 3 : Object held
   bit 4 : Object in inventory
   bit 5 : Object in room
   bit 6 : Object in world
   bit 7 : If fighting, and no argument, select tar_char as self
   bit 8 : If fighting, and no argument, select tar_char as victim (fighting)
   bit 9 : If no argument, select self, if argument check that it IS self.

*/

#define SPELL_TYPE_SPELL   0
#define SPELL_TYPE_POTION  1
#define SPELL_TYPE_WAND    2
#define SPELL_TYPE_STAFF   3
#define SPELL_TYPE_SCROLL  4

#define GOOD_AVATAR_MOB 950
#define EVIL_AVATAR_MOB 951
#define GOOD_AVATAR_OBJ 950
#define EVIL_AVATAR_OBJ 951

#ifdef _DE_
#include "defines.h"

struct skill_data
{
  const char *name;
  // 0-56 for a skill, and 0-12 for a spell.
  int minLevel[CLASS_COUNT+1];
#if defined (_PFILE_)
  struct ClassSkillInfo m_class[CLASS_COUNT];     /* info for each class */
#endif
};

typedef struct skill_data Skill;
#endif

#endif /* _SOJ_SPELLS_H_ */
